- .github/workflows/cd.yml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> build: fix env variables

- packages/analytics-browser/README.md
- packages/analytics-browser/package.json
- packages/analytics-core/package.json
- Added tslib to project dependencies
- Fixed timing of src/version update in lifecycle
- Add readme
> fix: add missing dependency

- .github/workflows/cd.yml
- package.json
- packages/analytics-browser/package.json
- packages/analytics-core/package.json
- packages/analytics-types/package.json
context plugin library version
> fix: context plugin library version

- packages/analytics-browser/output/amplitude-snippet.js
- packages/analytics-browser/src/typings/browser-snippet.d.ts
- packages/analytics-browser/src/utils/snippet-helper.ts
- packages/analytics-browser/template/browser-snippet.template.js
- packages/analytics-browser/test/browser-client.test.ts
- packages/analytics-browser/test/utils/snippet-helper.test.ts
- packages/analytics-core/src/config.ts
> feat: add snippet promise support

- .github/workflows/cd.yml
Release pipeline makes repo changes based on the new version. These changes include:
* script loader snippet
* src/version.ts used by context plugin for `event.library`
> build: check in usable build artifacts

- .github/workflows/cd.yml
- lerna.json
- packages/analytics-browser/package.json
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> build: check in snippet

- README.md
- packages/analytics-browser/README.md
- packages/analytics-core/README.md
* Added snippet install instructions
* Added promise interface sample code
> docs(readme): add snippet install instructions and promise interface

- .github/workflows/s3-upload-test.yml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> build: test assume role in github actions

- .github/workflows/cd.yml
- .github/workflows/s3-upload-test.yml
- packages/analytics-browser/package.json
* Allow github actions to assume iam role to perform s3 api operations
* Update test workflow so we can test before trying in prod pipeline
> build: fix auth for publishing to aws s3

- .github/workflows/cd.yml
Add additional permissions for github token. Needs for aws auth to work.
> build: add github token additional permissions

- .github/workflows/cd.yml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> build: add github token content write permissions

- packages/analytics-browser/src/transports/fetch.ts
- packages/analytics-browser/test/transport/fetch.test.ts
- packages/analytics-core/src/config.ts
- packages/analytics-core/src/plugins/destination.ts
- packages/analytics-core/test/config.test.ts
* Fix error handling for fetch client
* Fix error message for error 400 and 413
* Fix setting log level of 0
> fix: fix error handling in fetch client

- package.json
- packages/analytics-browser-test/README.md
- packages/analytics-browser-test/jest.config.js
- packages/analytics-browser-test/package.json
- packages/analytics-browser-test/test/constants.ts
- packages/analytics-browser-test/test/index.test.ts
- packages/analytics-browser-test/test/responses.ts
- packages/analytics-browser-test/tsconfig.json
- packages/analytics-browser/package.json
- packages/analytics-core/src/messages.ts
- yarn.lock
* Setup up new private package in workspace
* Private packages are excluded from publish cycle
* Integration tests are in separate package to ensure testing is black box
* Use [nock](https://www.npmjs.com/package/nock) to intercept http requests
* Covers the following scenario
* case: event with custom config
* case: event with event options
* case: 400 error response
* case: 413 error response
* case: 429 error response
* case: 500 error response
* case: exhausting max retries
* case: missing api key
* case: client opt out
> build: setup integration testing

- packages/analytics-browser/src/browser-client.ts
> docs: fix typo for alias

- packages/analytics-browser-test/test/index.test.ts
- packages/analytics-core/src/core-client.ts
- packages/analytics-core/src/utils/event-builder.ts
- packages/analytics-core/test/utils/event-builder.test.ts
Fixes https://github.com/amplitude/Amplitude-TypeScript/issues/88
> fix: allow event level groups tracking

- .github/workflows/cd.yml
Adds authorization job to cd workflow
> build: add authorization job to cd workflow

- LICENSE
> chore: Add license file

- packages/analytics-core/src/core-client.ts
- packages/analytics-core/src/event-bridge/event-bridge-channel.ts
- packages/analytics-core/src/event-bridge/event-bridge-container.ts
- packages/analytics-core/src/event-bridge/event-bridge.ts
- packages/analytics-core/src/event-bridge/event-channel.ts
- packages/analytics-core/src/event-bridge/event-receiver.ts
- packages/analytics-core/test/event-bridge/event-bridge-channel.test.ts
- packages/analytics-core/test/event-bridge/event-bridge-container.test.ts
- packages/analytics-core/test/event-bridge/event-bridge.test.ts
- packages/analytics-core/test/event-bridge/event-receiver.test.ts
- packages/analytics-types/src/base-event.ts
- packages/analytics-types/src/core-client.ts
- packages/analytics-types/src/event-bridge.ts
- packages/analytics-types/src/index.ts
> feat: add event bridge components

- packages/analytics-browser/scripts/templates/browser-snippet.template.js
- packages/analytics-browser/src/browser-client.ts
- packages/analytics-browser/test/browser-client.test.ts
- Add regenerateDeviceId method
> feat: add regenerateDeviceId method

- packages/analytics-react-native/src/plugins/identity.ts
- packages/analytics-react-native/src/react-native-client.ts
- packages/analytics-react-native/src/utils/analytics-connector.ts
* Add analytics-connector to react-native client
> feat: react native analytics-connector

- packages/analytics-react-native/package.json
- packages/analytics-react-native/src/version.ts
Adds initial version for react-native package. Running the next release should create 0.1.0 for react-native package.
* Does your PR have a breaking change?:  Yes
> chore: react-native initial package version

- .gitignore
This PR add some missing items to the gitignore file.
No
> build: add macos and log files to gitignore

- README.md
- packages/analytics-browser/README.md
- packages/analytics-browser/package.json
- packages/analytics-node/README.md
- packages/analytics-node/package.json
- packages/analytics-react-native/README.md
- packages/analytics-react-native/package.json
- typedoc.json
* Adds node SDK to generated docs
* Updates root README.md to include node SDK in projects
* Updates npm access level
> chore: Node SDK release prep

- packages/analytics-browser/src/browser-client.ts
- packages/analytics-react-native/src/react-native-client.ts
Fix the typo and format issue in API doc:
> docs: fix typo and adjust markdown format

- .github/workflows/jira-issue-create.yml
updates auto ticket creation to dxoc board
* Merge PR
* Update github secrets: `JIRA_PROJECT`
> fix: updates auto ticket creation to dxoc board

- .github/workflows/jira-issue-create.yml
Update value shape for custom field
> fix: value shape for cutomfield

- packages/analytics-browser/README.md
- packages/analytics-react-native/README.md
> docs(reset): Add `reset` documentation

- .github/workflows/jira-issue-create-template.yml
- .github/workflows/jira-issue-create.yml
- .github/workflows/ts-jira-issue-create.yml
Make typescript Jira Create github action as a template.
Other SDK repos can reuse this github action flow directly.
> chore: GitHub template

- examples/react-native/app/README.md
- examples/react-native/expo-app/README.md
- docs: add instructions to run react-native example app
> docs: add instructions to run react-native example app

- packages/analytics-core/src/plugins/destination.ts
- packages/analytics-core/test/plugins/destination.test.ts
- packages/analytics-core/test/timeline.test.ts
- packages/analytics-types/src/base-event.ts
> feat: add 'extra' to eventOptions

- .github/workflows/jira-issue-create-template.yml
Removes extra space in ticket title
> fix: update jira workflow ticket name

- packages/analytics-browser/src/storage/cookie.ts
- packages/analytics-react-native/src/storage/cookie.ts
pass options to testStorage in CookieStorage.isEnabled()
> fix: pass options to testStorage

- packages/analytics-browser/src/utils/query-params.ts
- packages/analytics-react-native/src/utils/query-params.ts
Add conditional check for `window.location.search`
> fix: add conditional check for window.location.search

- packages/analytics-types/src/response.ts
- packages/analytics-types/tsconfig.json
> fix: removes @types/node from analytics-types package

- packages/analytics-types/src/client/web-client.ts
> fix: allow undefined parameter in public facing setUserId interface

- packages/analytics-client-common/src/attribution/campaign-parser.ts
- packages/analytics-client-common/src/attribution/constants.ts
Add additional "click id" fields that apply to attribution.
> feat: additional click id campaign params

- packages/analytics-types/package.json
- packages/analytics-types/tsconfig.es5.json
- packages/analytics-types/tsconfig.esm.json
- packages/analytics-types/tsconfig.json
Generates ESM output for analytics types package
Fixes: #214 
> build: generate esm output for analytics-types package

- packages/analytics-types/tsconfig.es5.json
- packages/analytics-types/tsconfig.esm.json
- packages/analytics-types/tsconfig.json
Fix in response to: https://github.com/amplitude/Amplitude-TypeScript/pull/225/files#r977318185
> build: fix tsconfig for analytics-types

- packages/marketing-analytics-browser/package.json
- packages/plugin-page-view-tracking-browser/package.json
- packages/plugin-web-attribution-browser/package.json
Publish marketing analytics plugin publicly
> build: set marketing analytics packages to public

- packages/analytics-browser/src/browser-client.ts
- packages/analytics-react-native/src/react-native-client.ts
update userId in identify call if eventOptions contains userId
> fix: update userId in identify call if eventOptions contains userId

- packages/analytics-browser/src/browser-client.ts
- packages/analytics-browser/test/browser-client.test.ts
- packages/analytics-react-native/src/react-native-client.ts
- packages/analytics-react-native/test/react-native-client.test.ts
update userId/deviceId in identify call if eventOptions contains userId/deviceId
> fix: update userId/deviceId in identify call if eventOptions contains userId/deviceId

- .eslintrc.js
- package.json
- packages/analytics-browser-test/test/index.test.ts
- packages/analytics-browser/package.json
- packages/analytics-browser/src/browser-client.ts
- packages/analytics-client-common/package.json
- packages/analytics-core/src/core-client.ts
- packages/analytics-core/src/messages.ts
- packages/analytics-core/src/timeline.ts
- packages/analytics-core/test/core-client.test.ts
- packages/analytics-core/test/timeline.test.ts
- packages/analytics-node/package.json
- packages/analytics-node/src/node-client.ts
- packages/analytics-react-native/package.json
- packages/analytics-react-native/src/react-native-client.ts
- packages/marketing-analytics-browser/package.json
invoke pre-init track fns after attribution
Fixed #246 
> fix: invoke pre-init track fns after attribution

- packages/analytics-browser/src/browser-client.ts
- packages/analytics-browser/src/config.ts
- packages/analytics-browser/src/storage/local-storage.ts
- packages/analytics-client-common/src/session-manager.ts
- packages/analytics-client-common/src/storage/cookie.ts
* Adds logging around cookie storage
* Plan is to release beta version then revert changes
> fix: add logging around cookie storage

- packages/analytics-react-native/README.md
Adds documentation about `setUserId`
> docs(setUserId): Add documentation about `setUserId`

- packages/analytics-browser/package.json
> build: fix yarn publish script

- packages/analytics-node/README.md
> docs: remove beta label for node

- .github/workflows/cd.yml
- .github/workflows/docs.yml
- .github/workflows/jira-issue-create-template.yml
- .github/workflows/s3-upload-test.yml
- Update Node env since node 12 is deprecated
> chore: fix cd github action

- packages/analytics-react-native/android/build.gradle
Updates required kotlin version for react native SDK. Fixes #310.
> fix: updates required kotlin version for react native SDK

- README.md
- examples/react-native/app/README.md
- examples/react-native/expo-app/README.md
- packages/analytics-browser/README.md
- packages/analytics-node/README.md
- packages/analytics-react-native/README.md
- packages/marketing-analytics-browser/README.md
We recently have some basic questions got raised from the GitHub issues.
We currently miss the link between GitHub and the developer center and GitHub page.  
Add links to README.md to expose those docs. 
> docs: link api reference and developer center docs in github

- packages/analytics-node/README.md
For Node SDK, one of user id or device is required. 
> docs: add user_id when track an event 

- package.json
- packages/marketing-analytics-browser/generated/amplitude-gtm-snippet.js
- packages/marketing-analytics-browser/rollup.config.js
- packages/marketing-analytics-browser/src/gtm-snippet-index.ts
- packages/marketing-analytics-browser/src/typings/browser-snippet.d.ts
- scripts/build/rollup.config.js
- scripts/publish/upload-to-s3.js
- scripts/templates/browser-snippet.template.js
- scripts/version/create-snippet.js
- yarn.lock
Current questions/issues hope I can get your help on.
> build: expose amplitudeGTM for GTM template

- packages/marketing-analytics-browser/generated/amplitude-gtm-snippet.js
- scripts/build/rollup.config.js
- scripts/templates/browser-snippet.template.js
- scripts/version/create-snippet.js
> build: fix the CDN for marketing analytics browser GTM

- packages/marketing-analytics-browser/src/gtm-snippet-index.ts
> build: fix the issue in marketing analytics browser GTM template

- examples/plugins/remove-event-key/index.test.ts
- packages/analytics-core/src/timeline.ts
- packages/analytics-core/test/timeline.test.ts
- packages/analytics-types/src/plugin.ts
- packages/marketing-analytics-browser/test/plugins/context.test.ts
- packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts
Update Plugin implementation to allow for dropping events
> feat: update Plugin implementation to allow for dropping events

- packages/analytics-core/src/config.ts
- packages/analytics-core/test/config.test.ts
> fix: do not overwrite flushIntervalMillis=0 with default value (10 seconds)

- packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
Fixes #397 
* Does your PR have a breaking change? No, it fixes a regression
> fix: Reference error for location

- scripts/version/create-snippet.js
Refer to https://github.com/amplitude/Amplitude-TypeScript/pull/408
> build: remove unnecessary beta script guard

- packages/analytics-browser/README.md
- packages/analytics-node/README.md
- packages/analytics-react-native/README.md
- packages/marketing-analytics-browser/README.md
- packages/plugin-page-view-tracking-browser/README.md
- packages/plugin-web-attribution-browser/README.md
* Update install instructions to pin to ^1.0.0 to not accidentally read instructions for v1, but install v2.
* Update internal hyperlinks to v1.x branch
> docs: update instructions and docs to reference 1.0

- CONTRIBUTING.md
- README.md
- packages/analytics-browser/README.md
* Updates `README.md` in project root to specify V1 and V2 and their respective links
* Updates `CONTRIBUTING.md` to include instructions to fork, which branch to branch off and create a pull request against.
* Updates Browser SDK 2.0 `README.md` to only include quick start examples and refer to developer center for in-depth documentation.
> docs: update sdk documentation in readme

- packages/analytics-core/src/plugins/destination.ts
- packages/analytics-core/test/plugins/destination.test.ts
- packages/analytics-node/src/transports/http.ts
- packages/analytics-types/src/response.ts
Cherry picks commit: 86de7bd75c564601d980c029e548fe0303ba43f2 from this PR: https://github.com/amplitude/Amplitude-TypeScript/pull/415
> feat: log response body from API to logger

- packages/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AmplitudeReactNativeModule.kt
- packages/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AndroidContextProvider.kt
- packages/analytics-react-native/ios/AmplitudeReactNative.m
- packages/analytics-react-native/ios/AmplitudeReactNative.swift
- packages/analytics-react-native/src/plugins/context.ts
Based on https://github.com/amplitude/Amplitude-Kotlin/pull/125
> fix: do not fetch advertising Id if adid tracking is disabled

- packages/analytics-browser/src/browser-client-factory.ts
- packages/analytics-browser/src/browser-client.ts
- packages/analytics-browser/src/index.ts
- packages/analytics-browser/test/browser-client.test.ts
- packages/analytics-browser/test/helpers/mock.ts
- packages/analytics-browser/test/index.test.ts
- packages/analytics-react-native/src/react-native-client.ts
- packages/analytics-types/src/client/web-client.ts
- scripts/templates/browser-snippet.template.js
> feat: added extendSession() method to Browser Client (#425)

- packages/analytics-core/src/plugins/destination.ts
- packages/analytics-core/test/plugins/destination.test.ts
* Output more compact response JSON for [AMP-77261](https://amplitude.atlassian.net/browse/AMP-77261?focusedCommentId=193204)
[AMP-77261]: https://amplitude.atlassian.net/browse/AMP-77261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: compact logged response body's for AMP-77261

- packages/analytics-browser/jest.config.js
- packages/analytics-browser/src/__mocks__/det-notification.ts
- packages/analytics-browser/src/browser-client.ts
- packages/analytics-browser/src/det-notification.ts
- packages/analytics-browser/test/det-notification.test.ts
- packages/analytics-browser/test/setup.js
* Adds logs when default tracking is enabled
> fix: adds logs when default tracking is enabled

- packages/analytics-types/src/client/node-client.ts
- packages/analytics-types/src/client/web-client.ts
- packages/analytics-types/src/plugin.ts
> fix: types for plugins to be env specific (#440)

- .github/workflows/jira-issue-create-template.yml
* add subcomponent to issue workflow inputs
> chore: add subcomponent to issue workflow inputs

- .github/workflows/jira-issue-create-template.yml
* correctly set component field in issue workflow
> chore: correctly set component field in issue workflow

- packages/plugin-web-attribution-browser/package.json
> fix: missing core dependency for web attribution

- .github/workflows/publish-v1.yml
Set github token using actions/checkout@v3
> build: fix setting github token

- .github/workflows/publish-v1.yml
Reverts amplitude/Amplitude-TypeScript#472
> revert: fix setting github token

- packages/analytics-react-native/src/plugins/context.ts
- packages/analytics-react-native/test/plugins/context.test.ts
Fix the context plugin to include app version from native mobile.
related to #179 
* Does your PR have a breaking change?:   NO
> fix: react-native fix context plugin to include app version on mobile

- packages/analytics-react-native/src/react-native-client.ts
- packages/analytics-react-native/test/react-native-client.test.ts
- packages/analytics-react-native/test/react-native-sessions.test.ts
Slightly updates session logic and added new tests (copied from Amplitude-Kotlin).
Additional notes - in the Jira task.
> fix: updated session logic and tests

- packages/plugin-user-agent-enrichment-browser/package.json
Bump plugin-user-agent-enrichment-browser to 1.0.0-beta.0 in preparation for 1.0.0 release
> chore: plugin-user-agent-enrichment-browser@1.0.0-beta.0

- packages/plugin-page-view-v1-enrichment/package.json
- packages/plugin-user-agent-enrichment-browser/package.json
> chore: add publish script to plugins to upload the script into cdn

- packages/plugin-page-view-v1-enrichment/package.json
Test: tested in an app example. Works as expected. will graduate this package, since it's going to be public facing.
Same pr like [this](https://github.com/amplitude/Amplitude-TypeScript/pull/513)  for bumping up to a major version.
> chore: plugin-page-view-v1-enrichment@1.0.0-beta.0

- examples/react-native/legacyDataMigration/yarn.lock
- packages/analytics-react-native/src/migration/remnant-data-migration.ts
Fix a TODO warning (affects migration example app).
> chore: fix TODO warning

- packages/plugin-ga-events-forwarder-browser/package.json
> fix: set ga events forwarder plugin private

- packages/analytics-react-native/ios/AmplitudeReactNative.swift
- packages/analytics-react-native/ios/AppleContextProvider.swift
Use logic from https://github.com/amplitude/Amplitude-Swift/blob/main/Sources/Amplitude/Plugins/ContextPlugin.swift#L65-L75
Can't test in simulator.
> fix: collect 'carrier' data in react-native iOS

- packages/plugin-ga-events-forwarder-browser/src/constants.ts
- packages/plugin-ga-events-forwarder-browser/src/ga-events-forwarder.ts
- packages/plugin-ga-events-forwarder-browser/src/helpers.ts
- packages/plugin-ga-events-forwarder-browser/test/ga-events-forwarder.test.ts
- packages/plugin-ga-events-forwarder-browser/test/helpers.test.ts
Prevents sending GA automatically collected events if DET is enabled
> feat: dedupe det events & ga automatic events

- packages/analytics-browser/src/config.ts
- packages/analytics-browser/test/config.test.ts
Fixes https://github.com/amplitude/Amplitude-TypeScript/issues/551
* Does your PR have a breaking change?: Not really
> fix(browser): allow cookie options to be customized #548

- packages/analytics-browser/test/config.test.ts
Add a test to verify that
1. default cookie domain is set correctly
2. custom cookie domain is set correctly
> test: add tests to verify setting cookie domain option works correctly

- packages/plugin-session-replay-browser/README.md
- packages/session-replay-browser/README.md
Update docs to reflect that replays are collected
> docs(session replay): update readme to reflect collection

- packages/analytics-browser/generated/amplitude-bookmarklet-snippet.js
- packages/analytics-browser/rollup.config.js
- scripts/build/rollup.config.js
- scripts/templates/browser-bookmarklet.template.js
- scripts/templates/browser-snippet.template.js
- scripts/version/create-bookmarklet-snippet.js
- scripts/version/create-bookmarklet.js
- feat: add bookmarklet
To use it:
1. In browser bookmark bar, "Add Page"
1. Put any name
1. Copy the code below, update the `YOUR_API_KEY` to your API key
1. Put the code in the URL input box
1. Save
1. Open any web site
1. Click on the bookmark
1. Now Amplitude SDK with more trackings is enabled, click/change any item to track
Limitations:
- Ads blocker might block the script loading
- CSP might block the script loading, depending on the target website security configuration
The bookmarklet will:
- Load the SDK from CDN
- Initialize the SDK with your API key (and user id if updated)
- Initialize the inline [auto-tracking plugin](https://github.com/amplitude/Amplitude-TypeScript/compare/add-bookmarklet?expand=1#diff-6c206852d91cf818395e72ab4930bbffffbb605dc369e24d783b005432c9e0c2R58-R213) …
> feat: add bookmarklet

- packages/plugin-auto-tracking-browser/package.json
- build: temp disable auto-tracking package publish
> build: temp disable auto-tracking package publish

- packages/analytics-browser/README.md
* update README for lerna to pickup package changes
* Fix release for #591
> fix: update README for lerna to pickup package changes

- packages/analytics-browser/README.md
- scripts/templates/browser-snippet.template.js
* Cherry pick #591 to `v1.x` branch
* Update README to get lerna to detect package changes
> fix: Amp 85112 set user id is not queued in snippet v1

- packages/analytics-browser-test/test/index.test.ts
- packages/analytics-core/src/plugins/destination.ts
- packages/analytics-core/test/plugins/destination.test.ts
- packages/analytics-types/src/payload.ts
https://amplitude.atlassian.net/browse/AMP-87178
> feat: add client upload time

- packages/plugin-session-replay-browser/package.json
- packages/session-replay-browser/package.json
- packages/session-replay-browser/src/session-replay.ts
- packages/session-replay-browser/test/session-replay.test.ts
- yarn.lock
Use the internal fork of rrweb, which includes some customizations specific for our usecase
> fix(session replay): use internal fork of rrweb

- packages/plugin-default-event-tracking-advanced-browser/README.md
- packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
- packages/plugin-default-event-tracking-advanced-browser/test/default-event-tracking-advanced.test.ts
- feat: add default data attr selector
> feat: add default data attr selector

- .github/workflows/feature-branch-prerelease.yml
A fix PR to https://github.com/amplitude/Amplitude-TypeScript/pull/621
Cannot go into If condition because GitHub Actions treats all input types as strings, even if they are defined as boolean
> ci: update dryRun type to string

- packages/analytics-browser/README.md
This PR is to set NPM `latest` tag to the correct version.
> fix: npm latest tag

- packages/plugin-session-replay-browser/package.json
> chore(session replay): manually bump version to 0.8.0

- packages/analytics-browser-test/package.json
- yarn.lock
Update test package's dependency on browser SDK
> build: fix integration test dependency on analytics SDK

- packages/plugin-session-replay-browser/src/session-replay.ts
- packages/plugin-session-replay-browser/src/typings/session-replay.ts
- packages/plugin-session-replay-browser/test/session-replay.test.ts
- packages/session-replay-browser/src/config.ts
- packages/session-replay-browser/src/session-replay.ts
- packages/session-replay-browser/src/typings/session-replay.ts
- packages/session-replay-browser/test/session-replay.test.ts
Expose block selector for ebay. 
* [x ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-TypeScript/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
no
> feat: expose block selector from rrweb to SR plugin/SDK 

- packages/plugin-session-replay-browser/src/session-replay.ts
- packages/plugin-session-replay-browser/test/session-replay.test.ts
* remove sr enrichment plugin on teardown
* clear plugin.client and plugin.config refs in teardown to prevent mem leaks
> fix: Amp 90629 remove sr enrichment plugin on teardown

- packages/analytics-browser/src/browser-client.ts
- packages/analytics-browser/test/browser-client.test.ts
* revert #636 due to issues with SR plugin
> revert: Amp 90349 revert session id insert before plugin setup

- packages/session-replay-browser/src/session-replay.ts
> fix(session replay): additional undefined check for events

- packages/plugin-default-event-tracking-advanced-browser/src/constants.ts
- build: bump visual tagger version for recent [fix](https://github.com/amplitude/visual-tagging-selector/pull/8)
> build: bump visual tagger version

- scripts/build/rollup.config.js
Enabling source maps for the browser and GTM SDKs
> build: Enable source maps for browser and gtm

- packages/plugin-default-event-tracking-advanced-browser/README.md
- packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
- docs: update deta plugin desc
> docs: update deta plugin desc

- packages/plugin-default-event-tracking-advanced-browser/src/constants.ts
feat: bump selector version to 0.1.1 (https://github.com/amplitude/visual-tagging-selector/pull/10)
> feat: bump selector version to 0.1.1

- packages/plugin-session-replay-browser/package.json
- packages/session-replay-browser/package.json
Bumping version from v0.x -> v1.x for SR GA
> chore(session replay): bump sr sdk version from 0 to 1

- packages/plugin-session-replay-browser/README.md
- packages/session-replay-browser/README.md
No functional change, just updates documentations for the two options that we didn't document. 
> docs: add undocumented options for debugMode and privacy

- packages/plugin-default-event-tracking-advanced-browser/src/constants.ts
- packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
- packages/plugin-default-event-tracking-advanced-browser/src/index.ts
- packages/plugin-default-event-tracking-advanced-browser/src/libs/messenger.ts
- packages/plugin-default-event-tracking-advanced-browser/test/default-event-tracking-advanced.test.ts
feat(deta): pass the on track message for instrumentations
Also refactor the types and export, so we can use these types in Amplitude side potentially.
> feat(deta): pass the on track message for instrumentations

- packages/analytics-browser-test/test/index.test.ts
- packages/analytics-browser/src/browser-client.ts
- packages/analytics-browser/src/config.ts
- packages/analytics-browser/test/browser-client.test.ts
- packages/analytics-client-common/src/default-tracking.ts
- packages/analytics-types/src/config/browser.ts
- packages/analytics-types/src/page-view-tracking.ts
- packages/analytics-types/src/user-session.ts
- packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
- packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts
https://amplitude.atlassian.net/browse/AMP-93561
Add a pageCount in the DET page view for analyzing the landing page and bounce rate.
- Reset the pageCount to 0 at the beginning of the session.
- Increment the pageCount with each page view during a session.
- 
> feat: landing page improvement

- packages/analytics-browser/src/config.ts
> fix: fix typo for pageCounter

- packages/plugin-default-event-tracking-advanced-browser/src/constants.ts
- packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
- packages/plugin-default-event-tracking-advanced-browser/src/libs/messenger.ts
feat(deta): support eu and staging origins
> feat(deta): support eu and staging origins

- packages/plugin-default-event-tracking-advanced-browser/src/constants.ts
Related to: https://github.com/amplitude/visual-tagging-selector/pull/13
> build: bump visual selector version to 0.2.0

- packages/analytics-browser/generated/amplitude-bookmarklet-snippet.js
- scripts/templates/browser-bookmarklet.template.js
- scripts/version/create-bookmarklet-snippet.js
feat: update bookmarklet snippet
The plugin has been renamed and the version has been updated here.
> feat: update bookmarklet snippet

- packages/analytics-core/src/plugins/destination.ts
- packages/analytics-core/test/helpers/util.ts
- packages/analytics-core/test/plugins/destination.test.ts
So this PR should
- Fix the original losing events problem which has been reverted https://github.com/amplitude/Amplitude-TypeScript/pull/673
- Stop accumulating events which are caused by the https://github.com/amplitude/Amplitude-TypeScript/pull/673
> fix: fix event drop issue

- packages/analytics-node/package.json
- packages/analytics-react-native/package.json
- yarn.lock
While graduate the beta version, github action cannot recognize the latest change in React Native and Node. 
> build: fix the dependency issue

- packages/session-replay-browser/src/session-replay.ts
- packages/session-replay-browser/test/session-replay.test.ts
We've observed that it is possible to generate many duplicate track calls, because there are code paths that do not stop the recording before starting it again. This change makes it so that the recording is always stopped right before it is started again, ensuring those duplicate track calls cannot be made.
> fix(session replay): always stop recording before starting anew

- packages/analytics-browser/generated/amplitude-bookmarklet-snippet.js
- scripts/templates/browser-bookmarklet.template.js
- scripts/version/create-bookmarklet-snippet.js
feat: update bookmarklet to use autocapture plugin
> feat: update bookmarklet to use autocapture plugin

- packages/analytics-client-common/src/attribution/web-attribution.ts
- packages/analytics-client-common/test/attribution/web-attribution.test.ts
The last PR (change web attribution plugin to util function) didn't consider the direct traffic in the session event. 
Adding that logic checking in the webAttribution.init().
> fix: add logic to escape campaign tracking for direct traffic in session

- packages/analytics-browser/src/config.ts
- packages/analytics-browser/test/config.test.ts
- packages/analytics-react-native/src/config.ts
- packages/analytics-react-native/test/config.test.ts
This PR does the same for v1.x as https://github.com/amplitude/Amplitude-TypeScript/pull/738 for main branch
> fix: location is polyfilled to an empty object

- packages/analytics-types/src/config/browser.ts
- packages/analytics-types/src/config/core.ts
Add comments and the default value for configuration
> docs: add comments and default value for configuration

- packages/analytics-browser/package.json
> test: fix the playground:react-spa command

- packages/plugin-autocapture-browser/src/autocapture-plugin.ts
- packages/plugin-autocapture-browser/src/index.ts
Export `AutocaptureOptions` for remote config type.
Use `fix` to bump the version. 
> fix(plugin-autocapture-browser): export AutocaptureOptions

- packages/analytics-client-common/src/storage/cookie.ts
- packages/analytics-client-common/test/storage/cookies.test.ts
Add logs to cookie storage for https://github.com/amplitude/Amplitude-TypeScript/pull/686 and https://github.com/amplitude/Amplitude-TypeScript/issues/664
> fix: add cookie storage logs

- packages/targeting/jest.config.js
- packages/targeting/package.json
- packages/targeting/src/index.ts
- packages/targeting/src/targeting-factory.ts
- packages/targeting/src/targeting-idb-store.ts
- packages/targeting/src/targeting.ts
- packages/targeting/src/typings/targeting.ts
- packages/targeting/test/flag-config-data.ts
- packages/targeting/test/jest-setup.js
- packages/targeting/test/targeting-factory.test.ts
- packages/targeting/test/targeting-idb-store.test.ts
- packages/targeting/test/targeting.test.ts
Carving out the targeting specific updates from this feature branch: https://github.com/amplitude/Amplitude-TypeScript/pull/750/files
> feat(targeting): add support for multiple events in targeting evaluation

- packages/targeting/src/targeting.ts
- packages/targeting/test/flag-config-data/catch-all.ts
- packages/targeting/test/flag-config-data/event-props.ts
- packages/targeting/test/flag-config-data/multiple-conditions.ts
- packages/targeting/test/flag-config-data/multiple-events.ts
- packages/targeting/test/flag-config-data/user-props.ts
- packages/targeting/test/targeting.test.ts
Add unit tests to track different types of supported conditions
> test(targeting): add unit tests for different flag condition types

- packages/plugin-autocapture-browser/package.json
> chore(plugin-autocapture-browser): use alpha tag

- packages/plugin-autocapture-browser/src/constants.ts
Update autocapture to also use the latest alpha version of Visual Labeling
> feat(plugin-autocapture-browser): update visual labeling to latest 1.0.0-alpha

- packages/session-replay-browser/src/session-replay.ts
We should always record if debugMode is true, otherwise the replay will be a confusing experience.
> fix(session replay): ignore focus should allow recording to continue as well

- packages/analytics-browser-test/test/web-attribution.test.ts
Relate to this [Jira Ticket](https://amplitude.atlassian.net/browse/AMP-104091)
Prove that for SPA by resetting the referrer after the first hit, direct traffic won't drop the UTM Campaign during a session.
> test: add more test for SPA Rogue Referral issue

- packages/plugin-session-replay-browser/src/session-replay.ts
- packages/plugin-session-replay-browser/test/session-replay.test.ts
- packages/session-replay-browser/src/config/types.ts
- packages/session-replay-browser/src/events/events-manager.ts
- packages/session-replay-browser/src/track-destination.ts
- packages/session-replay-browser/src/typings/session-replay.ts
- packages/session-replay-browser/test/track-destination.test.ts
Adding some version data to the headers.
> fix(session replay): add version and sdk type

- .github/workflows/feature-branch-prerelease.yml
- .github/workflows/publish-v2.yml
- lerna.json
Copying over two PRs from `main` to `v1.x` to support feature branch releases:
https://github.com/amplitude/Amplitude-TypeScript/pull/621
https://github.com/amplitude/Amplitude-TypeScript/pull/622
> ci: prerelease feature branch

- .github/workflows/feature-branch-prerelease.yml
Update prerelease script to capture all changes from main
> ci: update prerelease script to capture all changes from main

- packages/session-replay-browser/package.json
- yarn.lock
Update package to include a change in rrweb that removes negative lookback in the CSS regex.
> chore(session replay): update rrweb package

- packages/analytics-browser/package.json
- packages/analytics-browser/src/config/joined-config.ts
- packages/analytics-browser/test/config/joined-config.test.ts
- yarn.lock
Incorporate these changes: https://github.com/amplitude/Amplitude-TypeScript/pull/855
> fix(browser): bump remote config package

- packages/session-replay-browser/src/session-replay.ts
- packages/session-replay-browser/test/session-replay.test.ts
A Jenkins error was reported in https://amplitude.atlassian.net/browse/AMP-108769. It was caused by the unhandled idb open error. This PR handles it when creating the events managers. The events manager creation fails when the [idb store creation](https://amplitude.sourcegraph.com/github.com/amplitude/Amplitude-TypeScript@v1.x/-/blob/packages/session-replay-browser/src/events/events-idb-store.ts?L95) fails, and it skips adding the events manager so no replays will be captured then.
> fix(session-replay-browser): handle exceptions when creating an events manager

- packages/analytics-remote-config/src/remote-config.ts
- packages/analytics-remote-config/test/remote-config.test.ts
- packages/session-replay-browser/src/session-replay.ts
- packages/session-replay-browser/test/session-replay.test.ts
We've noticed a number of edge cases that are hard to reproduce, this adds some guards to prevent potential errors.
> fix(session-replay-browser): paranoia fixes for edge cases

- packages/session-replay-browser/src/config/joined-config.ts
- packages/session-replay-browser/test/config/joined-config.test.ts
This also helps remove an unnecesary need for a nullish check.
> fix(session-replay-browser): make joined config generator immutable

- packages/session-replay-browser/src/events/events-idb-store.ts
- packages/session-replay-browser/test/events-idb-store.test.ts
Adding a try/catch for graceful error handling.
> fix(session replay): add error handling for store

- packages/plugin-session-replay-browser/src/session-replay.ts
- packages/plugin-session-replay-browser/test/session-replay.test.ts
Adds try/catch logic to all the plugin interface APIs to prevent errors that can interrupt the functioning of the analytics browser SDK. 
An example snippet used to verify that the browser SDK can fail due to plugin failures. 
```
window.amplitude.add({
setup: function(s) {
console.log("initializing plugin");
throw Error("failed~~~~~~~");
}
})
window.amplitude.init("6151e18fcbce1f94010e8791964d2a71")
```
> fix: sr plugin failure isolation

- packages/plugin-session-replay-react-native/amplitude-plugin-session-replay-react-native.podspec
- packages/plugin-session-replay-react-native/android/build.gradle
Updating Android and iOS SR SDK dependency
> fix: updating underlying iOS and Android dependencies

- packages/analytics-remote-config/src/remote-config.ts
- packages/analytics-remote-config/src/types.ts
- packages/plugin-session-replay-browser/src/session-replay.ts
- packages/plugin-session-replay-browser/src/typings/session-replay.ts
- packages/plugin-session-replay-browser/test/session-replay.test.ts
- packages/session-replay-browser/src/config/joined-config.ts
- packages/session-replay-browser/src/config/types.ts
- packages/session-replay-browser/src/events/base-events-store.ts
- packages/session-replay-browser/src/events/event-compressor.ts
- packages/session-replay-browser/src/events/events-idb-store.ts
- packages/session-replay-browser/src/events/events-manager.ts
- packages/session-replay-browser/src/events/events-memory-store.ts
- packages/session-replay-browser/src/helpers.ts
- packages/session-replay-browser/src/hooks/click.ts
- packages/session-replay-browser/src/identifiers.ts
- packages/session-replay-browser/src/session-replay.ts
- packages/session-replay-browser/src/typings/session-replay.ts
Reverts amplitude/Amplitude-TypeScript#926
> Revert "feat(session-replay-browser): supporting string session id"

- packages/analytics-remote-config/src/remote-config.ts
- packages/analytics-remote-config/src/types.ts
Typing update to remote config interface to support custom session ids
> feat(analytics-remote-config): support custom session id

- packages/plugin-session-replay-browser/src/session-replay.ts
- packages/plugin-session-replay-browser/src/typings/session-replay.ts
- packages/plugin-session-replay-browser/test/session-replay.test.ts
- packages/session-replay-browser/src/config/joined-config.ts
- packages/session-replay-browser/src/config/types.ts
- packages/session-replay-browser/src/events/base-events-store.ts
- packages/session-replay-browser/src/events/event-compressor.ts
- packages/session-replay-browser/src/events/events-idb-store.ts
- packages/session-replay-browser/src/events/events-manager.ts
- packages/session-replay-browser/src/events/events-memory-store.ts
- packages/session-replay-browser/src/helpers.ts
- packages/session-replay-browser/src/hooks/click.ts
- packages/session-replay-browser/src/identifiers.ts
- packages/session-replay-browser/src/session-replay.ts
- packages/session-replay-browser/src/typings/session-replay.ts
Revert the revert of https://github.com/amplitude/Amplitude-TypeScript/pull/926
> feat(session-replay): supporting string session id

- packages/plugin-session-replay-react-native/amplitude-plugin-session-replay-react-native.podspec
> fix: update ios session replay version for react native

- packages/analytics-browser/test/browser-client.test.ts
[AMP-102589]
Fix flaky test by mocking Date.now().
[AMP-102589]: https://amplitude.atlassian.net/browse/AMP-102589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: fix flaky test

- packages/analytics-client-common/src/attribution/helpers.ts
- packages/analytics-client-common/src/attribution/web-attribution.ts
- packages/analytics-client-common/test/attribution/helpers.test.ts
- packages/plugin-web-attribution-browser/src/web-attribution.ts
[AMP-119380]
Add comments when deciding whether to fire an identify event to update campaign. 
[AMP-119380]: https://amplitude.atlassian.net/browse/AMP-119380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add comments in isNewCampaign()

- packages/analytics-browser/test/browser-client.test.ts
Cherry pick https://github.com/amplitude/Amplitude-TypeScript/pull/940
> test: fix flaky test (#940)

- packages/plugin-session-replay-react-native/README.md
Adding docs for capturing web views within React Native Session Replay
> fix: Adding docs for capturing web views within React Native Session Replay

- packages/analytics-browser-test/test/index.test.ts
- packages/analytics-core/src/revenue.ts
- packages/analytics-core/test/revenue.test.ts
- packages/analytics-types/src/base-event.ts
- packages/analytics-types/src/event.ts
Adding the ability to send currency code to Amplitude
> fix: ability to send revenue currency to amplitude

- packages/session-replay-browser/src/config/local-config.ts
- packages/session-replay-browser/src/index.ts
- packages/session-replay-browser/src/logger.ts
- packages/session-replay-browser/src/session-replay.ts
- packages/session-replay-browser/test/logger.test.ts
Main branch version of https://github.com/amplitude/Amplitude-TypeScript/pull/965
> fix(session replay): reduce chance of recursive loop with console tracking

- examples/plugins/page-view-tracking-enrichment/index.test.ts
Amend https://github.com/amplitude/Amplitude-TypeScript/pull/980. Update page view event name in the example enrichment plugin.
> test(examples): update page view event name

- packages/analytics-core/src/plugins/destination.ts
- packages/analytics-core/test/config.test.ts
- packages/analytics-core/test/identify.test.ts
- packages/analytics-core/test/logger.test.ts
- packages/analytics-core/test/plugins/destination.test.ts
- packages/analytics-core/test/plugins/identity.test.ts
- packages/analytics-core/test/timeline.test.ts
- packages/analytics-core/test/transports/base.test.ts
- packages/analytics-core/test/transports/fetch.test.ts
- packages/analytics-core/test/utils/debug.test.ts
- packages/analytics-core/test/utils/event-builder.test.ts
- packages/analytics-core/test/utils/result-builder.test.ts
A follow up PR of https://github.com/amplitude/Amplitude-TypeScript/pull/989 to clean imports in analytics-core tests. 
> test(analytics-core): replace analytics-types with analytics-core

- packages/plugin-session-replay-react-native/amplitude-plugin-session-replay-react-native.podspec
- packages/plugin-session-replay-react-native/android/build.gradle
- packages/plugin-session-replay-react-native/android/src/main/java/com/amplitude/pluginsessionreplayreactnative/PluginSessionReplayReactNativeModule.kt
- packages/plugin-session-replay-react-native/example/App.tsx
- packages/plugin-session-replay-react-native/example/ios/Podfile.lock
- packages/plugin-session-replay-react-native/example/ios/example.xcodeproj/project.pbxproj
- packages/plugin-session-replay-react-native/example/package.json
- packages/plugin-session-replay-react-native/example/yarn.lock
- packages/plugin-session-replay-react-native/ios/PluginSessionReplayReactNative.mm
- packages/plugin-session-replay-react-native/ios/PluginSessionReplayReactNative.swift
- packages/plugin-session-replay-react-native/src/session-replay.ts
- Update SR SDK versions
- Add start/stop functions to plugin
- Fix late init error on Android
> fix: add start and stop functions and fix lateinit crash on Android

- packages/analytics-browser/src/config.ts
- packages/analytics-types/src/config/browser.ts
Adding version to the analytics-browser config for plugin access.
> feat(analytics-browser): add browser version to config

- packages/analytics-browser/src/config.ts
- packages/analytics-browser/test/config.test.ts
> chore(analytics browser): add version to config class

- packages/analytics-types/src/config/browser.ts
> fix: typo in a docblock

- packages/analytics-browser/src/index.ts
- packages/analytics-core/src/index.ts
Fix https://github.com/amplitude/Amplitude-TypeScript/issues/1004
> fix(analytics-browser): export more types

- packages/analytics-browser/src/storage/local-storage.ts
> fix: remove log statements

- .github/workflows/jira-issue-create-template.yml
See https://github.com/actions/runner-images/issues/11101
> chore: update jira issue create to run on ubuntu-latest

- packages/plugin-experiment-browser/package.json
> chore(plugin-experiment-browser): fix package.json

- packages/unified/package.json
- packages/unified/src/library.ts
- packages/unified/src/unified.ts
- packages/unified/src/version.ts
- packages/unified/test/library.test.ts
- packages/unified/test/unified.test.ts
Append unified library prefix and version 
Before: `amplitude-ts/x.y.z`
After: `amplitude-ts-unified/a.b.c-amplitude-ts/x.y.z`
> fix(unified): update library

- .github/workflows/publish-v2.yml
- package.json
> chore: set --yes on lerna publish

- packages/analytics-react-native/test/mock/setup-mobile.ts
- packages/session-replay-browser/src/observers.ts
- packages/session-replay-browser/src/session-replay.ts
- packages/session-replay-browser/test/observers.test.ts
- packages/session-replay-browser/test/session-replay.test.ts
There's some improvements to the networkObserver that are incoming that will make this work better. Will bring this back later.
> revert: PR 1058

- package.json
> chore: undo publishing from-package mode

- packages/plugin-experiment-browser/README.md
- packages/unified/README.md
Add README.md to `@amplitude/unified` and `@amplitude/plugin-experiment-browser`. 
Will create a PR to amplitude-docs later. 
> docs(unified): add readme

- packages/analytics-core/src/storage/cookie.ts
- rename `testStrorage` to `testStorage` in cookie storage `isEnabled`
- run `yarn workspace @amplitude/analytics-core typecheck`
- `yarn workspace @amplitude/analytics-core typecheck`
> chore(analytics-core): fix typo by codex

- .github/workflows/publish-v2.yml
> chore: add fetch tags to publish release script

- .github/workflows/publish-v2.yml
- packages/analytics-core/README.md
> fix(analytics-core): bump version

- .github/workflows/e2e.yml
> ci: temporarily remove nx

- .github/workflows/ci-nx.yml
- nx.json
- package.json
- packages/analytics-core/src/network-observer.ts
- packages/plugin-autocapture-browser/package.json
- packages/plugin-autocapture-browser/test/autocapture-plugin/track-action-clicks.test.ts
- packages/plugin-autocapture-browser/test/default-event-tracking-advanced.test.ts
- packages/plugin-autocapture-browser/test/mock-browser-client.ts
- packages/plugin-network-capture-browser/package.json
- packages/plugin-network-capture-browser/test/autocapture-plugin/track-network-event.test.ts
- packages/plugin-network-capture-browser/test/mock-browser-client.ts
- packages/plugin-page-view-tracking-browser/package.json
- packages/plugin-page-view-tracking-browser/test/mock-browser-client.ts
- packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts
- typedoc.json
Integrates NX build system to improve build performance and resolves circular dependency issues that were causing build failures. Adds comprehensive test infrastructure improvements across plugin packages with new NX-powered commands for efficient development workflows.
‼️ I didn't update the original ci.yml file instead I create a new ci-nx.yml file to compare their running results in GHA. Let's keep them for several days to see how they both work. NOTE we will ultimately override ci.yml with the content in ci-nx.yml. Also I'm not planning to update publish-v2.yml as I believe we should still run the whole repo when publish just to gain more confidence. 
- Added NX configuration (`nx.json`) for build, test, and lint task orchestration
- Added NX scripts to root `package.json` with …
> build: add NX build system integration and improve test infrastructure

- packages/plugin-session-replay-browser/scripts/publish/upload-to-s3.js
- packages/segment-session-replay-plugin/scripts/publish/upload-to-s3.js
- packages/session-replay-browser/scripts/publish/upload-to-s3.js
Upload gzip file to CDN instead of the .js version. 
> fix(session replay): add gzip to cdn

- AGENTS.md
Add AGENTS.md for codex. https://platform.openai.com/docs/codex#using-agents-md
> chore: add AGENTS.md for codex

- packages/plugin-web-vitals-browser/src/web-vitals-plugin.ts
- packages/plugin-web-vitals-browser/test/web-vitals-plugin.test.ts
* Add TTFB score too
* Remove deduplication (metric ID) and just track metrics on first visibility change to hidden
> fix(plugin-web-vitals-browser): add TTFB

- packages/plugin-session-replay-react-native/android/build.gradle
lock analytics-android version to fix LogCatLogger missing error
> fix: [SR RN] LogCatLogger missing error

- packages/session-replay-browser/README.md
Changing the performanceConfig default to true in README.
> chore(session-replay): update readme

- packages/segment-session-replay-plugin-react-native/README.md
- packages/segment-session-replay-plugin-react-native/babel.config.js
- packages/segment-session-replay-plugin-react-native/jest.config.js
- packages/segment-session-replay-plugin-react-native/jest.setup.js
- packages/segment-session-replay-plugin-react-native/package.json
- packages/segment-session-replay-plugin-react-native/src/index.ts
- packages/segment-session-replay-plugin-react-native/src/segment-session-replay-plugin.ts
- packages/segment-session-replay-plugin-react-native/src/version.ts
- packages/segment-session-replay-plugin-react-native/test/segment-session-replay-plugin.test.ts
- packages/segment-session-replay-plugin-react-native/tsconfig.build.json
- packages/segment-session-replay-plugin-react-native/tsconfig.json
… replay plugin for react native
Add Segment Plugin for Session Replay React Native
> feat(segment-plugin-session-replay-react-native) add segment plugin for session replay

- packages/analytics-node-ai/jest.config.js
- packages/analytics-node-ai/src/openai.ts
- packages/analytics-node-ai/tsconfig.json
Overload OpenAI client to track user & agent messages using the Chat Completion APIs. 
> feat(analytics-node-ai): track user & agent messages

- .github/workflows/ci-nx.yml
- .github/workflows/ci.yml
- Revert [the revert to use nx for ci](https://github.com/amplitude/Amplitude-TypeScript/commit/11c68b2d5e36a9394e0d4dcc7ac4db6be43d64af)
- Remove nx ci on push to main
> ci: revert nx revert

- packages/analytics-core/src/types/frustration-interactions.ts
> fix(plugin-autocapture-browser): remove unused configurations from FrustrationInteractions

- packages/plugin-session-replay-react-native/android/src/main/java/com/amplitude/pluginsessionreplayreactnative/PluginSessionReplayReactNativeModule.kt
Prevent crash on Android 
fix for https://github.com/amplitude/Amplitude-TypeScript/issues/1233
> fix: make session replay optional on android

- packages/analytics-browser/src/config/joined-config.ts
Apply changes on https://github.com/amplitude/Amplitude-TypeScript/pull/1232#discussion_r2254824803
> chore(analytics-browser): more comments for remote config translate

- packages/analytics-browser/src/browser-client.ts
- test-server/autocapture/element-interactions.html
Remove debugger and console.log that somehow got in main
> fix: undo debug statement issue from last PR
