amplitude/Amplitude-TypeScript

packages/analytics-browser/src/typings/browser-snippet.d.ts
packages/analytics-browser/src/utils/snippet-helper.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/utils/snippet-helper.test.ts
packages/analytics-types/src/index.ts
packages/analytics-types/src/proxy.ts

The types declared in `typings/` directory is not getting included in the esm bundle. `typings/` is only use for dev purposes. This is used in generated `d.ts` files for esm build. Th poposed change is to move these type definitions to analytics-types package to guarantee inclusion.
Fixes https://github.com/amplitude/Amplitude-TypeScript/issues/69

fix: move types to analytics-types

---

packages/analytics-browser/rollup.config.js

`yarn build` detects local changes and generates snippet file updates unnecessarily. Restrict generation in CD GITHUB_WORKFLOW only.

build(snippet): run snippet generator in ci env

---

packages/analytics-types/src/plan.ts

Adds `versionId` to plan field in event options

fix: update plan type to include version id

---

packages/analytics-browser/src/storage/cookie.ts
packages/analytics-browser/test/storage/cookies.test.ts

Previously uses options in params, which is not passed. Options in constructor is passed already and better to use.

fix: cookie expires prematurely due to incorrectly used option

---

packages/analytics-browser/package.json
packages/analytics-browser/rollup.config.js

`yarn build` runs twice in deployment, which is fine. the first one is for validation of its current state, the second one is to include the new version (as the upcoming release would be assigned a new version). however, the first occurrence generates a snippet, and we don't want that because lerna will find uncommitted changes. we only want it to run on the second occurrence since we need to include the new version in the final bundle

build: limit snippet regeneration when ready to release

---

.gitignore
packages/analytics-core/src/utils/valid-properties.ts
packages/analytics-core/test/utils/valid-properties.test.ts

fix early return if array element is a valid object

fix: fix early return if array element is a valid object

---

packages/analytics-core/src/config.ts
packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts
packages/analytics-types/src/config.ts

The changes in this PR allow `minIdLength` to be configurable. This can be done by passing `minIdLength` as part of config object on init call.
```ts
amplitude.init(API_KEY, '', {
minIdLength: 1,
});
```
Fixes: https://github.com/amplitude/Amplitude-TypeScript/issues/98

fix: allow min_id_length option in http payload

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-core/src/config.ts
packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/config.test.ts
packages/analytics-types/src/config.ts

SDK does not use `options.serverUrl`. The changes uses `options.serverUrl` to set `config.serverUrl` and be used in destination plugin. Fixes https://github.com/amplitude/Amplitude-TypeScript/issues/103

fix: allow option.serverUrl to be used in destination plugin

---

packages/analytics-browser/package.json
yarn.lock

The change bumps dependency to @amplitude/ua-parser-js@0.7.31.

fix: upgrade to @amplitude/ua-parser-js@0.7.31

---

packages/analytics-browser/src/browser-client.ts

* Update `client.setUserId()` signature to allow unsetting user id by passing `undefined` value
```ts
// ✅ allowed
client.setUserId('user@amplitude.com');
client.setUserId(undefined);
// ❌ not allowed
client.setUserId();
```
Fixes: https://github.com/amplitude/Amplitude-TypeScript/issues/115

fix: allow setting undefined user id via setUserId()

---

packages/analytics-browser/test/browser-client.test.ts
packages/analytics-core/src/core-client.ts
packages/analytics-core/src/utils/event-builder.ts
packages/analytics-core/test/core-client.test.ts
packages/analytics-core/test/utils/event-builder.test.ts

…oupIdentifyEvent
This PR is to remove `userId` and `deviceId` from createIdentifyEvent and createGroupIdentifyEvent. `deviceId` and `userId` can be set through `eventOptions`.

fix: remove userId and deviceId from createIdentifyEvent and createGroupIdentifyEvent

---

packages/analytics-browser/src/attribution/campaign-tracker.ts
packages/analytics-browser/test/attribution/campaign-tracker.test.ts

auto page tracking to be off by default. turning this on by default increases the number of events sent.

fix: change auto page tracking to be opt in

---

packages/analytics-browser/src/utils/snippet-helper.ts
packages/analytics-core/src/utils/return-wrapper.ts
packages/analytics-types/src/amplitude-promise.ts

Fixes https://github.com/amplitude/Amplitude-TypeScript/issues/120
`Awaited` is only available starting TypeScript v4.5. This PR removes the use of `Awaited` type and replaces it with something effectively similar to support older versions of TypeScript.

fix: remove Awaited type to support older versions of typescript

---

packages/analytics-browser/src/config.ts
packages/analytics-browser/src/storage/cookie.ts
packages/analytics-browser/test/config.test.ts
packages/analytics-browser/test/storage/cookies.test.ts

* This allows cookie to be shared across subdomains
* When reading, SDK tries to decode first, otherwise skips decoding and proceeds
* Skipping decoding allows SDK to be backwards compatible
* Does your PR have a breaking change?: Yes. Cookie domain are set to top level domain by default

fix: encode cookies and set top level domain

---

packages/analytics-browser/scripts/templates/browser-snippet.template.js

Added flush api to snippet template. This allows flush api to be called before sdk is loaded, which is very unlikely. Not an urgent fix.

fix: added flush to snippet template

---

packages/analytics-core/src/utils/valid-properties.ts
packages/analytics-core/test/identify.test.ts
packages/analytics-core/test/utils/valid-properties.test.ts

When identify is assigned a `null` value, make it no-op. `null` values of identify is ignored by the API.
Fixes #136

fix: handle error gracefully when identify is set with null

---

packages/analytics-core/src/config.ts
packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts
packages/analytics-node/src/config.ts
packages/analytics-node/test/config.test.ts
packages/analytics-types/src/config.ts

Sets storage provider in core config as optional. Allows SDK to be configured with no storage provider, effectively turning off persisting unsent events. 
Before the fix, the default config for Node SDK uses in memory storage with `saveEvents` is set to `true`. In memory storage for Node doesn't provide any value to Node but only hurts it by taking memory resources.
This fix allows Node SDK to set storage provider to `undefined`, turning of saving unsent events and fixing the issue on memory usage. SDK can still be configured to have a custom storage provider.

fix: allow undefined storage provider

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-core/src/core-client.ts
packages/analytics-core/src/timeline.ts
packages/analytics-core/test/core-client.test.ts
packages/analytics-core/test/helpers/default.ts
packages/analytics-core/test/timeline.test.ts
packages/analytics-node-test/test/index.test.ts
packages/analytics-node/src/node-client.ts
packages/analytics-react-native/src/react-native-client.ts
packages/analytics-types/src/plugin.ts

This PR addresses https://github.com/amplitude/Amplitude-TypeScript/issues/132, by:
- Elevate `timeline` initialization in the `AmplitudeCore` constructor
- When events are `track`ed before `init`, `push` the events to `timeline` without `apply`
- When `init` happens:
- `reset` plugins in `timeline`
- install plugins, this will make sure `init` also resets the plugins like the behavior before
- `flush` all pushed events
To test this rare case, I use the following code to reproduce the issue and test the fix:
```
function App() {
const buttonClickHandler = async () => {
await track(`Button Click ${new Date().toISOString()}`, { name: 'App' })
await init('api-key', 'marvin@amplitude.com')
}
const reinitButtonClickHandler = async () => {
await init('api-key', 'marvin@amplitude.com')
await …
```

fix: missing tracked events before init issue

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-core/src/messages.ts
packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts
packages/analytics-node-test/test/index.test.ts

* Adds error handling for invalid api. The determination is made by the Amplitude http/batch apis. Previously, this is not caught and is retried multiple times (until max retry) which is unnecessary.
* Adds better error messages for requests that failed due to max retry limits.

fix: adds error handling for invalid api

---

packages/analytics-types/src/base-event.ts

Removes uuid event options
* Does your PR have a breaking change?: No 😉

fix: removes deprecated uuid from event options

---

packages/analytics-browser/scripts/templates/browser-snippet.template.js
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/index.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/index.test.ts
packages/analytics-react-native/src/index.ts
packages/analytics-react-native/src/react-native-client.ts
packages/analytics-react-native/test/index.test.ts
packages/analytics-react-native/test/react-native-client.test.ts

This PR adds and exposes the `#reset` method for user to reset `userId` and `deviceId`.

feat: add reset method for resetting userId and deviceId

---

packages/analytics-browser/package.json

Fixes auto gen of snippet instructions. Prior to the fix the snippet instructions are not being generated for a new release.

fix: fixes auto gen of snippet instructions

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-core/src/core-client.ts
packages/analytics-core/src/timeline.ts
packages/analytics-core/test/core-client.test.ts
packages/analytics-react-native/src/react-native-client.ts
packages/analytics-react-native/test/react-native-client.test.ts

Adds a queue to push callable functions that require `this.config` to be called. Once `this.config` is ready, invoke all functions in the queue.

fix: add callable queue when init is pending

---

.github/workflows/ci.yml

Adds node 18.x in build matrix. This verifies if packages are compatible with node 18.x.

build: add build on node 18.x

---

examples/react-native/app/README.md
examples/react-native/expo-app/README.md
packages/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AmplitudeReactNativeModule.kt
packages/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AndroidContextProvider.kt
packages/analytics-react-native/src/plugins/context.ts
packages/analytics-types/src/config.ts

- Update react-native readme to use `yarn` instead of `npm`
- Correct `platform` value
- Add `adid` option, see example:
```
trackingOptions: {
adid: false
}
```
This PR addresses:
- https://github.com/amplitude/Amplitude-TypeScript/issues/177
- https://github.com/amplitude/Amplitude-TypeScript/issues/176
(@BrodaNoel)

fix: correct platform and add adid

---

packages/analytics-core/src/core-client.ts
packages/analytics-core/src/utils/event-builder.ts
packages/analytics-core/test/utils/event-builder.test.ts

Adds `eventOptions` to `setGroup`

fix: add event options to setGroup

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-core/src/core-client.ts
packages/analytics-node/src/node-client.ts
packages/analytics-node/test/node-client.test.ts
packages/analytics-react-native/src/react-native-client.ts
packages/analytics-react-native/test/react-native-client.test.ts

Prevents concurrent init calls for the same amplitude instance
Previously, the following code performs initialization multiple times. This leads to race conditions on 1) reading from storage; 2) resetting timeline state; and 3) installing plugins
```ts
amplitude.init(API_KEY); // performs full init
amplitude.init(API_KEY); // performs full init
amplitude.init(API_KEY); // performs full init
```
With this fix, succeeding `init` calls while one execution is pending exits early.
```ts
amplitude.init(API_KEY); // performs full init
amplitude.init(API_KEY); // returns early
amplitude.init(API_KEY); // returns early
```
However, serial `init` calls retains status quo behavior.

fix: prevent concurrent init calls

---

packages/analytics-browser/src/utils/query-params.ts
packages/analytics-browser/test/utils/query-params.test.ts
packages/analytics-react-native/src/utils/query-params.ts
packages/analytics-react-native/test/utils/query-params.test.ts

Amplitude SDK throws an error when parsing malformed query parameters. The fix is to add try/catch around the parsing logic and returning an empty string if query parameters are malformed

fix: handle parsing malformed query parameters for web attribution

---

packages/analytics-types/src/plugin.ts

Updates plugin interface for setup method to allow implicit return
With this fix, the code example below will be allowed by TS compiler:
```ts
const plugin = (): amplitude.Types.Plugin => {
return {
name: '',
type: amplitude.Types.PluginType.ENRICHMENT,
setup: async (c) => {},
execute: async (e) => {
return e;
},
};
};
```
Previously, setup needed to `return undefined`.

fix: allow implicit undefined return for Plugin.setup interface

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/config.ts
packages/analytics-react-native/src/react-native-client.ts
packages/analytics-types/src/campaign.ts
packages/analytics-types/src/client/web-client.ts
packages/analytics-types/src/config.ts
packages/analytics-types/src/index.ts
packages/plugin-web-attribution-browser/src/plugin-campaign-tracker.ts

Temporarily remove deprecation message for `config.attribution` while plugins are not published yet. Consolidate to single attribution type for browser and react-native.

refactor: clean up attribution config

---

packages/analytics-browser/README.md
packages/analytics-node/README.md
packages/analytics-react-native/README.md

This PR is fixing a mistake in all subpackage Readmes in `groupIdentify` section. The original snippet defined an `event` but used `identify` const in the `groupIdentify` call. This PR unifies the const to be the same. I also took the liberty to change the common naming from `identify` to `identity` as I believe the semantics matter and variables and consts should not be named by what they do (e.g. `identify`), but what they are (e.g. `identity`).

fix: fix groupIdentify code example snippets

---

packages/analytics-browser/package.json
packages/analytics-client-common/package.json
packages/analytics-core/package.json
packages/analytics-node/package.json
packages/analytics-types/package.json
packages/marketing-analytics-browser/package.json
packages/plugin-page-view-tracking-browser/package.json
packages/plugin-web-attribution-browser/package.json

Optimize bundle size by declaring that packages do not have side effects, effectively tree shaking more unused code. 
Info about side effects: https://sgom.es/posts/2020-06-15-everything-you-never-wanted-to-know-about-side-effects/

build: set no side effect to optimize bundle size

---

packages/analytics-browser/package.json
packages/analytics-client-common/package.json
packages/analytics-react-native/package.json
yarn.lock

Fix `@amplitude/analytics-connector` being installed in secondary dependency, not as direct

fix: define correct dependencies for @amplitude/analytics-connector

---

packages/marketing-analytics-browser/src/typings/browser-client.ts
packages/plugin-page-view-tracking-browser/rollup.config.js
packages/plugin-page-view-tracking-browser/src/index.ts
packages/plugin-web-attribution-browser/rollup.config.js
packages/plugin-web-attribution-browser/src/index.ts
packages/plugin-web-attribution-browser/test/web-attribution.test.ts
scripts/build/rollup.config.js

Exports plugins using a plugin's name instead of `amplitude` to prevent naming conflict on window.
For npm installation
```ts
import { pageViewTrackingPlugin } from '@amplitude/plugin-page-view-tracking-browser'; // preferred for npm installation
// or `import { plugin } from '@amplitude/plugin-page-view-tracking-browser';`
```
For script installation
```html
<script src="https://cdn.amplitude.com/libs/plugin-page-view-tracking-browser-0.3.2-beta.1-min.js.gz"></script>
<script>
pageViewTracking.plugin(); // preferred for script installation
// or `pageViewTrackingPlugin.pageViewTrackingPlugin();`
</script>
```

fix: js script export name for marketing analytics plugins

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-client-common/test/cookie-name.test.ts
packages/analytics-node/src/node-client.ts
packages/analytics-node/test/node-client.test.ts
packages/analytics-react-native/src/react-native-client.ts
packages/analytics-react-native/test/react-native-client.test.ts

Fix the edge case that `apiKey` might be null or undefined in the runtime.
Refer to issue: https://github.com/amplitude/Amplitude-TypeScript/issues/238

fix: cover the case when apiKey is missing in the runtime

---

packages/marketing-analytics-browser/README.md
packages/marketing-analytics-browser/src/browser-client.ts
packages/marketing-analytics-browser/src/plugins/context.ts
packages/marketing-analytics-browser/src/typings/browser-client.ts
packages/marketing-analytics-browser/test/browser-client.test.ts
packages/marketing-analytics-browser/test/integration.test.ts
packages/marketing-analytics-browser/test/plugins/context.test.ts
typedoc.json

* [fix: remove unintended options passed to browser SDK](https://github.com/amplitude/Amplitude-TypeScript/commit/6031faf694b3aa974a27e36b904db4a865dc0de7)
* [docs: update docs with new option key](https://github.com/amplitude/Amplitude-TypeScript/commit/f6f75eb3fcb6c27c6bfe0a48168c55a0878c00fc)
* [refactor: convert marketing analytics browser context plugin to fn de…](https://github.com/amplitude/Amplitude-TypeScript/commit/115ee546d9621f6e3d31c2f44aaa8dcb6fca5cd7) 
* [docs: add marketing analytics browser to type doc](https://github.com/amplitude/Amplitude-TypeScript/commit/9d47cd2dfba2db83a85e0bb641e7d8027726c4ae)

fix: remove unintended options passed to browser SDK

---

packages/analytics-client-common/src/attribution/campaign-tracker.ts
packages/analytics-client-common/test/attribution/campaign-tracker.test.ts
packages/plugin-web-attribution-browser/test/plugin-campaign-tracker.test.ts

This PR is to fix not tracking the first direct/organic traffic for web attribution. 
- `getCampaignFromStorage` returns false if no campaign is found
- `isNewCampaign` returns true if previous campaign is undefined

fix: resolve web attribution is not tracking the first direct/organic traffic

---

.github/workflows/ci.yml
examples/plugins/page-view-tracking-enrichment/index.test.ts
examples/plugins/page-view-tracking-enrichment/index.ts
package.json

Adds an example plugin that enriches events with event_type "Page View" by adding more event_properties on top of what `@amplitude/analytics-browser` provides out of the box

docs: adds example for enriching page view events

---

packages/analytics-browser/jest.config.js
packages/analytics-browser/src/index.ts
packages/analytics-browser/src/snippet-index.ts
packages/analytics-browser/src/utils/global-scope.ts
packages/analytics-browser/test/utils/global-scope.test.ts
packages/marketing-analytics-browser/src/snippet-index.ts

Replace `globalThis` (unsupported in some legacy browsers) with `GlobalScope` polyfill (from Amplitude-JavaScript)

fix: globalThis polyfill

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/src/browser-client.ts
packages/analytics-core/src/core-client.ts

Updated AmplitudeBrowser to run queued functions after other initialization completes.
* There is now a separate pluginQueue for `add()` and `remove()` that runs before `this.q`
* Added test for order of calls (identify with attribution, then track)
* fixes #246 

fix: run queued functions after attribution in browser-client.ts

---

examples/plugins/page-view-tracking-enrichment/index.ts
examples/plugins/remove-event-key/index.test.ts
examples/plugins/remove-event-key/index.ts

* adds plugin example for removing keys from event payload
* adds an actual example for removing `event.time` from event payload

docs: adds plugin example for removing keys from event payload

---

packages/analytics-client-common/src/query-params.ts

Adds optional chaining to `window.location`

fix: adds optional chaining to window.location

---

packages/plugin-page-view-tracking-browser/README.md
packages/plugin-web-attribution-browser/README.md

Add comprehensive docs for web attribution and page view tracking plugins
* https://github.com/amplitude/Amplitude-TypeScript/tree/plugin-docs/packages/plugin-web-attribution-browser
* https://github.com/amplitude/Amplitude-TypeScript/tree/plugin-docs/packages/plugin-page-view-tracking-browser

docs: adds README.md for plugins

---

.eslintrc.js
packages/analytics-client-common/src/attribution/campaign-tracker.ts
packages/analytics-client-common/test/attribution/campaign-tracker.test.ts
packages/plugin-web-attribution-browser/src/plugin-campaign-tracker.ts

For attribution plugin, don't reset session or campaign when subdomain changes.

feat: ignore subdomains when comparing newness of campaigns

---

packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts

When calling `amplitude.flush()`, events are flushed immediately but a timeout remains open, created by `amplitude.track()`, which keeps the Node process running. Consider the following situation:
```ts
amplitude.track('Event 1');
// `Event 1` is now queued
// Destination plugin opened a timeout for `config.flushIntervalMillis` or 10000ms (default)
amplitude.track('Event 2');
// `Event 2` is now queued
// Destination plugin detects previously opened timeout, and does not open a new one
await amplitude.flush().promise;
// `Event 1` and `Event 2` are immediately sent
// `track()` promises for `Event 1` and `Event 2` are resolved
// Destination plugin has the timeout still open for the next `config.flushIntervalMillis` or 10000ms (default)
// The timeout keeps the Node process running …
```

fix: clear open timeouts when flush is called

---

packages/analytics-react-native/tsconfig.build.json

Excludes `__mocks__` folder from typescript declarations

fix: exclude '__mocks__' from typescript declarations

---

packages/analytics-react-native/src/config.ts
packages/analytics-react-native/test/config.test.ts
packages/analytics-react-native/test/helpers/default.ts

Set React Native default session timeout to 5 minutes (same for other mobile devices)

fix: set React Native default session timeout to 5 minutes (same for other mobile devices)

---

packages/analytics-client-common/src/session-manager.ts
packages/analytics-client-common/test/session-manager.test.ts
packages/analytics-react-native/src/plugins/context.ts
packages/analytics-react-native/src/react-native-client.ts
packages/analytics-react-native/test/plugins/context.test.ts
packages/analytics-react-native/test/react-native-client.test.ts
packages/analytics-types/src/session-manager.ts

The event id is persisted and read from storage, not each time just start from 0.

feat: persisted event identifiers (React Native)

---

packages/analytics-browser-test/test/in-memory-storage.test.ts

Adds test assertions for all storage scenarios for user session and unsent events:
* Uses default storage
* Uses local storage only
* Uses custom storage (MemoryStorage)

test: add testing for storage scenarios

---

packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts
packages/analytics-react-native/src/react-native-client.ts

- fix: avoid loading types node
https://github.com/amplitude/Amplitude-TypeScript/issues/281, update the `scheduled` seems working for my local.
Add `void` to `appStateChangeHandler` for fixing the building error:
```
@amplitude/analytics-react-native: src/react-native-client.ts:83:5 - error TS2322: Type 'void' is not assignable to type 'NativeEventSubscription | undefined'.
@amplitude/analytics-react-native: 83     this.appStateChangeHandler = AppState.addEventListener('change', this.handleAppStateChange);
@amplitude/analytics-react-native:        ~~~~~~~~~~~~~~~~~~~~~~~~~~
@amplitude/analytics-react-native: Found 1 error.
```

fix: avoid loading types node

---

.github/workflows/ci.yml

- build: add basic automate node type loading check
Use the very basic `grep` to check the import, I didn't find an existing lib/plugin to do this though
Tests
- Pass case: https://github.com/amplitude/Amplitude-TypeScript/actions/runs/3935359357/jobs/6730974668
- Fail case: https://github.com/amplitude/Amplitude-TypeScript/actions/runs/3935384751/jobs/6731021353

build: add basic automate node type loading check

---

packages/analytics-browser-test/package.json
packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/src/config.ts
packages/analytics-browser/src/cookie-migration/index.ts
packages/analytics-browser/test/config.test.ts
packages/analytics-browser/test/cookie-migration/index.test.ts
packages/analytics-react-native/src/config.ts
packages/analytics-react-native/src/cookie-migration/index.ts
packages/analytics-react-native/test/config.test.ts
packages/analytics-react-native/test/cookie-migration/index.test.ts
packages/analytics-types/src/config.ts

1. Adds `config.cookieUpgrade` to retain old SDK cookie and treat as source of truth.
3. This allows parallel instrumentation of legacy and new SDK
4. Best practice is to remove `config.cookieUpgrade` when no longer in parallel instrumentation
5. [BONUS] Integration tests for `@amplitude/analytics-browser` now runs faster and in parallel
**Step 0: Pre migration**
This assumes customer is instrumenting solely using `amplitude-js`
```ts
import amplitude from 'amplitude-js';
amplitude.getInstance().init(...);
```
**Step 1: Parallel instrumentation and partial migration**
This assumes customer is instrumenting using both `amplitude-js` and `@amplitude/analytics-browser`
```ts
import amplitude from 'amplitude-js';
import * as amplitude2 from '@amplitude/analytics-browser'; …
```

feat: allow opt out of deleting legacy sdk cookies

---

packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/test/helpers/mock.ts
packages/analytics-browser/test/plugins/file-download-tracking.test.ts
packages/analytics-types/src/plugin.ts

This set of changes adds a internal plugin for tracking file downloads.
Considering the following `<a>` tag:
```html
<a
id="my-link-id"
href="https://analytics.amplitude.com/files/my-file.pdf"
target="_blank"
rel="noopener noreferrer"
>
Download
</a>
```
The plugin tracks  the following event:
```json
{
"event_type": "file_download",
"event_properties": {
"file_extension": "pdf",
"file_name": "/files/my-file.pdf",
"link_id": "my-link-id",
"link_text": "my-link-text",
"link_url": "https://analytics.amplitude.com/files/my-file.pdf"
}
```
1. The download button must be an anchor tag
1. The download button must contain an href property
1. The href property must point to a file with the following file types
- `pdf`, `xls`, `xlsx`, `doc`, `docx`, `txt`, `rtf`, `csv`, `exe`, `key`, `pps`, `ppt`, …

feat: add file download tracker

---

packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/test/helpers/mock.ts
packages/analytics-browser/test/plugins/form-interaction-tracking.test.ts

This set of changes adds an internal plugin for tracking form interactions.
Considering the following `<form>` tag:
```html
<form id="form-id" name="form-name" action="/hello">
<input type="text" />
<input type="submit" text="Submit" />
</form>
```
The plugin tracks  the following event:
```json
{
"event_type": "form_start",
"event_properties": {
"form_id": "my-form-id",
"form_name": "my-form-name",
"form_destination": "http://localhost/hello",
}
```
```json
{
"event_type": "form_submit",
"event_properties": {
"form_id": "my-form-id",
"form_name": "my-form-name",
"form_destination": "http://localhost/hello",
}
```
1. Form must have `<form>` tag
1. Form must contain `<input type="submit">` to track `form_submit` event
1. Form can contain `<input>` tags as children of `<form>` tag to track …

feat: add form interaction event tracker

---

packages/analytics-browser/src/snippet-index.ts
packages/analytics-types/src/proxy.ts
packages/marketing-analytics-browser/src/snippet-index.ts
scripts/build/rollup.config.js
scripts/templates/browser-snippet.template.js

Adds named instances for google tag manager use case
* If no name is provided, instance is anonymous and not accessible in `amplitude._iq` (See code below)
* Named instances is not available in `npm` installation
* Amplitude GTM template to consume named instances is in progress
* Template will store an instance name
* Template will access instance when executing a command
* Template to pass `$default_instance` name when not provided
```js
// create instance
const instance = createInstance('my-instance-name')
// access instance
amplitude._iq['my-instance-name']
```

feat: add named instances for google tag manager use case

---

packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
packages/plugin-page-view-tracking-browser/src/typings/page-view-tracking.ts
packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts
packages/plugin-web-attribution-browser/src/web-attribution.ts

Creates flexible interface for page view tracking with client instance now optional. This flexibility is only compatible with future (unreleased as of the moment) version of the browser SDK.
```ts
// implicitly using the same instance
const instanceA = createInstance();
instanceA.add(pageViewTrackingPlugin())
```
```ts
// explicitly using the same instance
const instanceA = createInstance();
instanceA.add(pageViewTrackingPlugin(instanceA))
```

fix: remove client parameter requirement for page view tracking plaugin

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/package.json
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/config.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-client-common/src/default-tracking.ts
packages/analytics-client-common/src/index.ts
packages/analytics-client-common/test/default-tracking.test.ts
packages/analytics-types/src/config/browser.ts
packages/analytics-types/src/config/index.ts
packages/analytics-types/src/index.ts
packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts
packages/plugin-web-attribution-browser/src/web-attribution.ts
packages/plugin-web-attribution-browser/test/web-attribution.test.ts

* Replaces browser SDK logic for attribution and page view tracking with first-party plugins
* Old logic for attribution and page view tracking is still supported
* New logic for page view tracking is enabled when using new config
To configure with old logic for page view tracking,
```ts
amplitude.init(API_KEY, USER_ID, {
attribution: {
trackPageViews: true,
},
});
```
To configure with new logic for page view tracking,
```ts
amplitude.init(API_KEY, USER_ID, {
defaultTracking: {
pageViews: true,
},
});
```

feat: retrofit web attribution and page view plugins to browser SDK

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/config.ts
packages/analytics-browser/src/plugins/context.ts
packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/src/plugins/session-handler.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/plugins/context.test.ts
packages/analytics-browser/test/plugins/session-handler.test.ts

Sends session start and session end events when a new session is assigned. Additionally, a new session is assigned when a new user is assigned
```ts
amplitude.init(API_KEY, USER_ID, {
defaultTracking: {
sessions: true,
},
sessionTimeout: 500,
});
// If previous session exists, sends `session_end` event
// Sends `session_start` event
amplitude.track('Event in first session');
setTimeout(() => {
amplitude.track('Event in next session');
// Sends `session_end` event for previous session
// Sends `session_start` event for next session
}, 1000);
setTimeout(() => {
amplitude.setUserId(USER_ID_2); // effectively creates a new session
// Sends `session_end` event for previous user and session
// Sends `session_start` event for next user and session
}, 2000);
```
* Does your PR have a breaking …

feat: add session start/end event tracker

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/config.ts
packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/plugins/file-download-tracking.test.ts
packages/analytics-browser/test/plugins/form-interaction-tracking.test.ts
packages/analytics-client-common/src/default-tracking.ts
packages/analytics-client-common/test/default-tracking.test.ts
packages/analytics-types/src/config/browser.ts
packages/marketing-analytics-browser/src/browser-client.ts
packages/marketing-analytics-browser/src/typings/browser-client.ts
packages/marketing-analytics-browser/test/browser-client.test.ts

Add form interaction and file download plugins
* Transform marketing analytics page view config to default event tracking config
* `form_start` -> `[Amplitude] Form Start`
* `form_submit` -> `[Amplitude] Form Submit`
* `file_download` -> `[Amplitude] File Download`

feat: add form interaction and file download plugins

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/constants.ts
packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/src/plugins/session-handler.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-client-common/src/default-tracking.ts
packages/analytics-client-common/test/default-tracking.test.ts
packages/analytics-types/src/config/browser.ts
packages/analytics-types/src/index.ts
packages/analytics-types/src/page-view-tracking.ts
packages/marketing-analytics-browser/src/browser-client.ts
packages/marketing-analytics-browser/test/browser-client.test.ts
packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
packages/plugin-page-view-tracking-browser/src/typings/page-view-tracking.ts
packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts

* Adds `eventType` config nested under page view tracking config to specify custom page view event type (see code sample)
* Various clean up
```ts
// Browser SDK
amplitude.init(API_KEY, undefined, {
defaultTracking: {
pageViews: {
eventType: 'Page Viewed',
},
},
});
// Marketing Analytics SDK
amplitude.init(API_KEY, undefined, {
pageViewTracking: {
eventType: 'Page Viewed',
},
});
// Page view tracking plugin
pageViewTrackingPlugin(
eventType: 'Page Viewed',
);
```
When `Page View` is default vs when `[Amplitude] Page View` is default
1. The configuration below is new with default events and yields page view events with event type `[Amplitude] Page View`.
```ts
amplitude.init(API_KEY, undefined, {
defaultTracking: {
pageViews: true,
},
});
```
2. The configuration below has been supported …

feat: allow custom page view event type

---

scripts/version/create-snippet.js

When publishing a new version, we update the script loader to include the latest version. The changes prevents this from happening when releasing a beta version. Production versions should update the script loader as usual.

build: prevents script loader update for beta version

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/src/config.ts
packages/analytics-browser/src/cookie-migration/index.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/config.test.ts
packages/analytics-react-native/src/config.ts
packages/analytics-react-native/src/cookie-migration/index.ts
packages/analytics-react-native/src/react-native-client.ts
packages/analytics-react-native/test/config.test.ts
packages/analytics-react-native/test/react-native-client.test.ts
packages/plugin-web-attribution-browser/src/web-attribution.ts

Actual behavior:
SDKs creates cookies despite being configured with `disableCookies: true`.
Expected behavior:
SDKS should not create cookies when configured with `disableCookies: true`.

fix: improper cookie usage

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/config.ts
packages/analytics-browser/src/cookie-migration/index.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/config.test.ts
packages/analytics-browser/test/cookie-migration/index.test.ts

session end and session start shares may share user id or device id on `reset()` or `setUserId()`
```
Session Start
Event 1
Event 2
// User calls amplitude.reset() or amplitude.setUserId() 
Session End // has user id or device id of next session
Session Start
Event 3
Event 4
```
```
Session Start // store user id and event id
Event 1
Event 2
// User calls amplitude.reset() or amplitude.setUserId() 
Session End // use previously stored user id and event id
Session Start // store user id and event id
Event 3
Event 4
```

fix: inconsistent user and device id on session events

---

packages/analytics-browser/src/plugins/file-download-tracking.ts

Suppress error for malformed URL value in href property of an anchor tag. The error is not useful and the malformed URL might be intentional.

fix: improve error handling for file download tracking

---

packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/test/plugins/file-download-tracking.test.ts
packages/analytics-browser/test/plugins/form-interaction-tracking.test.ts

Fixes how event listeners are attached to dynamically appended `<a>` and `<form>` tags
Previously we attach event listeners to dynamically appended nodes like this:
```ts
const observer = new MutationObserver((mutations) => {
mutations.forEach((mutation) => {
mutation.addedNodes.forEach((node) => {
if (node.nodeName === 'A') {
addFileDownloadListener(node as HTMLAnchorElement);
}
});
});
});
```
This method loops through the `mutations` and `addedNodes` and checks if an added node is an anchor/form tag. If so, it adds an event listener to it.
This assumes that all newly mounted tags are included in the `addedNodes` array. However, `addedNodes` only include the the "root" node to represent itself and all its children. That means that if an anchor/form tag is appended [Case 1], it is part …

fix: attach listener to nested nodes

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/constants.ts
packages/analytics-browser/src/plugins/default-page-view-event-enrichment.ts
packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/plugins/default-page-view-event-enrichment.test.ts
packages/analytics-browser/test/plugins/file-download-tracking.test.ts
packages/analytics-browser/test/plugins/form-interaction-tracking.test.ts
packages/analytics-core/src/plugins/destination.ts
packages/marketing-analytics-browser/test/browser-client.test.ts
packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts

Use Amplitude naming convention for default events and properties
For page views:
```diff
{
-  event_type: '[Amplitude] Page View',
+  event_type: '[Amplitude] Page Viewed',
event_properties: {
-      page_domain: '',
-      page_location: '',
-      page_path: '',
-      page_title: '',
-      page_url: '',
+      '[Amplitude] Page Domain': '',
+      '[Amplitude] Page Location': '',
+      '[Amplitude] Page Path': '',
+      '[Amplitude] Page Title': '',
+      '[Amplitude] Page URL': '',
},
},
}
```
For file downloads:
```diff
{
-  event_type: '[Amplitude] File Download',
+  event_type: '[Amplitude] File Downloaded',
event_properties: {
-      file_extension: '',
-      file_name: '',
-      link_id: '',
-      link_text: '',
-      link_url: '',
+      '[Amplitude] File Extension': …
```

fix: event types for default events

---

packages/analytics-browser/test/browser-client.test.ts

added tests unsetting the user id in Browser SDK via `setUserId(undefined)`
https://amplitude.atlassian.net/browse/DXOC-633

chore: added tests unsetting the user id in Browser SDK

---

packages/analytics-types/src/base-event.ts

Add support for [exactOptionalPropertyTypes](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) compiler option.
Only `BaseEvent` type is updated. Maybe all public types should be updated in the same way.

fix: add support for exactOptionalPropertyTypes TypeScript compiler option to BaseEvent

---

.github/workflows/ci.yml

It appears that react-native tests isn't working for Node version 18.16. Pinning Node version for PR build to 18.15 as workaround.

build: update node 18 version on pr build

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-react-native/src/react-native-client.ts

The event bridge connector listener was being added before the plugins were added and setup. This would cause exposures to get sent and fail due to the lack of plugins to add user info to the event.
This change moves adding the event bridge listener to after plugins get added and after queued events are run.

fix: add connector event listener after plugins and queued functions

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-client-common/src/default-tracking.ts
packages/analytics-client-common/test/default-tracking.test.ts
packages/analytics-react-native/test/react-native-client.test.ts
packages/marketing-analytics-browser/test/integration.test.ts

Updates default event tracking configuration to be opt-out instead of opt-in. This assists customers with instrumenting default events with one line init code.
Pattern 1: Opt-in to default event tracking using short config
```diff
- amplitude.init(API_KEY, undefined, {
-   defaultTracking: true,
- });
+ amplitude.init(API_KEY);
```
Pattern 2: Opt-in to default event tracking using verbose config
```diff
- amplitude.init(API_KEY, undefined, {
-   defaultTracking: {
-     attribution: true,
-     fileDownloadTracking: true,
-     formInteractionTracking: true,
-     pageViews: true,
-     sessions: true,
-   },
- });
+ amplitude.init(API_KEY);
```
Pattern 3: Opt-out of default event tracking using short config
```diff
- amplitude.init(API_KEY);
+ amplitude.init(API_KEY, undefined, {
+ …
```

feat: make default event tracking enabled by default

---

packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts

Refer to: https://github.com/amplitude/Amplitude-TypeScript/pull/395
This PR applies the change to Browser SDK V1.

fix: dyanamic page view tracking to run after navigation

---

packages/analytics-browser-test/package.json
packages/analytics-browser/package.json
packages/analytics-client-common/package.json
packages/analytics-core/package.json
packages/analytics-node-test/package.json
packages/analytics-node/package.json
packages/analytics-react-native/package.json
packages/analytics-types/package.json
packages/marketing-analytics-browser/package.json
packages/plugin-page-view-tracking-browser/package.json
packages/plugin-web-attribution-browser/package.json

Cleans up all package versions to be on version 1.x
* New 1.x versions are on beta first
* However, release workflow should graduate these versions
* Does your PR have a breaking change?:  Np

chore: 1.x version

---

scripts/version/create-snippet.js

I recently added dist tags to published versions. The dist tag should label `latest` or `next` (beta) tags appropriately. The guard to prevent generating beta script loaders is not needed, and would not be visible in the npm package's homepage because of dist tags.

build: remove unnecessary beta script guard

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-types/src/client/web-client.ts

Update TS SDK to match the default session handling of JS SDK on `setUserId()`.
* By default, changing userId will NOT start a new session
* Users can call `setSessionId(Date.now())` start a new session if desired
* https://amplitude.atlassian.net/browse/AMP-76240
* Does your PR have a breaking change?:  Technically yes as this changes the current default behavior, however considering this is a bug fix to make work like JS SDK

fix: don't automatically start new session on setUserId

---

packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts
packages/analytics-node/src/transports/http.ts
packages/analytics-node/test/transport/http.test.ts
packages/analytics-types/src/response.ts

* [AMP-77375](https://amplitude.atlassian.net/browse/AMP-77375) FIX: Correctly [resolve `send()` promise on error](https://github.com/amplitude/Amplitude-TypeScript/pull/415/files#r1223588296)
* [AMP-77261](https://amplitude.atlassian.net/browse/AMP-77261) log intermediate response body to logger on retries for Node SDK
[AMP-77375]: https://amplitude.atlassian.net/browse/AMP-77375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AMP-77261]: https://amplitude.atlassian.net/browse/AMP-77261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: log response body from API to logger

---

packages/analytics-browser/src/config.ts

Fixes cookie expiration. It was not setting it property due to incorrect property mapping from options to `CookieStorage` fields

fix: set cookie expiration from options

---

packages/analytics-browser/src/browser-client-factory.ts
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/index.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/helpers/mock.ts
packages/analytics-browser/test/index.test.ts
packages/analytics-react-native/src/react-native-client.ts
packages/analytics-types/src/client/web-client.ts

** Add extendSession() method to Browser SDK to allow customers to extend the current session without sending events / using quota.
```typescript
amplitude.extendSession();
```

feat: added extendSession() method to Browser Client

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/src/plugins/context.ts

* Update `lastEventTime` in on new events to extend session on new events
* Added integration tests
Context: we've always had this but was removed in a recent PR

fix: extend session on new events

---

.github/workflows/publish-v1.yml
.github/workflows/publish-v2.yml
packages/analytics-browser/package.json
packages/analytics-client-common/package.json
packages/analytics-core/package.json
packages/analytics-node/package.json
packages/analytics-react-native/package.json
packages/analytics-types/package.json
packages/plugin-page-view-tracking-browser/package.json
packages/plugin-web-attribution-browser/package.json

- All beta version will have a `beta` [dist-tag](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag)
- All non-beta versions (except for node and react-native, currently private) will have `latest` [dist-tag](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag)
- I configured node and react-native to have `beta` [dist-tag](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag) on any version to protect ourselves for tagging the next published version (likely to be beta) as `latest` once it is no longer private. This config should be changed to `latest` when team is ready.
v1 counterpart: https://github.com/amplitude/Amplitude-TypeScript/pull/418

build: update default dist-tag and pre-dist-tag

---

packages/analytics-browser/package.json
packages/analytics-client-common/package.json
packages/analytics-core/package.json
packages/analytics-node/package.json
packages/analytics-react-native/package.json
packages/analytics-types/package.json
packages/marketing-analytics-browser/package.json
packages/plugin-page-view-tracking-browser/package.json
packages/plugin-web-attribution-browser/package.json

- All non-beta versions (except for node and react-native) will have `v1` [dist-tag](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag)
- I configured node and react-native to have `latest` [dist-tag](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag) on any version because 2.0 is not ready. This config should be changed to `v1` when team for node and react native SDK 2.0.
V2 counterpart: https://github.com/amplitude/Amplitude-TypeScript/pull/417

build: update dist-tag

---

packages/analytics-types/src/client/node-client.ts
packages/analytics-types/src/client/web-client.ts
packages/analytics-types/src/plugin.ts

* Type hints for `amplitude.add()` shows core interface instead of env specific interface both for config and client parameters
**Before:**
_config_
_client_
**After:**
_config_
_client_

fix: types for plugins to be env specific

---

.github/workflows/jira-issue-create-template.yml

* fix issue worflow by removing unnecessary comma

chore: remove extra comma in issue workflow

---

package.json
packages/analytics-client-common/src/storage/cookie.ts
packages/analytics-client-common/test/storage/cookies.test.ts

Fixes #444 - SSR (tested with nextjs) fails when using the cookie storage.

fix: cookie-storage SSR incompatibility

---

packages/analytics-browser/src/config.ts
packages/analytics-browser/src/storage/browser-storage.ts
packages/analytics-browser/src/storage/local-storage.ts
packages/analytics-browser/src/storage/session-storage.ts
packages/analytics-browser/test/config.test.ts
packages/analytics-browser/test/storage/browser-storage.test.ts
packages/analytics-browser/test/storage/local-storage.test.ts
packages/analytics-browser/test/storage/session-storage.test.ts
packages/analytics-types/src/storage.ts

Proposed fix for #434
Adds support for sessionStorage as identityStorage
```ts
amplitude.init(<YOUR_API_KEY>, {
identityStorage: 'sessionStorage',
});
```

feat(storage): add support for sessionStorage as identityStorage

---

packages/plugin-web-attribution-browser/package.json

fix: missing core dependency for web attribution

---

packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/test/plugins/file-download-tracking.test.ts
packages/analytics-browser/test/plugins/form-interaction-tracking.test.ts
packages/analytics-core/src/timeline.ts
packages/analytics-core/test/timeline.test.ts
packages/analytics-types/src/plugin.ts
packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts

* Adds teardown method to plugins interface
* Removes event listeners on plugin teardown
* Fixes #457

fix: allow plugins to teardown to remove listeners

---

.github/workflows/publish-v1.yml
.github/workflows/publish-v2.yml

* aws-actions/configure-aws-credentials from v1 to v2
* According to aws-actions/configure-aws-credentials v2 [changelog](https://github.com/aws-actions/configure-aws-credentials/blob/main/CHANGELOG.md?plain=1#L16-L19), the change only uses node 16 by default which we are already using, so nothing else needs to be changed from our end

ci: update aws-actions/configure-aws-credentials

---

packages/analytics-client-common/src/storage/cookie.ts

Handles concurrent cookie testing
Concurrent cookie testing causes isEnabled to return `false`. This is mainly because the cookie key for the cookie tester is the same and is shared by all instances. Below are the specific steps that lead to the issue:
1. Cookie test 1 starts
2. Cookie test 1 sets AMP_TEST to random value 1
3. Cookie test 2 starts
4. Cookie test 2 sets AMP_TEST to random value 2
5. Cookie test 1 reads AMP_TEST but gets random value 2
6. Cookie test 1 fails
7. Cookie test 2 reads AMP_TEST and gets random value 2
8. Cookie test 1 succeeds
Keep static property of latest random value generated and always test against latest random value

fix: handle concurrent cookie testing

---

packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts

Handles concurrent history.pushState calls
`previousURL` is stale. Consider the following steps that lead to the error
0. current path is `/home`
1. First pushState()  to `/settings`
2. diffs previousURL with newURL
3. First track event (awaited)
4. Second pushState()  to `/settings`
5. diffs previousURL with newURL
* Because step 3 is being awaited on, `previousURL` is still `/home`
6. Second track event (awaited)
7. Updates `previousURL` for first push state
8. Updates `previousURL` for second push state
Update `previousURL` on the same clock tick. Consider the following steps that lead to correct state
0. current path is `/home`
1. First pushState()  to `/settings`
2. diffs previousURL with newURL
3. Updates `previousURL` for first push state
4. First track event (awaited)
5. Second …

fix: handle concurrent history push state calls

---

packages/analytics-types/src/plugin.ts
packages/plugin-session-replay-browser/src/session-replay.ts

Extends plugin interface to allow literal values for `type`. This effectively fixes compatibility issue of `plugin-session-replay-browser` with Browser SDK 2.0.

fix: allow literal values for plugin type

---

packages/plugin-session-replay-browser/package.json
packages/plugin-session-replay-browser/src/helpers.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

This PR updates the timing of when batches of session replay events as the following:
- As soon as the first two events in a session sequence are recorded they are sent to the API
- Then batches are sent every 1000, 2000, 3000....up to 10000 max milliseconds.
- There is also a size limit kept on the event batch of 20MB, if the next event would cause the batch of events to go over 20MB the list will be sent.
This PR also adds a default of masking all inputs to the recorder, this will be updated to be configurable in future revisions.

fix(plugins): update timing of sending batches of session replay events

---

packages/plugin-session-replay-browser/src/session-replay.ts

This PR modifies the timing of initializing the recording of events for the session replay plugin, so that events are always recorded upon plugin initialization.

fix(plugins): change timing of record upon initialization for session replay plugin

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

This PR reworks the initialization logic as well as the IndexDB storage format to better support scenarios where users move between multiple tabs, and to provide resiliency against duplication of batch sequences. The core changes are:
- the initialize function, which in the changes in this PR will be run on both full page load as well as tab refocus
- the format of the IndexDB data, which gives us better insight into the status of the current sequence for a session.
See the following diagram for an explanation of the flow of data of the plugin after these changes:

fix(plugins): Solve timing and duplicated batch issues with session replay plugin

---

packages/plugin-user-agent-enrichment-browser/README.md
packages/plugin-user-agent-enrichment-browser/jest.config.js
packages/plugin-user-agent-enrichment-browser/package.json
packages/plugin-user-agent-enrichment-browser/rollup.config.js
packages/plugin-user-agent-enrichment-browser/src/index.ts
packages/plugin-user-agent-enrichment-browser/src/typings/ua-parser.d.ts
packages/plugin-user-agent-enrichment-browser/src/typings/user-agent-enrichment-plugin.ts
packages/plugin-user-agent-enrichment-browser/src/user-agent-enrichment-plugin.ts
packages/plugin-user-agent-enrichment-browser/test/user-agent.test.ts
packages/plugin-user-agent-enrichment-browser/tsconfig.es5.json
packages/plugin-user-agent-enrichment-browser/tsconfig.esm.json
packages/plugin-user-agent-enrichment-browser/tsconfig.json

This pr is the same as [this PR](https://github.com/amplitude/Amplitude-TypeScript/pull/497), but merge to v1.x branch since we made the decision to merge to which branch is based on the version in the package.json in[ this discussion](https://amplitude.atlassian.net/wiki/spaces/GOV/pages/2148827164/Process+to+maintain+the+typescript+repo.). 
Where to use this plugin:
This plugin will be used to avoid breaking changes for GTM Browser 2.0 template. 
The plugin will be added to [ the GTM SDK Wrapper ](https://github.com/amplitude/amplitude-js-gtm/blob/v3.x/src/amplitude-wrapper.js#L146-L154) by default.
Still investigating on if this can be configured based on customer input, if not, or if there is no quick solution at this time, we are going to force everyone to use this plugin for the …

feat: user agent plugin

---

packages/analytics-browser/generated/amplitude-gtm-snippet.js
packages/analytics-browser/rollup.config.js
packages/analytics-browser/src/gtm-snippet-index.ts
packages/analytics-browser/src/typings/browser-snippet.d.ts
scripts/publish/upload-to-s3.js

Exposing the window.amplitudeGTM for gtm template. 
This is for avoiding the issue caused by multiple window.amplitude compatibility issues which brought up by Unity at the beginning. We have those changes in marketing-analytics-browser before. Duplicate the work here, since we want to upgrade the GTM template to wrap Browser 2.0.
The PRs we have made in marketing-analytics-browser:
[build: fix the issue in marketing analytics browser GTM template by yuhao900914 · Pull Request #365 · amplitude/Amplitude-TypeScript](https://github.com/amplitude/Amplitude-TypeScript/pull/365/files) 
[build: fix the CDN for marketing analytics browser GTM by yuhao900914 · Pull Request #363 · amplitude/Amplitude-TypeScript](https://github.com/amplitude/Amplitude-TypeScript/pull/363/files) 
[build: expose …

build: expose window.amplitudeGTM for gtm template

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

This PR adds logic to stop recording for session replay when document.hasFocus is false. I have noticed that there is some flakiness and timing issues in the window.blur event so the stop recording functionality does not always occur at the right time. This should add extra protection against recording when the tab is not active.
I also updated the max persisted event size to be 10 MB due to changes in the backend.

fix(plugins): stop recording when document.hasFocus is false

---

packages/plugin-session-replay-browser/README.md
packages/plugin-session-replay-browser/src/messages.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

This PR contains three changes:
1. Add default tracking of sessions upon setup of session replay plugin. Its required for the session replay plugin to work to have sessions tracked, this allows us to enforce that requirement
2. Add a configuration option for the sampling rate. This allows users to specify what percent of the sessions they would like to have recorded
3. Abide by the global configuration for opting out of tracking in the session recording - ie don't record if opt out is true

feat(plugins): Adding configuration options to session replay plugin

---

packages/analytics-browser/src/config.ts
packages/analytics-browser/test/config.test.ts

Fix https://github.com/amplitude/Amplitude-TypeScript/issues/492 where ipAddress is set to be false but is still tracked in the event payload.
The original code uses a spread operator (...) to spread out the properties of the options.trackingOptions object into the new trackingOptions object being created. It creates a shallow copy of the options.trackingOptions object. And then ipAddress, language, and platform properties are added to the trackingOptions object setting true which overrides the value in options.trackingOptions
To fix it, check if each property is undefined. If so, default it to be true. Otherwise use the property value of trackingOptions.

fix: get trackingOptions from config

---

packages/plugin-session-replay-browser/README.md
packages/plugin-session-replay-browser/package.json
packages/plugin-session-replay-browser/src/constants.ts
packages/plugin-session-replay-browser/src/helpers.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/plugin-session-replay-browser/test/helpers.test.ts
yarn.lock

This PR adds support for masking non-input elements, as well as unmasking some input elements. See the README update for further details.
I also split out the constants from the top of the session-replay.ts file into their own file, and added a helper file for smaller functions (like the maskInputFn added here)

feat(plugins): add masking controls to session replay and reorganize constants and helper fns

---

packages/plugin-session-replay-browser/README.md
packages/plugin-session-replay-browser/src/constants.ts
packages/plugin-session-replay-browser/src/session-replay.ts

Adds the ability to block elements in the recording by using the class `amp-block` in the implementer's code.

feat(plugins): add option to block elements based on amp-block class in session replay

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

This fixes some confusing behavior observed when users open a new tab but do not have it in focus. We only want to record the tab that is in focus at any time.

fix(plugins): prevent any activity from occurring in session replay plugin if document does not have focus

---

packages/plugin-session-replay-browser/src/constants.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

This PR includes two changes:
1. Correctly fetch shouldRecord from the store - previously we were only using the value if it was set to false, we need to know if a previous decision has been made that the session should be recorded as well.
2. Clean up the IDB store upon sending events, getting rid of session data that is older than 3 days. Average session durations are usually in the minutes-range, so a buffer of days should ensure that we are not evicting still relevant data for most sessions. But this cleanup will help ensure that the IDB storage doesn't unnecessarily bloat for customer's sites, which could potentially cause issues if they (or other services they use) also want to make use of IDB. 

fix(plugins): correctly fetch shouldRecord from store and clean up old store entries

---

packages/plugin-session-replay-browser/src/constants.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

Uses the right server endpoint based on the config from the SDK. 

feat(session replay eu): route traffic to eu based on config

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

This PR resolves the issue described in https://amplitude.atlassian.net/browse/AMP-81323, where some events were being dropped when a tab was opened in a background tab.

fix(plugins): fix edge case when opening tab in background

---

packages/plugin-session-replay-browser/src/constants.ts
packages/plugin-session-replay-browser/src/helpers.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/plugin-session-replay-browser/test/helpers.test.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

This PR reduces our dependence on IndexedDB (and the timing issues related to using it) by using a hash function to deterministically calculate whether a session id is included in the sample or not. @jackson-amplitude and I ran a series of automated tests using 10,000 generated session ids to ensure that this calculation would allow for accurate sampling.

fix(plugins): use hash to calculate is session is included in sample

---

packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

Add a test for robustness of sending events that are not recording for current session and current sequence

test(plugins): add test for sending events that are not current sessions current sequence

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

This PR adds a teardown method to the session replay plugin, which is called when either `amplitude.remove()` or `amplitude.init()` is called for a subsequent time. This method removes event listeners from the window, stops recording, and flushes the event queue, sending all remaining events.

feat(plugins): add teardown functionality to session replay plugin

---

packages/plugin-session-replay-browser/package.json

Add an override so that Lerna doesn't autocorrect packages for session replay plugin

fix(plugin): override lerna autocorrect packages

---

packages/plugin-session-replay-browser/package.json

Add analytics-core as dependency to session replay plugin

fix(plugins): add analytics-core as dependency

---

packages/plugin-ga-events-forwarder-browser/src/constants.ts
packages/plugin-ga-events-forwarder-browser/src/ga-events-forwarder.ts
packages/plugin-ga-events-forwarder-browser/src/helpers.ts

* Include `analytics.google.com` in tracked endpoints
* Decode payload when parsing

fix: add allowed hostname for ga events forwarder

---

packages/analytics-react-native/README.md
packages/analytics-react-native/android/build.gradle
packages/analytics-react-native/android/gradle.properties
packages/analytics-react-native/android/src/main/AndroidManifestNew.xml

Updated Android files to match files produced by [create-react-native-library tool](https://www.npmjs.com/package/create-react-native-library). It removes a few deprecation warnings.
It looks like iOS part doesn't contain significant changes.
Tested RN versions: 0.72.3, 0.71.12, 0.70.13

feat: update Android files to support recent React Native versions

---

packages/plugin-session-replay-browser/package.json
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts
yarn.lock

Capture errors from rrweb and swallow them, logging to the console instead. Also bumped rrweb version to the latest

fix(plugins): add error handling to session replay and bump rrweb version

---

packages/plugin-ga-events-forwarder-browser/src/ga-events-forwarder.ts
packages/plugin-ga-events-forwarder-browser/src/helpers.ts

Enforce type consistency between proxied function and proxy function

fix: add return type of proxied function

---

packages/analytics-browser/src/config.ts
packages/analytics-browser/src/storage/local-storage.ts
packages/analytics-browser/test/config.test.ts
packages/analytics-browser/test/storage/local-storage.test.ts

To fix https://amplitude.atlassian.net/browse/AMP-82144
Equivalent for v2.0 https://github.com/amplitude/Amplitude-TypeScript/pull/528
Limit local storage size to 1000 events if it stores an array of events

fix: limit local storage size

---

packages/plugin-page-view-tracking-browser/package.json
packages/plugin-web-attribution-browser/package.json

Removed circular dependencies from `devDependencies`

fix: remove circular dependencies to unblock release

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-client-common/package.json
packages/analytics-client-common/src/analytics-connector.ts
packages/analytics-client-common/src/index.ts
packages/analytics-client-common/test/analytics-connector.test.ts
yarn.lock

This PR updates the v1 version of browser sdk to allow amplitude.setOptOut to set the opt out config in the analytics connector. The session replay SDK will need to be able to fetch the most up to date value for opt out at run time, which this allows. 

feat(browser): set optOut config in analytics connector

---

packages/analytics-core/src/core-client.ts
packages/analytics-core/src/timeline.ts
packages/analytics-core/test/core-client.test.ts

We have some use cases where customers will need to remove the 'amplitude' destination plugin, for example if they need to use a shell Browser SDK for session management only. When testing these use cases, I noticed that there is an implicit expectation that at least one destination plugin is on the instance. This PR removes that expectation, logging a warning to the console if an event is tracked without any destination plugins. 

fix(core): allow no destination plugins on instance

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-client-common/src/index.ts
packages/analytics-client-common/src/session.ts
packages/analytics-client-common/test/session.test.ts
packages/plugin-web-attribution-browser/src/helpers.ts
packages/plugin-web-attribution-browser/src/web-attribution.ts
packages/plugin-web-attribution-browser/test/helpers.test.ts

fix: fix web attribution behavior for no referrer in the same session

---

packages/plugin-ga-events-forwarder-browser/src/constants.ts
packages/plugin-ga-events-forwarder-browser/src/ga-events-forwarder.ts
packages/plugin-ga-events-forwarder-browser/src/helpers.ts
packages/plugin-ga-events-forwarder-browser/test/ga-events-forwarder.test.ts
packages/plugin-ga-events-forwarder-browser/test/helpers.test.ts

* Set Amplitude SDK user ID when a new Google Analytics SDK user ID is processed
* Ignore Google Analytics SDK device ID completely

fix: set user id and device id from ga events

---

packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/test/plugins/form-interaction-tracking.test.ts

ignore non-string `form.name` values for form interaction tracking
We've seen in a customer's production site where `form.name` can return a value of type Element. This yields an error when this value is included in the event payload as it eventually gets stringified and the element has circular references. The following error is thrown.
```
logger.ts:38 Amplitude Logger [Error]: Converting circular structure to JSON
--> starting at object with constructor 'HTMLInputElement'
|     property 'xxx' -> object with constructor 'x'
--- property 'stateNode' closes the circle
```

fix: ignore non-string form.name values for form interaction tracking

---

packages/plugin-auto-tracking-browser/CHANGELOG.md
packages/plugin-auto-tracking-browser/README.md
packages/plugin-auto-tracking-browser/jest.config.js
packages/plugin-auto-tracking-browser/package.json
packages/plugin-auto-tracking-browser/rollup.config.js
packages/plugin-auto-tracking-browser/src/auto-tracking-plugin.ts
packages/plugin-auto-tracking-browser/src/constants.ts
packages/plugin-auto-tracking-browser/src/helpers.ts
packages/plugin-auto-tracking-browser/src/index.ts
packages/plugin-auto-tracking-browser/test/auto-tracking-plugin.test.ts
packages/plugin-auto-tracking-browser/test/helpers.test.ts
packages/plugin-auto-tracking-browser/tsconfig.es5.json
packages/plugin-auto-tracking-browser/tsconfig.esm.json
packages/plugin-auto-tracking-browser/tsconfig.json
packages/plugin-ga-events-forwarder-browser/test/ga-events-forwarder.test.ts

Extract the auto-tracking logic from https://github.com/amplitude/Amplitude-TypeScript/pull/529 to a new package.
- feat: add auto-tracking plugin
The plugin accepts 1 optional parameter, which is an `Object` to configure the allowed tracking options.
```typescript
const plugin = autoTrackingPlugin({
cssSelectorAllowlist: ['.amp-auto-tracking', '[amp-auto-tracking]'],
tagAllowlist: ['button', 'a'],
});
```
Examples:
- The above `cssSelectorAllowlist` will only allow tracking elements like:
- `<button amp-auto-tracking>Click</button>`
- `<a class="amp-auto-tracking">Link</a>`
- The above `tagAllowlist` will only allow `button` and `a` tags to be tracked.
Note `ingestionMetadata` is for internal use only, you don't need to provide it.
|Name|Type|Default|Description|
|-|-|-|-| …

feat: add auto-tracking plugin

---

packages/plugin-auto-tracking-browser/README.md
packages/plugin-auto-tracking-browser/src/auto-tracking-plugin.ts
packages/plugin-auto-tracking-browser/src/constants.ts
packages/plugin-auto-tracking-browser/test/auto-tracking-plugin.test.ts

- refactor(plugin-auto-tracking-browser): remove ingestion metadata option
We can use the `ingestionMetadata` configured in the global config.

refactor(plugin-auto-tracking-browser): remove ingestion metadata option

---

packages/analytics-react-native/src/plugins/context.ts

Config values should take precedence over nativemodule in Context plugin.
I can't find other issues except `appVersion`.
> [bgiori](https://github.com/bgiori) [on Jul 27](https://github.com/amplitude/Amplitude-TypeScript/pull/507#discussion_r1275464705)
> FWIW analytics-browser does the same, we use uaresult values not the config values
I can't find the config values related to uaresult. I believe, uaresult values are specific for a user/device and shouldn't be configured globally.

fix: config values should take precedence over nativemodule in Context plugin

---

packages/session-replay-browser/README.md
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Expose a getSessionReplayProperties method, that does the same as the existing getSessionRecordingProperties. For now we are doing this in a backwards compatible manner, and maintaining getSessionRecordingProperties. We will remove getSessionRecordingProperties in a future breaking changes version.

feat(session replay): add getSessionReplayProperties method

---

packages/session-replay-browser/src/index.ts
packages/session-replay-browser/src/session-replay-factory.ts
packages/session-replay-browser/src/typings/session-replay.ts

In my last PR, I forgot to actually expose the getSessionReplayProperties method

fix(session replay): expose getSessionReplayProperties externally

---

packages/plugin-web-attribution-browser/src/helpers.ts
packages/plugin-web-attribution-browser/test/helpers.test.ts

Fix the issue at [Jira](https://amplitude.atlassian.net/browse/AMP-84339?filter=18277), based on the comment 
> Direct = No external referral, no UTMs, no click-ids, and no other customer-identified marketing campaign url params.
> 
> Therefore we should always capture UTMs even if there is no referral info.  Stripping referral info is common with redirects.

fix: fix attribution to capture UTMs even if there is no referral info

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

We want to update all places we mention 'record' to mention 'replay' instead, so we will eventually deprecate `getSessionRecordingProperties`

fix(session replay plugin): update plugin to use the sessionReplayProperties fn

---

packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Fix issue with session replay opt out not applying immediately. This change will immediately stop recordings and opt the user out of session replay. 
Also fixed issue where identityStoreOptOut would default to this.config.optOut when identityStoreOptOut was false. This misses the case where optOut should be false and not defaulted to this.config.optOut which could be the previous optOut state.

fix(session replay): opt out should take effect immediately

---

packages/plugin-global-user-properties/src/global-user-properties.ts
packages/plugin-global-user-properties/src/typings/global-user-properties.ts
packages/plugin-global-user-properties/test/global-user-properties.test.ts

Adds a property transform option to the global user properties plugin. My own use case is to be able to filter the properties down to a list of allowed ones, and i thought this would be the most flexible way to accomplish that.

feat: add transform option to global user property

---

packages/analytics-core/src/core-client.ts
packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts
packages/plugin-ga-events-forwarder-browser/src/ga-events-forwarder.ts

Logs caught errors before stringifying
* Allows complete error trace to be logged using the logger provider

fix: log error trace in catch blocks

---

packages/plugin-default-event-tracking-advanced-browser/README.md
packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
packages/plugin-default-event-tracking-advanced-browser/src/helpers.ts
packages/plugin-default-event-tracking-advanced-browser/src/index.ts
packages/plugin-default-event-tracking-advanced-browser/test/default-event-tracking-advanced.test.ts
packages/plugin-default-event-tracking-advanced-browser/test/helpers.test.ts

feat: make auto-tracking solely use css selector allowlist
This change make `cssSelectorAllowlist` the single source of truth for the selector configuration, which allows us to track clicking of elements not in the default tag list: `['a', 'button', 'input', 'select', 'textarea', 'label']`. Reason is some button might be built with `div`, not with the `button`.
Add `event.stopPropagation();` specifically, as nested element clicking may cause unexpected events flood.

feat: make auto-tracking solely use css selector allowlist

---

packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts

- fix: remove event stopPropagation
I was under the wrong impression that `stopPropagation` won't affect the parent clicking event when there are other `onclick` attached, this fix removes the `stopPropagation`.

fix: remove event stopPropagation

---

packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts

- fix: add filter back to handle current node

fix: add filter back to handle current node

---

packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
packages/plugin-default-event-tracking-advanced-browser/test/default-event-tracking-advanced.test.ts

- fix: handle text node throw error issue
This is an edge case, React Components debugging tool is injecting nodes onto the page, including Text Node. The text node doesn't have tag and matches method, which will throw error on the page.
Previously, as we have the tag list filter, so this issue was not triggered.

fix: handle text node throw error issue

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/src/config.ts
packages/session-replay-browser/src/constants.ts
packages/session-replay-browser/src/helpers.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/helpers.test.ts
packages/session-replay-browser/test/session-replay.test.ts

Adding in generic session replay ID to initialization and session turnover:
```
// Your existing initialization logic with Browser SDK
amplitude.init(API_KEY);
// Create and Install Session Replay Plugin
const sessionReplayTracking = sessionReplayPlugin();
amplitude.add(sessionReplayTracking);
amplitude.getSessionReplay
```
```
// Can include generic sessionReplayId 
await sessionReplay.init(AMPLITUDE_API_KEY, {
deviceId: <string>,
sessionId: <number>,
// sessionReplayId: <string>,
optOut: <boolean>,
sampleRate: <number>
}).promise;
// This would generate from sessionId/deviceId
sessionReplay.setSessionId({sessionId:123});
// This would use passed in generic
//sessionReplay.setSessionId({sessionReplayId:"123/456"});
// This will include [NEW_SESSION_REPLAY_PROPERTY]: sessionReplayId / …
```

feat: add session replay ID generic identifier to init/turnover

---

packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
packages/plugin-default-event-tracking-advanced-browser/src/helpers.ts
packages/plugin-default-event-tracking-advanced-browser/test/default-event-tracking-advanced.test.ts
packages/plugin-default-event-tracking-advanced-browser/test/helpers.test.ts

- fix: skip parent element event when it is not target
- feat: limit to only the innermost allowed element
In the following case, the plugin will fire 3 events, as the clicking event is propagated to the parent (and parent's parent):
```html
<div data-testid="details">
<div data-testid="container">
<button data-testid="button">Click Me</button>
</div>
</div>
// configure
cssSelectorAllowlist: ["[data-testid]"]
```
To avoid this, we can check the `event?.target != event?.currentTarget`. However, this will potential introduce another issue:
```html
<button>
<span>Click Me</span>
</button>
// configure
cssSelectorAllowlist: ["button"]
```
When clicking on `span`, it won't track as `span` is not in the allow list, and due to the change we check the target, it will not track the event for …

fix: skip parent element event when it is not target

---

packages/session-replay-browser/src/constants.ts
packages/session-replay-browser/src/index.ts
packages/session-replay-browser/src/session-replay-factory.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/index.test.ts
packages/session-replay-browser/test/session-replay.test.ts

feat(session replay): remove recording terms

---

.github/workflows/feature-branch-prerelease.yml
.github/workflows/publish-v1.yml
.github/workflows/publish-v2.yml
lerna.json

https://amplitude.atlassian.net/browse/AMP-88911
Add a Github actions workflow to prerelease from a feature branch
- Can run a dry run without pushing to remote repo 
- Must input the branch name. It is then used when checkout and used as the preid
Example:
If current version is `@amplitude/analytics-browser: 2.2.1`, the feature branch is `feat-sdk-diagnostics`, it will prerelease to ` 2.3.0-featsdkdiagnostics.0`

ci: prerelease feature branch

---

packages/analytics-client-common/src/attribution/campaign-tracker.ts
packages/analytics-core/README.md
packages/analytics-types/README.md

This PR is to set the npm latest tag to the correct versions for 
- @amplitude/analytics-client-common
- @amplitude/analytics-core
- @amplitude/analytics-types

fix: npm latest tags

---

packages/plugin-default-event-tracking-advanced-browser/src/constants.ts
packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
packages/plugin-default-event-tracking-advanced-browser/src/helpers.ts
packages/plugin-default-event-tracking-advanced-browser/src/libs/messenger.ts
packages/plugin-default-event-tracking-advanced-browser/test/default-event-tracking-advanced.test.ts
packages/plugin-default-event-tracking-advanced-browser/test/helpers.test.ts

feat: integrate with selector
- Add the lazy loading of visual tagging selector UI when enabled
- Implement a messenger to sync to the opener, treating the selector UI as a tool to only get the selected element

feat: integrate with selector

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-client-common/src/attribution/campaign-helper.ts
packages/analytics-client-common/src/index.ts
packages/analytics-client-common/src/session.ts
packages/analytics-client-common/test/attribution/campaign-helper.test.ts
packages/analytics-client-common/test/session.test.ts
packages/analytics-core/src/timeline.ts
packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts
packages/plugin-web-attribution-browser/src/typings/web-attribution.ts
packages/plugin-web-attribution-browser/src/web-attribution.ts
packages/plugin-web-attribution-browser/test/web-attribution.test.ts

[AMP-85242](https://amplitude.atlassian.net/browse/AMP-85242)
* update attribution plugin to apply utm params to the `session_start` event
[AMP-85242]: https://amplitude.atlassian.net/browse/AMP-85242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update attribution plugin to apply utm params to the `session_start` event

---

packages/plugin-session-replay-browser/README.md
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/src/index.ts
packages/session-replay-browser/src/session-replay-factory.ts
packages/session-replay-browser/src/typings/session-replay.ts

Alternative to #628 
* [AMP-89820](https://amplitude.atlassian.net/browse/AMP-89820) - update Browser SR plugin to allow explicit flushing
* [fix: binding of sessionReplay shutdown method](https://github.com/amplitude/Amplitude-TypeScript/pull/633/commits/65812f376aa5c0129eeb9759a0dd3297166271d5)
For Mobile session replay I am using the Browser SR plugin to convert the mobile layouts to `rrweb` events. This works well but I need a way to explicitly flush the SR events, which is not currently possible as the Browser SR plugin doesn't expose a flush method.
This PR converts the session replay plugin to a DestinationPlugin to add `flush()`. Since we also need to do enrichment the new DestinationPlugin adds a EnrichmentPlugin in `setup()`. This allows the change to be (mostly) backwards …

feat: convert session replay plugin to be a destination plugin with flush support

---

packages/analytics-browser/src/plugins/form-interaction-tracking.ts

Ignore non-string form.id values for form interaction tracking. [AMP-89625](https://amplitude.atlassian.net/browse/)
If the `form.id` is not string, event property value is flatten and appends to property name "Form Id". For example:
```
"event_properties":{
"Form ID": {A: B}
}
```
The backend will extract property name to be `Form ID.A` and property value to be `B`
[AMP-89625]: https://amplitude.atlassian.net/browse/AMP-89625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: ignore non-string form.id for form interaction tracking

---

packages/analytics-types/src/server-zone.ts
packages/session-replay-browser/src/config.ts
packages/session-replay-browser/src/constants.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

add staging endpoint capabilities for SR sdk
Ticket: https://amplitude.atlassian.net/browse/AMP-89623

chore(sr): amp-89623 Add staging endpoint capabilities for SDK

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts

* Plugins were not receiving the config.sessionId
* Made it so browser config is finalized before calling plugin.setup

fix: Amp 90349 plugins not receiving session id

---

packages/plugin-default-event-tracking-advanced-browser/src/constants.ts
packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
packages/plugin-default-event-tracking-advanced-browser/src/helpers.ts
packages/plugin-default-event-tracking-advanced-browser/src/index.ts
packages/plugin-default-event-tracking-advanced-browser/src/libs/messenger.ts
packages/plugin-default-event-tracking-advanced-browser/test/default-event-tracking-advanced.test.ts
packages/plugin-default-event-tracking-advanced-browser/test/helpers.test.ts
packages/plugin-default-event-tracking-advanced-browser/test/utils.ts

feat(deta): use same method for element properties
Related to: https://github.com/amplitude/visual-tagging-selector/pull/7.
Expose the `origin` to be configurable so it can be used for testing in local/staging envs like:
```js
amplitude.add(amplitudeDefaultEventTrackingAdvancedPlugin.defaultEventTrackingAdvancedPlugin({
visualTaggingOptions: {
enabled: true,
messenger: new amplitudeDefaultEventTrackingAdvancedPlugin.WindowMessenger({origin: 'http://localhost:3007'}),
},
}));
```

feat(deta): use same method for element properties

---

packages/plugin-default-event-tracking-advanced-browser/src/constants.ts

Bump version to 0.1.0, related to https://github.com/amplitude/visual-tagging-selector/pull/9.

build: bump visual tagger version to 0.1.0

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/src/config.ts
packages/session-replay-browser/src/constants.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Adds an optional configuration that turns on debug mode. 
When debug mode is turned on, additional debug information is captured in the `[Amplitude] Session Replay Debug` event property. Currently it only contains the hash of the app, can capture additional information such as errors in the future.

feat: session seplay debug mode

---

packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Fixing issue with sample rate and adding additional test coverage regarding default of 0. 

feat(session replay): stricter check for no sample rate

---

packages/plugin-default-event-tracking-advanced-browser/package.json
packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
packages/plugin-default-event-tracking-advanced-browser/src/helpers.ts
packages/plugin-default-event-tracking-advanced-browser/test/default-event-tracking-advanced.test.ts
packages/plugin-default-event-tracking-advanced-browser/test/helpers.test.ts

fix(deta plugin): type and error issues
- adjust the `@amplitude/analytics-types` version based on user installed version, so it won't display the type error like:
```
Argument of type 'BrowserEnrichmentPlugin' is not assignable to parameter of type 'Plugin<BrowserClient, BrowserConfig>'.
```
- in the case that `<html>` document doesn't have the `<body>` yet, it runs the scripts (sync) inside `<head>`, we mount the mutation observer later after page load finishes
- in some cases, `finder` might throw error, e.g., if an element is removed from the document tree, we fallback to use a simple strategy to get the selector

fix(deta plugin): type and error issues

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts

Workaround to https://github.com/amplitude/Amplitude-TypeScript/issues/500 where `TypeError: globalScope.addEventListener is not a function` happens in Next.js application. This PR will prevent page view tracking plugin from installing based on config when `config.defaultTracking = false` or `config.defaultTracking.pageViews = false`

fix: should not install page view tracking plugin based on config

---

packages/plugin-default-event-tracking-advanced-browser/src/constants.ts

build: bump visual selector version to 0.2.1
Related to: https://github.com/amplitude/visual-tagging-selector/pull/14

build: bump visual selector version to 0.2.1

---

packages/plugin-session-replay-browser/package.json
packages/plugin-session-replay-browser/src/constants.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/src/index.ts
packages/session-replay-browser/src/session-replay-factory.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

This PR improves the general of the SR plugin by: 
1. By synchronizing Session Id between Browser SDK and SR plugin on each event. In the process also getting rid of the need to require start session event. 
2. Updates getSessionReplayProperties to ignore the focus state handler to enhance tagging of events. 

feat(session replay): improve initialization and event tagging

---

packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts

The issue was:
[In the setup](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-core/src/plugins/destination.ts#L62), we get all events from the storage, put them into a local storage and clean the cookies storage. 
However, some customers, as noted in [Jira 1](https://amplitude.atlassian.net/browse/AMP-93344) and [Jira 2](https://amplitude.atlassian.net/browse/AMP-93297), are missing session start/session end events when redirecting to another page. After investigation, we found that the event_id has been incremented, but the server did not receive this event. We think the original logic might have caused the events to be dropped after we cleared the storage.
Current logic:
While adding an event to the queue, we saved the event to the storage. In line #106. …

fix: fix event flush process

---

packages/plugin-session-replay-browser/README.md
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Fixes the event tagging issues from last PR, mainly: 
1. we should not tag events that have mismatching session id with the current session (these are likely late/out of session events) 
2. only tag events when we are in focus/recording. The focus handler is only ignored when in debug mode, this can be used for people who are developing with the console open (which makes the page out of focus). 

fix(session replay): fix event tagging 

---

packages/plugin-default-event-tracking-advanced-browser/src/constants.ts
packages/plugin-default-event-tracking-advanced-browser/src/default-event-tracking-advanced-plugin.ts
packages/plugin-default-event-tracking-advanced-browser/src/libs/messenger.ts
packages/plugin-default-event-tracking-advanced-browser/src/typings/default-event-tracking-advanced.ts

Related to https://github.com/amplitude/visual-tagging-selector/pull/15.
This PR:
- get `actionType` from the message
- pass the `isElementSelectable` to visual tagging selector

feat: pass iselementselectable to visual selector

---

packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts

This reverts commit 043987f1382172fa5b700220b0b39f0e655514e4.
https://amplitude.atlassian.net/browse/AMP-96244
`analytics-browser v2.5.3` doesn't drop bad events. This PR reverts https://github.com/amplitude/Amplitude-TypeScript/pull/670.

fix: stop accumulating bad events

---

packages/session-replay-browser/README.md
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Update setSessionId to allow for updating the device id at the same time. Useful for consumers who want to use device id to track users, such as moving between an anonymous part of the site to a logged in part of the site.

feat(session replay): add argument to setSessionId to allow for updating deviceId

---

packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/test/plugins/file-download-tracking.test.ts
packages/analytics-browser/test/plugins/form-interaction-tracking.test.ts

When the amplitude script tag is added before the body tag, the file download listeners and form listeners weren't able to attach themselves to the body of the page (since the body was still not loaded). Fixing this by setting up the listener after the window is loaded

fix: register download and form listeners after window is loaded

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts

This PR fixes the bug described at https://amplitude.atlassian.net/browse/AMP-94551 where `SessionReplayPlugin` throws an "session Id and device Id not found" error because `plugin.setup()` is executed before `client.config` is set. 
This PR is made in the consideration of not breaking the fix of https://github.com/amplitude/Amplitude-TypeScript/pull/426, specifically the session Id of the session end event should be the one fetched from storage rather than `options.sessionId`. That being said, we cannot simply solve this by 
- Change this [line](https://github.com/amplitude/Amplitude-TypeScript/blob/d9e6fc678e6d364f209f0a942ebd57143966992e/packages/analytics-browser/src/config.ts#L226) in `useBrowserConfig()` to be `const sessionId = options.sessionId ?? previousCookies?.sessionId ?? …

fix: have session and device IDs ready before plugin setup

---

packages/session-replay-browser/src/typings/session-replay.ts

Expose an updated interface to setSessionId via updated typing. This optional argument was added in #690  

fix(session replay): expose deviceid on setSessionId type

---

packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/track-destination.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/test/track-destination.test.ts

In preparation for adding logic to support targeting, I am simplifying the core SessionReplay class. This class has grown large already as we've added functionality, and will continue to grow larger. This PR separates out all logic related to sending the sequence of events to the API into a new class, TrackDestination. There are no functional changes in this PR.

refactor(session replay): split out destination logic into separate class

---

packages/session-replay-browser/src/session-idb-store.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/session-idb-store.test.ts
packages/session-replay-browser/test/session-replay.test.ts

Reimplement #704 , with a fix for this binding on `cleanUpSessionEventsStore`

refactor(session replay): move events storage logic in idb to separate class

---

packages/session-replay-browser/src/config.ts
packages/session-replay-browser/src/identifiers.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

This PR in the Session Replay SDK creates a distinction between config that is set once upon initialization, and identifiers that can be updated throughout the SDK lifecycle (session id, device id, and session replay id). This helps add clarity to which aspects of the configuration are changed in the lifecycle, and which we can expect to remain static.

refactor(session replay): separate out session identifiers from the rest of config

---

packages/targeting/CHANGELOG.md
packages/targeting/README.md
packages/targeting/jest.config.js
packages/targeting/package.json
packages/targeting/rollup.config.js
packages/targeting/src/index.ts
packages/targeting/src/targeting.ts
packages/targeting/src/typings/targeting.ts
packages/targeting/test/flag-config-data.ts
packages/targeting/test/targeting.test.ts
packages/targeting/tsconfig.es5.json
packages/targeting/tsconfig.esm.json
packages/targeting/tsconfig.json
yarn.lock

This PR introduces the base of a new package called `targeting`, that will provide a wrapper around the experiment-core Evaluation Engine. This package will manage the storage of some event and user property data, but ultimately be a concise interface between Session Replay and future action based products to the Evaluation Engine.

feat(targeting): introduce new package for targeting

---

packages/session-replay-browser/src/events-manager.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/track-destination.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/events-manager.test.ts
packages/session-replay-browser/test/integration.test.ts
packages/session-replay-browser/test/session-replay.test.ts

This PR introduces an SessionReplayEventsManager class to the Session Replay SDK architecture. This class is responsible for all handling of rrweb events - both storage and at what cadence to send them to the backend. This refactor will make it much easier to introduce targeting, which will modify the timing of both storage and backend submissions.
There are two commits in this PR, that may be easier to review independently:
[The first commit introduces the class](https://github.com/amplitude/Amplitude-TypeScript/pull/708/commits/bd81ad033416c33d146d1c59c5bcdfcd9244bf5e), changing as little as possible in the tests to show that there are no regressions based on this refactor
[The second commit reworks the tests](https://github.com/amplitude/Amplitude-TypeScript/pull/708/commits/026adf5c3b2 …

refactor(session replay): create events manager class

---

packages/session-replay-browser/package.json
packages/session-replay-browser/src/remote-config-fetch.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/flag-config-data.ts
packages/session-replay-browser/test/remote-config-fetch.test.ts
packages/targeting/src/index.ts
packages/targeting/src/typings/targeting.ts

Add a RemoteConfigFetch class to the Session Replay SDK. This will allow us to fetch targeting config in the initialization of the SR SDK

feat(session replay): introduce remote config fetch class

---

packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Safety check in case users call init multiple times

fix(session replay): remove event listeners on init

---

packages/session-replay-browser/src/events-manager.ts
packages/session-replay-browser/src/remote-config-fetch.ts
packages/session-replay-browser/src/session-idb-store.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/events-manager.test.ts
packages/session-replay-browser/test/remote-config-fetch.test.ts
packages/session-replay-browser/test/session-idb-store.test.ts

Store remote config in indexeddb, allowing us to only make request to fetch config each time a session starts

feat(session replay): store remote config in indexeddb

---

packages/session-replay-browser/src/remote-config-fetch.ts
packages/session-replay-browser/src/session-idb-store.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/integration.test.ts
packages/session-replay-browser/test/remote-config-fetch.test.ts
packages/session-replay-browser/test/session-idb-store.test.ts
packages/session-replay-browser/test/session-replay.test.ts
packages/targeting/src/index.ts
packages/targeting/src/targeting-factory.ts
packages/targeting/src/targeting.ts
packages/targeting/src/typings/targeting.ts

Evaluate targeting in SR init, storing the result in IndexedDB. With this PR we are not actually doing anything with the result, that will come later. I decided to put the logic for evaluation in the RemoteConfigFetch class, as it felt like too much for the base SessionReplay class to have to know about, I may update the name of RemoteConfigFetch in a future PR to make it a little more inclusive of targeting logic.

feat(session replay): evaluate targeting in SR init

---

packages/session-replay-browser/src/track-destination.ts
packages/session-replay-browser/test/integration.test.ts
packages/session-replay-browser/test/track-destination.test.ts

A customer discovered a race condition where its possible to add multiple of the same sequences to the send queue in specific circumstances, particularly upon blur. This adds a check to the queue to prevent the same sequence number from being added and sent

fix(session replay): prevent multiple of the same sequences from being added to send queue

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts

The previous web attribution will only fetch the campaign change for page reloading. This PR is to cover the case of a Single Page Application (SPA) campaign change (without reloading the page) in a new session. 

fix: fetch the campaign in SPA at session start

---

packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Styled-components throws an error that is meant to be caught by their internals, however rrweb was catching it and suppressing it instead. This PR adds a special case in our error handler to re-throw that error when it occurs, allowing other rrweb internal errors to still be caught.

fix(session replay): throw error for styled-components

---

packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts

When the page gets reloaded while the amplitude client is trying to send a request, the browser kills the request. When this happens, the event should not be dropped and should be retried the next time the client gets loaded.

fix: error when sending data to Amplitude should get retried

---

packages/analytics-browser-test/test/helper.ts
packages/analytics-browser-test/test/helpers.ts
packages/analytics-browser-test/test/web-attribution.test.ts

Jira [AMP-98581](https://amplitude.atlassian.net/browse/AMP-98581)
Add web attribution integration test
The test covers
1. Page reload. The test uses double init to mock hard page reload. 
a. In a new session should track all UTMs and referrers
b. In a new session should track no campaign if no UTMs and no referrer
c. In a new session should not track all UTMs and referrers if the referrer is excluded referrer
d. During a session should not fire campaign identify event for direct traffic
e. During a session  should track all UTMs and referrers if any campaign changed and not direct traffic
f.  During a session should start a new session with resetSessionCampaign enable and track campaign updates
2. Process event, when any events under process, which include SPA redirect 
a.  in a new …

test: web attribution integration test

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts

…691)"
This reverts commit 83e3eca5a529838a19f6c2afb59e1d8a5f2ac650.
This change made it not possible to tag start session events with the session replay ID

revert(browser): fix: have session and device IDs ready before plugin setup

---

packages/analytics-core/src/core-client.ts
packages/analytics-core/test/core-client.test.ts

We've observed that the SR plugin is not correctly awaited when added before the client is initialized. This is because the SR plugin performs some async behavior in setup, and the client timeline was not awaiting on the `.promise` of the `AmplitudeReturn` of `client.add`.
See the unit test in this PR for a good representation of the issue - I confirmed that this test fails without this fix.

fix(core): correctly await promises called before init

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/identifiers.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Now that setSessionId has an async action, we should wait for it to complete before proceeding in the plugin. This PR adds an optional async interface to setSessionId via the AmplitudeReturn interface, `await setSessionId().promise`. This will allow us to properly tag start session events with the correct replay id, after fetching the remote config to ensure the replays shoul d be captured.

feat(session replay): add ability to wait for setSessionId process to complete

---

packages/analytics-browser/src/config.ts
packages/analytics-browser/test/config.test.ts
packages/analytics-react-native/src/config.ts
packages/analytics-react-native/test/config.test.ts

https://amplitude.atlassian.net/browse/AMP-97294
If `window.location` is set to be an empty object in polyfills, 
```
global.window.location = global.window.location || {};
```
an error occurs "TypeError: Cannot read property 'split' of undefined".
This PR patches this edges cases with tests.

fix: location is polyfilled to an empty object

---

packages/session-replay-browser/src/config/remote-config.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/config/remote-config.test.ts

This PR adds a 5000ms timeout to the remote config fetch logic. This will prevent any long hanging remote config API calls from blocking execution of the rest of the SDK.

fix(session replay): add a timeout to remote config fetch

---

packages/analytics-remote-config/CHANGELOG.md
packages/analytics-remote-config/README.md
packages/analytics-remote-config/jest.config.js
packages/analytics-remote-config/package.json
packages/analytics-remote-config/rollup.config.js
packages/analytics-remote-config/src/index.ts
packages/analytics-remote-config/src/remote-config-idb-store.ts
packages/analytics-remote-config/src/remote-config.ts
packages/analytics-remote-config/src/types.ts
packages/analytics-remote-config/test/remote-config-idb-store.test.ts
packages/analytics-remote-config/test/remote-config.test.ts
packages/analytics-remote-config/tsconfig.es5.json
packages/analytics-remote-config/tsconfig.esm.json
packages/analytics-remote-config/tsconfig.json
yarn.lock

Introduce a generic version of SR's remote config fetch package, to be shared across different products/plugins. This package handles fetching remote config based on passed configKeys, and storing the results in Indexeddb. Config is stored in it's own DB, with object stores for each config namespace (ie, Session Replay config will be retrievable independently from Browser SDK config).

feat(analytics remote config): introduce generic remote config fetch and storage package

---

packages/analytics-core/src/core-client.ts
packages/analytics-core/test/core-client.test.ts

I observed that it is possible to fire a track call while awaiting on a plugin to be setup, and in that case, the track call is dropped, as the call is not added to the queue. Instead it's processed immediately, but in the Browser SDK, the Destination plugin has not been registered, so the track call is not sent to the backend. 
This PR adds a property to core-client to determine if it has processed all functions in the queue. This property can be used to determine whether any API call should be added to the queue or processed immediately.

fix(core): api calls should queue while awaiting queued promises

---

packages/plugin-session-replay-browser/src/session-replay.ts

This resolves a circular dependency issue that was causing errors to bubble up for customers. I confirmed through manual testing that the plugin is still successfully removed after this change, and replay capture ends after the plugin is removed.

fix(plugin session replay browser): remove circular dependency

---

packages/analytics-remote-config/src/remote-config-idb-store.ts
packages/analytics-remote-config/src/remote-config.ts
packages/analytics-remote-config/src/types.ts
packages/analytics-remote-config/test/remote-config.test.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/src/config/joined-config.ts
packages/session-replay-browser/src/config/local-config.ts
packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/config/joined-config.test.ts

[AMP-98593](https://amplitude.atlassian.net/browse/AMP-98593)
Pulls and joins remote privacy config for the session replay browser package. Also adds a custom config endpoint URL for local testing.
* Does your PR have a breaking change?:  No.
[AMP-98593]: https://amplitude.atlassian.net/browse/AMP-98593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(session-replay-browser): fetch privacy configs remotely and join with local

---

packages/analytics-browser-test/test/web-attribution.test.ts
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts

Customers are seeing the session events fire too often. 
https://amplitude.atlassian.net/browse/AMP-99237
https://amplitude.atlassian.net/browse/AMP-100016
https://amplitude.atlassian.net/browse/AMP-100149
The issue is that we never await on process. If there are too many events being processed, it will cause a blockage at line 305 and alll events are treated as new session events because we update the lastEvent time in the setSessionId after line 305. Removing await on webAttribution.init() allows every process call to run sequentially. The first event in the new session will set this.config.lastEventTime in setSessionId, and then process the subsequent event.
However, removing line 305 means we won't catch cases in single-page applications (SPAs) where, after the session expires, users …

fix: fix the session event fire too often issue

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/config.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-client-common/test/analytics-connector.test.ts

[AMP-93936]
This PR allows the Browser SDK to get and set sessionId from `ampSessionId` url parameter of the url (`window.location`). This allows the same sessionId and thus continuous user journey for cross domain tracking. 
This PR also changes how the SDK gets deviceId from the url.
- Previously, the SDK only supports `deviceId` url parameter
- Now, the SDK gets deviceId from `ampDeviceId` url parameter first and then falls back to `deviceId`
We add `amp` prefix because `deviceId` and `sessionId` are very generic names. 
For example, the SDK will automatically use the deviceId `my-device-id` and sessionId `1716245958483` from `https://www.example.com?ampDeviceId=my-device-id&ampSessionId=1716245958483`. 
It's recommended to follow the same sessionId format as the Browser SDK by using …

feat: support sessionId from url for cross domain tracking

---

packages/analytics-browser/src/transports/xhr.ts
packages/analytics-browser/test/transport/xhr.test.ts
packages/analytics-client-common/src/transports/fetch.ts
packages/analytics-client-common/test/transports/fetch.test.ts
packages/analytics-node/src/transports/http.ts
packages/analytics-node/test/transport/http.test.ts

[AMP-100725]
This PR fixes Amplitude transports so that The SDK will not throw an error when response has either empty body or has non-json format body, which triggers `Unexpected end of JSON input` error. Now in these two cases, the SDK will build the response based on the response code. 
[AMP-100725]: https://amplitude.atlassian.net/browse/AMP-100725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: response with non-json format

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts
packages/analytics-types/src/destination-context.ts

[Jira AMP-98809
](https://amplitude.atlassian.net/browse/AMP-98809)
This change is for making sure the events sent into the backend are in order.
Previously in the Typescript SDK, we 
- Sent different promises in parallel using Promise.all, which led to race conditions.
- Scheduled individual events based on their own timeout, which also resulted in events being sent out of order.
Current behavior:
- In the event of an error, we filter out problematic events while keeping all other events in the queue. These events will be retried with the next trigger.

fix: sends events in order

---

packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts

Avoid using window global variable directly and instead use `getGlobalScope()`

fix: don't use global window directly

---

packages/session-replay-browser/src/events/events-idb-store.ts
packages/session-replay-browser/test/events-idb-store.test.ts

Adding error handling for [AMP-101119](https://amplitude.atlassian.net/browse/AMP-101119) to defer issues as warnings and not trigger errors in client. 
https://amplitude.atlassian.net/browse/DDI-489
[AMP-101119]: https://amplitude.atlassian.net/browse/AMP-101119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(session replay): add error handling for indexeddb

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser/package.json
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/config.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-types/src/user-session.ts

Enable debug logs by setting `debugLogsEnabled` in the AMP_* cookie

fix: adding ability to enable debug logs using cookies

---

packages/session-replay-browser/package.json
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts
yarn.lock

* for errors that are marked external (as in triggered by clients outside of rrweb), rethrow those errors. Frameworks like styled components depend on these errors being thrown. 
* also fixed an issue I noticed while looking at safari and the default state of block selectors. 
WIP: needs the new version of rrweb

fix(session replay): rethrow external errors and fix block selectors null state

---

packages/analytics-remote-config/src/remote-config-idb-store.ts

I just ran into the deleteDB call hanging because the db wasn't closed first. Somewhat surprised this doesn't happen automatically in idb, but this change closes the DB before trying to delete it.

fix(remote config): close db before deleting

---

packages/analytics-remote-config/src/remote-config.ts
packages/analytics-remote-config/src/types.ts
packages/analytics-remote-config/test/remote-config.test.ts
packages/session-replay-browser/test/config/joined-config.test.ts
packages/session-replay-browser/test/integration.test.ts
packages/session-replay-browser/test/integration/sampling.test.ts
packages/session-replay-browser/test/session-replay-factory.test.ts
packages/session-replay-browser/test/session-replay.test.ts

Add `fetchTime`, the total time spent in milliseconds to get remote config. 
The timer starts at the beginning of `getRemoteConfig()` and ends when `getRemoteConfig()` returns.

feat(analytics-remote-config): add fetchTime 

---

.github/workflows/feature-branch-prerelease.yml

This PR stops the CI "Prerelease feature branch" publishing prereleases to CDN. It will only publish to NPM with a tag based on the branch name by selecting the feature branch. For example, the screenshot will release `2.x.x-featureremoteconfig.0`.
I added [--ignore-scripts](https://www.npmjs.com/package/@lerna/publish/v/3.14.1#--ignore-scripts) so that lerna will not run `build' commands of subpackages, for example, [uploading-to-s3](https://github.com/amplitude/Amplitude-TypeScript/blob/d00981e3d7d2572d479d49511b96282a44d81de7/packages/analytics-browser/package.json#L38) in analytics-browser.

ci: stop publishing preleases to CDN

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-browser-test/test/web-attribution.test.ts
packages/analytics-browser/package.json
packages/analytics-browser/src/config/joined-config.ts
packages/analytics-browser/test/config/joined-config.test.ts
packages/analytics-core/src/config.ts
packages/analytics-core/src/index.ts
packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/config.test.ts
packages/analytics-core/test/index.test.ts
packages/analytics-core/test/plugins/destination.test.ts
packages/analytics-types/src/config/browser.ts
packages/analytics-types/src/config/core.ts
packages/analytics-types/src/config/index.ts
packages/analytics-types/src/index.ts
yarn.lock

Add remote config fetch time to the payload. Example payload:
```
{
"api_key": "xxx",
"events": [
{
"user_id": "playground.user@amplitude.com",
"device_id": "657b8364-e231-421f-8f2d-42103c0fcc92",
"session_id": 1718215002924,
"time": 1718215008416,
"platform": "Web",
"language": "en-US",
"ip": "$remote",
"insert_id": "81bd3a1a-aadf-4f01-8375-76de4fd3fa9b",
"event_type": "[Amplitude] Page Viewed",
"event_properties": {
"[Amplitude] Page Domain": "127.0.0.1",
"[Amplitude] Page Location": "http://127.0.0.1:8080/",
"[Amplitude] Page Path": "/",
"[Amplitude] Page Title": "Amplitude SDK Playground",
"[Amplitude] Page URL": "http://127.0.0.1:8080/",
"[Amplitude] Page Counter": 2
},
"event_id": 115,
"library": "amplitude-ts/2.8.1",
"user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) …
```

fix(analytics-browser): add remote config fetch time

---

packages/session-replay-browser/package.json

Doing rimraf at post install seems to break the build. Trying to move it to the `build` command. Users seeing errors on install? https://github.com/amplitude/Amplitude-TypeScript/pull/776#discussion_r1643211964

fix(session-replay-browser): move rimraf from postinstall to build

---

.github/workflows/ci.yml
packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/config.ts
packages/analytics-browser/src/config/joined-config.ts
packages/analytics-browser/src/config/types.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/config/joined-config.test.ts
packages/analytics-core/src/timeline.ts
packages/analytics-core/test/timeline.test.ts
packages/analytics-core/tsconfig.json
packages/analytics-types/src/autocapture.ts
packages/analytics-types/src/config/browser.ts
packages/analytics-types/src/index.ts
packages/analytics-types/tsconfig.json

- Add `config.autocapture` and install the autocapture plugin if `config.autocapture` is not `false`. 
- Copy `AutocaptureOptions` from `@amplitude/plugin-autocapture-browser` to export them from `@amplitude/analytics-types` so that it can be used in the `BrowserConfig` interface without circular reference
- Will update `@amplitude/plugin-autocapture-browser`  to use `AutocaptureOptions` in `@amplitude/analytics-types` later in [AMP-102833]
- Timeline will NOT install a new plugin if it's name is the same as one of the existing plugins. 
Note:
Add `lib: dom, es6` to `tsconfig.json` of `analytics-types` and `analytics-core` for `Element` and `RegExp` in `AutocaptureOptions`. It will not affect existing customers using the packages. They don't need to add it to their `tsconfig.json`. And it …

feat(analytics-browser): integrate autocapture plugin

---

packages/analytics-browser/src/config/joined-config.ts
packages/analytics-browser/test/config/joined-config.test.ts

[AMP-102552]
Catch the error returned by `remoteConfigFetch.getRemoteConfig()` at https://github.com/amplitude/Amplitude-TypeScript/blob/0525097f4002f44349fc01c4a17486bf0ef5fbae/packages/analytics-remote-config/src/remote-config.ts#L163
[AMP-102552]: https://amplitude.atlassian.net/browse/AMP-102552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analytics-browser): should catch error from getRemoteConfig

---

packages/plugin-autocapture-browser/src/helpers.ts
packages/plugin-autocapture-browser/src/libs/messenger.ts
packages/plugin-autocapture-browser/test/helpers.test.ts

Use unique IDs and a callback map to allow clients to use a request/response pattern for communication to the opener window

feat(autocapture-browser): Adding async request/response pattern to Autocapture messenger

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/session-replay-browser/README.md
packages/session-replay-browser/package.json
packages/session-replay-browser/src/index.ts
packages/session-replay-browser/src/session-replay-factory.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/targeting/targeting-idb-store.ts
packages/session-replay-browser/src/targeting/targeting-manager.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/test/targeting/targeting-idb-store.test.ts
packages/session-replay-browser/test/targeting/targeting-manager.test.ts
packages/targeting/jest.config.js
packages/targeting/package.json
packages/targeting/src/targeting-idb-store.ts
packages/targeting/src/targeting.ts
packages/targeting/src/typings/targeting.ts
packages/targeting/test/flag-config-data.ts
packages/targeting/test/jest-setup.js
packages/targeting/test/targeting-idb-store.test.ts
packages/targeting/test/targeting.test.ts

This PR adds support for targeting via single or multiple event conditions. A new method is exposed, evaluateTargetingAndRecord, which accepts an event as a parameter. That event is passed to the targeting package, which updates an internal IDB store of events for the current session. The single event and the list of stored events are passed to the evaluation package to be compared against the targeting flag config.

feat(targeting and session replay): Add support for targeting by single event and multiple events

---

packages/session-replay-browser/src/hooks/click.ts
packages/session-replay-browser/test/hooks/click.test.ts

Adds scroll to click events, using RRweb's window scroll method.

fix(session-replay-browser): add scroll to click event

---

packages/analytics-client-common/src/global-scope.ts
packages/analytics-client-common/src/types/global.d.ts
packages/analytics-client-common/src/types/global.ts
packages/analytics-client-common/test/global-scope.test.ts

Adding another option to get the getGlobalScope function to assist with our integration
* Does your PR have a breaking change?:  NO

fix(analytics-client-common): adding ampIntegrationsContext to getGlobalScope

---

packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

The logger was not representing the correct log level when used with the standalone SDK, this fixes it so we can observe proper logging outside of the plugin

fix(session replay): fix logger for standalone

---

packages/session-replay-browser/package.json
packages/session-replay-browser/src/hooks/click.ts
packages/session-replay-browser/src/libs/finder.ts
yarn.lock

`@medv/finder` is not packaged to dual support ESM and CJS. We could own this repo or try to make things work upstream, but it doesn't seem like it's worth the effort of "vendoring" the file. Our build process will appropriately create ESM and CJS versions.

fix(session-replay-browser): remove @medv/finder as a dependency

---

packages/analytics-remote-config/src/remote-config-idb-store.ts
packages/analytics-remote-config/src/remote-config.ts
packages/analytics-remote-config/src/types.ts
packages/analytics-remote-config/test/remote-config-idb-store.test.ts
packages/analytics-remote-config/test/remote-config.test.ts
packages/session-replay-browser/src/index.ts
packages/session-replay-browser/src/session-replay.ts

2 changes in this PR:
1. Prevent remote config package from making multiple requests if response has been returned without certain keys - for example, if config response has `sampling_config` but not `targeting_config`, we should not keep refetching when package tries to access `targeting_config`
2. Type export and log level change in session replay

fix(remote config): prevent extra fetches of remote config

---

.github/workflows/ci.yml
.github/workflows/feature-branch-prerelease.yml
.github/workflows/publish-v1.yml
.github/workflows/publish-v2.yml
.prettierignore
lerna.json
package.json
yarn.lock

[AMP-102563]
https://github.com/lerna/lerna/issues/4027
- Update lerna version to 8.1.5 which depends on library braces 3.0.3 with a known security vulnerability fixed.
- `lerna repair` command automatically updates `lerna.json` and `.prettierignore` by following [lerna migration guide](https://github.com/lerna/lerna/blob/main/CHANGELOG.md#700-2023-06-08)
- Update CI's node version to use 18 and 20 as lerna 8.1.5 requires at lease node 18 and node 16 has already be end of life in 2023 according to https://nodejs.org/en/about/previous-releases
[AMP-102563]: https://amplitude.atlassian.net/browse/AMP-102563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update lerna version for security

---

packages/analytics-browser/src/config.ts
packages/analytics-browser/test/config.test.ts

[AMP-103256]
This PR fixes https://github.com/amplitude/Amplitude-TypeScript/issues/788 by setting `config.storageProvider` to be `MemoryStorage` when `config.storageProvider` (by default `localStorage` is disabled) as `localStorage` can be disabled in private mode browsers. 
[AMP-103256]: https://amplitude.atlassian.net/browse/AMP-103256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analytics-browser): fall back to MemoryStorage when localStorage is disabled

---

packages/session-replay-browser/src/helpers.ts
packages/session-replay-browser/test/helpers.test.ts
packages/session-replay-browser/test/test-data.ts

Supports higher granularity sample rate, up from 2 to 6 decimal places. Performance impact here should be negligible: https://jsperf.app/xeditu/2
This would give different results for the same session, but because sessions are short lived it should be OK.

feat(session-replay-browser): support higher granularity sample rate

---

packages/session-replay-browser/src/beacon-transport.ts
packages/session-replay-browser/src/helpers.ts
packages/session-replay-browser/src/hooks/beacon.ts
packages/session-replay-browser/src/hooks/scroll.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/track-destination.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/helpers.test.ts
packages/session-replay-browser/test/hooks/beacon.test.ts
packages/session-replay-browser/test/hooks/scroll.test.ts
packages/session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/test/track-destination.test.ts

Adds scroll event support. This tries its best to send scroll events which should be small on a page leave. It uses the Beacon API for reliability and performance with a fallback to XHR. I decided to add a few new classes:
1. ScrollWatcher -- Watches for max page scrolls and updates its state. It includes a hook for RRweb to trigger it to update its state and a BeaconTracker to send a Beacon API event for either 'pagehide' or 'beforeunload', whichever is supported by the browser.
2. BeaconTracker -- Wraps the Beacon API and provides an automatic fallback to XHR on failure.
There was a slight refactor to pull out common functions and make testing easier.
I tested this using the tasks-app in Chrome and Firefox though I may need to do a bit more testing. I'll especially need to do end to end …

feat(session-replay-browser): scroll events support

---

packages/plugin-ga-events-forwarder-browser/package.json
packages/plugin-ga-events-forwarder-browser/src/ga-events-forwarder.ts
packages/plugin-ga-events-forwarder-browser/test/constants.ts
packages/plugin-ga-events-forwarder-browser/test/ga-events-forwarder.test.ts
yarn.lock

It appears that google analytics now can send events using `fetch` rather than using the `sendBeacon` api. The current GA plugin does not capture these events and thus some customers are not seeing their GA events in amplitude. This PR adds a Proxy for fetch to capture these events in the same way as those for `sendBeacon` were.
Jira: https://amplitude.atlassian.net/browse/AMP-103958

fix: ga events sent through fetch not captured

---

packages/plugin-session-replay-browser/src/constants.ts
packages/plugin-session-replay-browser/src/helpers.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/helpers.test.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/targeting/targeting-manager.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

(Reattempting #808)
The current implementation of targeting via user properties relied on a Browser SDK instance being present (it used the analytics connector functionality). This PR updates the logic in the standalone to accept user properties as config and arguments to setSessionId and to evaluateTargetingAndRecord, and updates the plugin to pass user properties when appropriate.

feat(session replay): support targeting via passing user properties

---

packages/plugin-autocapture-browser/src/helpers.ts
packages/plugin-autocapture-browser/src/hierarchy.ts
packages/plugin-autocapture-browser/test/default-event-tracking-advanced.test.ts
packages/plugin-autocapture-browser/test/hierarchy.test.ts

- Reverse the hierarchy element ordering
-  This is important as elements from the end of the array will get removed if the total size of the property 
exceeds the projects limit. If only parents are removed, the selector functionality is more likely to still work, rather than if 
the last target element is removed
- Use better size approximation logic that allows the client to determine if the property is likely to be too long.

fix: Reverse hierarchy order and use more accurate property size calculation

---

packages/session-replay-browser/src/config/joined-config.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/config/joined-config.test.ts
packages/session-replay-browser/test/integration/sampling.test.ts

We used to record on remote config fetch failure, however with privacy config added it's important that if we fail to fetch any config that we do not record. Otherwise, we risk exposing unwanted text.

fix(session-replay-browser): remote config failure handling

---

package.json
packages/plugin-autocapture-browser/package.json
packages/plugin-autocapture-browser/src/autocapture-plugin.ts
packages/plugin-autocapture-browser/src/autocapture/track-action-click.ts
packages/plugin-autocapture-browser/src/autocapture/track-change.ts
packages/plugin-autocapture-browser/src/autocapture/track-click.ts
packages/plugin-autocapture-browser/src/helpers.ts
packages/plugin-autocapture-browser/src/libs/messenger.ts
packages/plugin-autocapture-browser/test/autocapture-plugin/track-action-clicks.test.ts
packages/plugin-autocapture-browser/test/default-event-tracking-advanced.test.ts
packages/plugin-autocapture-browser/test/helpers.test.ts
yarn.lock

This PR introduces significant enhancements to the autocapture plugin. Most notably, clicks that result in either a DOM mutation or a navigation event:
1. Implementation with RxJS for multiple event stream handling
2. Addition of action click tracking for elements not in the default selector list
3. Enhanced configurability with new options like `debounceTime` and `actionClickAllowlist`
4. Refactoring of event tracking logic into separate modules for better maintainability
5. Update the default `isElementSelectable` function that is passed to Visual Labeling to also include
elements from `actionClickAllowlist` 
Note on navigation events:
Currently this is not fully implemented in all browsers, the fallback will be beforeunload

feat(autocapture): track DOM mutations and navigation events to capture action clicks

---

packages/analytics-remote-config/src/remote-config.ts
packages/analytics-remote-config/test/remote-config.test.ts

There may be other required changes, but what I noticed is that when testing the SDK would check for the remote config often and succeed. However, after awhile it started to fail because of request exceeeded count. Resetting the attempt count after success helps a bit, but maybe there is a better solution later on.

fix(analytics-remote-config): reset attempt count on success

---

packages/session-replay-browser/src/config/joined-config.ts

I just observed that a sample rate of 0 wasn't being respected when sent via remote config, due to an improper falsy check. This is quite an edge case but figured I'd fix it upon observation anyways.

fix(session replay): set sample rate if it is 0 as well

---

packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/integration.test.ts
packages/session-replay-browser/test/integration/sampling.test.ts
packages/session-replay-browser/test/session-replay.test.ts

I believe we can now remove our focus/blur handling to stop/start recording when moving between tabs. Many customers have run into issues around this part of our logic, so much that we've had to add a `debugMode` option to our sdk to ease their pain. Reflecting on this recently, I realized that we no longer need this logic for the following reasons:
- Because of the IndexedDB refactor I did a few months ago, we now use IndexedDB as our source of truth for event lists. So the cross tab communication already works seamlessly without doing needing to sync the IndexedDB state to memory (this can be observed by looking at the sequenceId numbers in the track calls when switching back and forth between tabs, the sequenceIds automatically jump ahead to match the state from the previous tab)
- …

fix(session replay): remove focus/blur handling

---

packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Jackson pointed out that we will attribute incremental snapshots incorrectly if we don't take a full snapshot on a tab change. This updates the SDK to restart recording on focus (which will cause a full snapshot to be taken).
Example incorrect replay capture without this change: https://app.amplitude.com/analytics/amplitude/project/408823/search/amplitude_id%3D951490210053
Example correct replay capture with this change:
https://app.amplitude.com/analytics/amplitude/project/408823/search/amplitude_id%3D951502713658

fix(session replay): restart recording on focus

---

packages/session-replay-browser/package.json
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/src/version.ts
packages/session-replay-browser/test/session-replay.test.ts

* This sends RRweb events that include the config for internal debugging purposes.
* I also fixed the version being incorrect in the SDK.
Tested this locally.

feat(session-replay-browser): support debug info in session replay SDK

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/config/joined-config.test.ts
packages/analytics-client-common/src/default-tracking.ts
packages/analytics-client-common/src/index.ts
packages/analytics-client-common/test/default-tracking.test.ts
packages/analytics-types/src/config/browser.ts
packages/analytics-types/src/element-interactions.ts
packages/analytics-types/src/index.ts

[AMP-105806](https://amplitude.atlassian.net/browse/AMP-105806)
Rename `config.autocapture.userInteractions` to `config.autocapture.elementInteractions` to algin with mobile interfaces and make the config name less general.
[AMP-105806]: https://amplitude.atlassian.net/browse/AMP-105806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: rename userInteractions to elementInteractions

---

packages/plugin-autocapture-browser/src/autocapture-plugin.ts
packages/plugin-autocapture-browser/src/autocapture/track-action-click.ts
packages/plugin-autocapture-browser/test/autocapture-plugin/track-action-clicks.test.ts
packages/plugin-autocapture-browser/test/default-event-tracking-advanced.test.ts

- Lower rage click buffer to 0
- the buffer can have issues when the event triggers a navigate event, this causes the buffer to be lost and no event to be fired. There are work arounds for this, but since the rage click feature had not been turned on yet, disabling it will be sufficient for now
- Fix issue where action clicks fired for each mutation or navigate event, now, limit it to 1 so that the action click is triggered only once
- Fix issue where timestamp was not used for action clicks

fix(autocapture): Remove click tracking buffer and duplicate action clicks

---

packages/plugin-autocapture-browser/src/autocapture-plugin.ts

Add more elements to the default `cssSelectorAllowlist`
- `video`
- `audio`
- `[contenteditable="true" i]`

feat(autocapture): add more elements to the default cssSelectorAllowlist

---

packages/analytics-remote-config/src/remote-config-idb-store.ts
packages/analytics-remote-config/test/remote-config-idb-store.test.ts

Noticed when trying to debug an issue for a customer that we were creating the store with the incorrect store name here!

fix(remote config): recreate remote config store with correct name

---

packages/session-replay-browser/package.json

The description should cover it. An [example replay with the fix](https://app.amplitude.com/analytics/junjie-amplitude/session-replay/project/626341/search/amplitude_id%3D956859617383?sessionHandle=ZEQU/3P_ZEQU/3P_N7JRxBn_CY6l_b428b501-6223-4dcc-934b-9a9b250d6cf5&sessionReplayId=b428b501-6223-4dcc-934b-9a9b250d6cf5/1722555825615&sessionLength=199&sessionStartTime=1722555825615&deviceType=Windows&user_id=&country=United%20States).

fix(session-replay-browser): update rrweb version to 2.0.0-alpha.19 to fix duplicate text

---

packages/session-replay-browser/src/config/joined-config.ts
packages/session-replay-browser/src/constants.ts
packages/session-replay-browser/src/events/events-idb-store.ts
packages/session-replay-browser/src/events/events-manager.ts
packages/session-replay-browser/src/helpers.ts
packages/session-replay-browser/src/messages.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/track-destination.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/events-manager.test.ts
packages/session-replay-browser/test/helpers.test.ts
packages/session-replay-browser/test/integration/sampling.test.ts
packages/session-replay-browser/test/session-replay.test.ts

This PR adds extra logs to the SR SDK lifecycle, as well as adds storage size data to the custom event we are sending along with our rrweb events.

feat(session replay): add logging to SR SDK

---

packages/session-replay-browser/src/config/joined-config.ts
packages/session-replay-browser/src/helpers.ts
packages/session-replay-browser/src/session-replay.ts

Ensure API Key is obfuscated when config is printed locally as well as sent as custom rrweb event

fix(session replay): ensure api key is obfuscated in local logs

---

.github/workflows/ci.yml
.github/workflows/publish-v1.yml
.github/workflows/publish-v2.yml

Node 16 is end of life: https://endoflife.date/nodejs

chore(core): bump node versions for ci

---

packages/session-replay-browser/src/config/joined-config.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/config/joined-config.test.ts
packages/session-replay-browser/test/session-replay.test.ts

Move removeInvalidSelectorsFromPrivacyConfig to joined config class so that it can be run on session id change as well

fix(session replay): move removeInvalidSelectorsFromPrivacyConfig to joined config class

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/README.md
packages/session-replay-browser/package.json
packages/session-replay-browser/src/index.ts
packages/session-replay-browser/src/session-replay-factory.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/targeting/targeting-manager.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/flag-config-data.ts
packages/session-replay-browser/test/integration/sampling.test.ts
packages/session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/test/targeting/targeting-manager.test.ts
yarn.lock

This PR covers the following changes:
- Choose either targeting config or sampling config (if no targeting config exists) to determine if users should be captured
- Ensure the timing of replay capture is as follows:
- on init, stop capture and start anew (in the case a user is already being captured) - matches existing behavior
- on session id change, stop capture and start anew - matches existing behavior
- when evaluateTargetingAndCapture is called, only start capture if it hasn't been started yet - this is because `evaluateTargetingAndCapture` is called on every event - we don't want to cause a full dom snapshot on every event.
- Changed the names of any methods that have `record` in them to `capture`

feat(session replay): correct timing of replay capture, and use targeting config or sampling config

---

packages/session-replay-browser/src/constants.ts
packages/session-replay-browser/src/helpers.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Add a tool to fire custom rrweb events when recording, and add an event when getSessionReplayProperties is called.

chore(session replay): add custom rrweb event method and fire on getSessionReplayProperties

---

packages/session-replay-browser/src/session-replay-factory.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

We need to reset the targeting match state when the session id turns over. The unfortunate aspect about this change is it highlights the fact that we are keeping the state of targeting match in two places - both in component state and in IDB (within the targeting manager class). This is necessary because we need to be able to access the value of sessionTargetingMatch synchronously, as it's used by synchronous fns (getShouldCapture, which is used by captureEvents and getSessionReplayProperties), and accessing a value from IDB is an asynchronous action. The downside here is that it's possible for the component state to be out of sync with the IDB state if we're not careful to update it.

fix(session replay): set targeting match to false when session id is changed

---

.github/workflows/feature-branch-prerelease.yml

Need to use node 18+ in our jobs

ci: bump node version to match release jobs

---

packages/analytics-remote-config/src/remote-config.ts
packages/analytics-remote-config/src/types.ts
packages/analytics-remote-config/test/remote-config.test.ts
packages/session-replay-browser/test/config/joined-config.test.ts
packages/session-replay-browser/test/integration.test.ts
packages/session-replay-browser/test/integration/sampling.test.ts
packages/session-replay-browser/test/session-replay-factory.test.ts
packages/session-replay-browser/test/session-replay.test.ts

- Add a "metrics" filed with type `Map<string, string|number>` to remote config fetcher 
- Collect two metrics
- fetch time from IndexedDB
- fetch time from API

fix: add metrics field to remote config fetcher

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/integration/browser-sdk-integration.test.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

The Mobile SR team converted our enrichment plugin into an enrichment and destination plugin for a previous spike, but they no longer need that functionality. This PR simplifies the plugin back into a single enrichment plugin

refactor(session replay plugin): collapse plugins into one

---

packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Reduce the init error to warn to be less noisy

fix(session replay): change log level of init warning

---

packages/analytics-browser/package.json
packages/analytics-browser/src/config/joined-config.ts
packages/analytics-browser/test/config/joined-config.test.ts
packages/analytics-core/src/config.ts
packages/analytics-core/test/plugins/destination.test.ts
packages/analytics-types/src/config/core.ts
yarn.lock

This PR contains two changes
[AMP-106699]
Merging logic:
- `options.autocapture` should override `options.defaultTracking` if it’s set. This happens at `useBrowserConfig()` when creating browser config based on options customers passed in 
- In `joined-config.ts`, `remoteConfig.autocapture` should merge with `localConfig.autocapture` which means that if a field exists in `remoteConfig.autocapture`, it should add to mergedConfig, however, if a filed doesn’t exist, we should check the value in `localConfig.autocapture`
Examples
```
client.init(apiKey, userId, {
autocapture: false
}).promise;
// remote config is enabled only for clicks
{
autocapture: {
elementInteractions: true
}
}
// result
{
fileDownloads: false,
formInteractions: false,
pageViews: false,
attribution: false,
sessions: …
```

feat: support remote config for each autocapture field

---

packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Supports disabling batching for interaction events to eventually support attribution.

fix(session-replay-browser): support disabling batching for interaction events

---

packages/session-replay-browser/src/hooks/click.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/hooks/click.test.ts

We were sending a payload of strings rather than objects, which is incorrect. This fixes it.

fix(session-replay-browser): send proper interaction response

---

packages/plugin-autocapture-browser/src/helpers.ts
packages/plugin-autocapture-browser/src/libs/finder.ts

This change mirrors this PR in the upstream library: https://github.com/antonmedv/finder/pull/84
This prevents a scenario where a very large number of combinations are generated and causes memory exhaustion.

fix(autocapture): prevent potential memory exhaustion when generating combinations

---

packages/analytics-browser/package.json
yarn.lock

Bump `@amplitude/plugin-autocapture-browser` to  `1.0.1` to bring in this change: https://github.com/amplitude/Amplitude-TypeScript/pull/863

fix(browser): bump plugin-autocapture-browser package

---

packages/analytics-types/src/element-interactions.ts
packages/analytics-types/src/index.ts

A follow-up PR of https://github.com/amplitude/Amplitude-TypeScript/pull/780. 

fix(analytics-types): update element interactions options

---

packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts

[Related tickets 
](https://amplitude.atlassian.net/browse/AMP-107632)

feat: decode URI for page view properties

---

packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts

[Related ticket
](https://amplitude.atlassian.net/browse/AMP-108564)

fix: fix the pathOnly option

---

packages/analytics-react-native/android/build.gradle
packages/analytics-react-native/android/src/main/AndroidManifestNew.xml

- To support RN 0.73, library authors have to bump to AGP 8.1.1 according to the [breaking changes list](https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#other-breaking-changes)
- AGP 8.0 requires namespace in module level gradle.build https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#namespace-dsl
- Replace JCenter with Maven Center by following https://developer.android.com/build/jcenter-migration
For RN >= 0.73
- Added new `AndroidManifestNew.xml without namespace`
- Added namespace in build.gradle
Fix
- https://github.com/amplitude/Amplitude-TypeScript/pull/616
- https://github.com/amplitude/Amplitude-TypeScript/pull/617
- https://github.com/amplitude/Amplitude-TypeScript/issues/665
* Does your PR have a breaking …

fix(analytics-react-native): support RN 0.73

---

packages/plugin-autocapture-browser/src/autocapture-plugin.ts
packages/plugin-autocapture-browser/src/helpers.ts
packages/plugin-autocapture-browser/src/hierarchy.ts
packages/plugin-autocapture-browser/test/default-event-tracking-advanced.test.ts
packages/plugin-autocapture-browser/test/helpers.test.ts

This fixes scenarios where the `id` property inside the hierarchy was returning `{}` instead of a string.
The approach here is to use `getAttribute` for attributes and to cast these to a string to handle edge cases where another element can be returned in any property on the target element.
This happens because the `id` property of form elements (and some other specific elements) can sometimes return an element reference instead of a string as a special case. This behavior is part of an old DOM feature called "named property access" or "named access on the window object".
This would happen for form elements which have children inputs where the `name` or `id` attribute on those inputs overrides the property accessor with the same `name` or `id` value on the ancestor form element.
Example: …

fix(autocapture): use getAttribute to more safely access attributes

---

packages/analytics-types/src/element-interactions.ts

This PR fixes the issue in https://github.com/amplitude/Amplitude-TypeScript/pull/780 that `Element` type is resolved to the custom defined type because typescript looks up local scope first before global scope. 
Create a custom type `DomElement` if `Element` is available (`dom` library is added) otherwise set to `never`.
- `analytics-browser`, `plugin-autocapture-browser` will use `Element`
- `analytics-node` doesn't have access to `Element` and will use `never` instead

fix(analytics-types): update Element in element interactions

---

packages/plugin-autocapture-browser/package.json
packages/plugin-autocapture-browser/src/autocapture-plugin.ts
packages/plugin-autocapture-browser/src/autocapture/track-action-click.ts
packages/plugin-autocapture-browser/src/autocapture/track-change.ts
packages/plugin-autocapture-browser/src/helpers.ts
packages/plugin-autocapture-browser/src/index.ts
packages/plugin-autocapture-browser/src/libs/messenger.ts
packages/plugin-autocapture-browser/src/typings/autocapture.ts
packages/plugin-autocapture-browser/test/autocapture-plugin/track-action-clicks.test.ts
packages/plugin-autocapture-browser/test/default-event-tracking-advanced.test.ts
yarn.lock

- plugin-autocapture-browser imports types from analytics-types higher than 2.8.2
- Remove `${name} plugin requires a later version of @amplitude/analytics-browser. Events are not tracked.` warning because 
- analytics-types v2.x always requires client in plugin.setup() https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-types/src/plugin.ts#L14
- client is optional in analytics-types v1.x https://github.com/amplitude/Amplitude-TypeScript/blob/v1.x/packages/analytics-types/src/plugin.ts#L15

fix(plugin-autocapture-browser): import types from analytics-types

---

packages/analytics-browser/package.json
yarn.lock

Bump autocapture plugin version to v1.0.2 which uses types from analytics-types

fix(analytics-browser): bump autocapture plugin version

---

packages/analytics-browser/src/plugins/network-connectivity-checker.ts
packages/analytics-browser/test/plugins/network-connectivity-checker.test.ts

Check if navigator is available before using it for network connectivity checks

fix: disable network checker if navigator is unavailable

---

packages/analytics-react-native/src/index.ts
packages/analytics-react-native/src/react-native-client.ts
packages/plugin-autocapture-browser/package.json

[AMP-104265]
Should export `extendSession` in `client` to fix the error `Property extendSession is missing in type
typeof import("/Users/xinyi.ye/Documents/GitHub/ampli-examples/react-native/typescript/v2/AmpliApp/node_modules/@amplitude/analytics-react-native/lib/typescript/index")
but required in type ReactNativeClient`. 
Example:
```
amplitude.init('API_KEY');
await ampli.load({client: {instance: amplitude}}).promise;
```
---
This PR also updates `package.json` in `plugin-autocapture-browser` to use the correct type set in https://github.com/amplitude/Amplitude-TypeScript/commit/9d00976708f749dfbf4ad2e4627bd3981fd8fa2a
[AMP-104265]: https://amplitude.atlassian.net/browse/AMP-104265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

fix(analytics-react-native): should export extendSession in client

---

packages/session-replay-browser/src/config/local-config.ts

Fixes issue where the library wasn't propagating to the track call header. 

fix(session replay): add version option into local config generation

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/src/config/local-config.ts
packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/events/base-events-store.ts
packages/session-replay-browser/src/events/events-idb-store.ts
packages/session-replay-browser/src/events/events-manager.ts
packages/session-replay-browser/src/events/events-memory-store.ts
packages/session-replay-browser/src/events/in-memory-events-store.ts
packages/session-replay-browser/src/index.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/track-destination.ts
packages/session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/test/base-events-store.test.ts
packages/session-replay-browser/test/event-compressor.test.ts
packages/session-replay-browser/test/events-idb-store.test.ts
packages/session-replay-browser/test/events-manager.test.ts
packages/session-replay-browser/test/events-memory-store.test.ts
packages/session-replay-browser/test/integration.test.ts
packages/session-replay-browser/test/integration/sampling.test.ts
packages/session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/test/track-destination.test.ts

~~**Do not merge, still testing with the tasks app**~~
Currently, we store events using indexedDB (IDB). However, it's not possible in all cases where we want to capture replays that IDB is present. This PR adds an in-memory version of the event store that can either be the default store or will be the fallback if IDB is not present. The storage API is not quite stable yet and the implementation to make both stores unified needs a bit of work. This is small holdover to help in certain situations and to prevent a very large initial PR.
_Sorry for the long PR! This was an attempt at the minimal amount of changes with a few quality of life things thrown in._

feat(session-replay-browser): in memory events storage

---

packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/test/plugins/file-download-tracking.test.ts

Jira: [AMP-111576]
File download should also track when url contains url parameters. 
[AMP-111576]: https://amplitude.atlassian.net/browse/AMP-111576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analytics-browser): should track file download when with url params

---

examples/browser/next-app/.eslintrc.json
examples/browser/next-app/pages/index.tsx
packages/analytics-types/src/element-interactions.ts

Jira: [AMP-110387]
Fix https://github.com/amplitude/Amplitude-TypeScript/issues/883 by referring `globalThis['Element']` instead of using `infer T` to avoid build error in next.js. The root cause is that the syntax `infer T extends` is introduced in 4.8 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-8.html#improved-inference-for-infer-types-in-template-string-types.
Test with examples/browser/next-app with typescript 4.6.3
[AMP-110387]: https://amplitude.atlassian.net/browse/AMP-110387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analytics-types): build in next.js

---

packages/plugin-ga-events-forwarder-browser/src/helpers.ts
packages/plugin-ga-events-forwarder-browser/test/constants.ts
packages/plugin-ga-events-forwarder-browser/test/helpers.test.ts

When this feature was originally built, GA sent bulk events in a single request using the request payload. The request payload is a list of valid query parameter formatted string separated by the `\\r\\` character. A customer reported that their GA-forwarded events are not being formatted correctly. After some investigating, we are seeing the list of valid query parameter formatted stings are separated by `\n` character. The changes here include adding support to `\n` separated strings and ignoring events that are formatted outside the supported formats.

feat: adds support to \n separated request body for ga forwarding

---

.github/workflows/ci.yml

Adds Node 22.x to build env matrix

build: add node 22.x to build env matrix

---

packages/analytics-react-native/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt

Android SDK version 35 makes the table property non nullable in sqlite. 

fix: make table non nullable

---

packages/analytics-core/test/identify.test.ts
packages/analytics-types/src/event.ts

Jira: [AMP-114927]
Allow an array of objects as identify value type
```
const identify = new Identify();
const propertyValue = [
{
key1: 'value1',
key2: 'value2',
},
{
key1: 'value3',
key2: 'value4',
},
];
identify.set('PROPERTY_NAME', propertyValue);
```
[AMP-114927]: https://amplitude.atlassian.net/browse/AMP-114927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analytics-types): allow an array of objects as identity value type

---

examples/react-native/example/android/app/build.gradle

Updating android lib version to fix gson R8 issues

fix: updating android lib version to fix gson R8 issues

---

packages/plugin-session-replay-react-native/android/build.gradle

Update Android SDK version to fix R8 gson issue

fix: update android sdk version to fix r8 gson issue

---

packages/plugin-autocapture-browser/package.json
packages/plugin-ga-events-forwarder-browser/package.json
packages/plugin-ga-events-forwarder-browser/src/ga-events-forwarder.ts

* Fixes missing request body in intercept function call for fetch interception
* Fixes outdated version in builds

fix: missing body for fetch intercepts in ga events forwarder

---

packages/plugin-session-replay-react-native/android/build.gradle

Updating to the latest Android SDK which fixes a memory leak

fix: update android session replay library version to fix a memory leak

---

packages/analytics-remote-config/src/remote-config.ts
packages/analytics-remote-config/src/types.ts
packages/analytics-remote-config/test/remote-config.test.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts
packages/session-replay-browser/src/beacon-transport.ts
packages/session-replay-browser/src/config/local-config.ts
packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/events/events-manager.ts
packages/session-replay-browser/src/helpers.ts
packages/session-replay-browser/src/track-destination.ts
packages/session-replay-browser/test/helpers.test.ts

This allows for custom urls for the remote config and track endpoints to help with testing against mocked or local versions of these services. There is an old config that was changed, but it seems like that was not used at all.
* Does your PR have a breaking change?:  Yes, but the old config was not used.

feat(session-replay-browser): support custom urls for remote config and track endpoints.

---

packages/session-replay-browser/src/hooks/click.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/hooks/click.test.ts
packages/session-replay-browser/test/session-replay.test.ts

Does not add click/scroll hooks if interaction config is not present. Also prevents finder errors from affecting session replay.

fix(session-replay-browser): prevent finder errors from affecting session replay

---

packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts

[AMP-118975]
Fix the issue that events are not received by order by the server. The root cause is that `Promise.all()` executes calls concurrently thus resolve order is not guaranteed. Fix it by sending batches sequentially, in other words, only send the next batch when the preceding one resolves. 
See [comment](https://amplitude.atlassian.net/browse/AMP-118975?focusedCommentId=301158) for additional notes.
[AMP-118975]: https://amplitude.atlassian.net/browse/AMP-118975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analytics-browser): should send batches sequentially

---

packages/analytics-core/src/core-client.ts
packages/analytics-core/src/timeline.ts
packages/analytics-core/test/timeline.test.ts

Currently, calling amplitude.remove(badPluginName) will remove the last registered plugin. Fixing that issue

fix: amplitude.remove should only remove if plugin was already registered

---

packages/plugin-session-replay-browser/rollup.config.js
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/package.json
packages/session-replay-browser/rollup.config.js
packages/session-replay-browser/src/config/local-config.ts
packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/events/event-compressor.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/worker/compression.ts
packages/session-replay-browser/test/event-compressor.test.ts
packages/session-replay-browser/test/worker/compression.test.ts

Adds experimental support for WebWorkers to offload compression. This is an initial first pass to see performance with hopefully later iterations being more complex and offloading not only compression, but other things such as networking calls.
To enable add to your local config:
```javascript
{
experimental: {
useWebWorker: true
}
}
```

feat(session-replay-browser): WebWorker support for compression

---

packages/analytics-browser/src/lib-prefix.ts
packages/analytics-browser/src/plugins/context.ts
scripts/build/rollup.config.js

- Change library to `amplitude-ts-sdk-script` in amplitude-min.js which is renamed as `analytics-browser-x.x.x-min.js.gz`and uploaded to s3 at https://github.com/amplitude/Amplitude-TypeScript/blob/cbb0afa63034959559216d4ea5217b50ce6f4cf1/scripts/publish/upload-to-s3.js#L9
- The main goal is to be able to distinguish installation methods: script vs npm/yarn which remains to be `amplitude-ts`
```
// install by script example
<script src="https://cdn.amplitude.com/libs/analytics-browser-2.11.10-min.js.gz"></script>
```
- Keep this as part of rollup instead of updating amplitude-min.js to avoid amplitude-min.js is used before library updated
- library in lib/esm and lib/cjs remains `amplitude-ts`

chore: update script library

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

The goal of the Session Replay plugin is to always have it added and control configuration through remote config. However, the plugin currently affects the configuration such that it's impossible to override. Rather than have users specify `forceSessionTracking` explicitly to false we'll have it default to false and have the downside that potentially Session Start and Session End events are missing.
* Does your PR have a breaking change?:  No, but a configuration change which should be inconsequential.

fix(plugin-session-replay-browser): default forceSessionTracking to false

---

packages/plugin-ga-events-forwarder-browser/src/ga-events-forwarder.ts

fix: missing user id in ga4 forwarder plugin
Tested with a local setup:

fix: missing user id in ga4 forwarder plugin

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

In some cases, customers aren't able to get the right device id configured. This could be due to an issue with the browser SDK or multiple instances of the browser SDK with the plugin. In order to support issues where this is a problem, instead of requiring users to move to the standalone SDK we can allow them to override the device ID.

feat(plugin-session-replay-browser): support custom device id

---

packages/plugin-session-replay-browser/src/session-replay.ts

fix: add safe access to loggerProvider in session replay plugin

---

packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/test/plugins/form-interaction-tracking.test.ts

Instead of accessing an element's attributes through it's object property, access it using `getAttribute()`
This is especially important in form elements where property values can be overridden by it's children inputs with that have an attribute `name` or `id` where the value matches property name.
Ex:
```html
<form action="/form_submit.php">
<input name="action" />
</form>
```
```js
// console.log(form.action)
// <input name="action" />
```

fix(plugin-form-interaction-tracking-browser): Access element attributes through getAttribute

---

packages/session-replay-browser/package.json
yarn.lock

We are bumping our rrweb versioning to include the latest Alpha release - https://github.com/rrweb-io/rrweb/pull/1554

chore(session replay): bump rrweb versioning to 2.0.0-alpha.27

---

packages/analytics-browser/test/browser-client.test.ts
packages/analytics-core/src/plugins/destination.ts
packages/analytics-core/test/plugins/destination.test.ts

This PR fixes https://github.com/amplitude/Amplitude-TypeScript/issues/963
When network is bad, for example, 3G, a network request takes time greater than flush interval to resolve, the SDK shouldn't keep sending events before the previous request.
Current behavior:
0       -> event1, schedule(1000)
1000    -> flush(event1)
1050    -> event2, schedule
**2000    -> flush(event1 + event2)**
2100    -> request1 resolve
Expected behavior:
0       -> event1, schedule(1000)
1000    -> flush(event1)
1050    -> event2, schedule(1000)
2050 (1050 + 1000)   -> no flush(event2) because request1 has not resolved
2200(1000 + 1200)    -> request1 resolved, schedule(1000)
3200    -> flush(event2)
- Introduce 2 schedule indicators in blue
- scheduleTimeout: the timeout of the current schedule. If there is …

fix(analytics-core): should not flush until previous request resolves

---

packages/analytics-types/src/base-event.ts

* Moves `groups` to `EventOptions` from `BaseEvent`
* Should not be a breaking change because `BaseEvent` still has `groups`
* Does your PR have a breaking change?:  Yes

feat: moves groups to eventoptions type

---

.github/workflows/publish-v2.yml

ci: update publish-v2 to use node node 18.17.x

---

packages/analytics-react-native/tsconfig.json
packages/plugin-session-replay-react-native/tsconfig.json
tsconfig.json

```
$ tsc -p ./tsconfig.es5.json
tsconfig.es5.json:4:3 - error TS5101: Option 'noImplicitUseStrict' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
```
According to https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#deprecations-and-default-changes, `noImplicitUseStrict` is deprecated in ts 5.0 and removed in ts 5.5. This setting no longer has any effect, meaning 
it's now `"noImplicitUseStrict": false` and not configurable, and ts will always insert "user strict" at the top of modules ( all modules will be treated as strict mode js).
The root yarn.lock uses typescript 5.5.2 https://github.com/amplitude/Amplitude-TypeScript/blob/a9463e89a750d11163ecfd120e34e7498422bbfc/yarn.lo …

ci: remove noImplicitUseStrict as it's deprecated in ts 5.5

---

packages/analytics-remote-config/package.json

- Delete `version` command as it shouldn't reinstall dependencies. And that's why publish-v2 fails
```
src/config/joined-config.ts:198:5 - error TS2322: Type 'SessionReplayLocalConfig' is not assignable to type 'Config'.
Types of property 'serverZone' are incompatible.
Type '"US" | "EU" | "STAGING" | undefined' is not assignable to type 'ServerZoneType | undefined'.
Type '"STAGING"' is not assignable to type 'ServerZoneType | undefined'.
198     localConfig,
~~~~~~~~~~~
../analytics-remote-config/lib/esm/types.d.ts:32:5
32     localConfig: Config;
~~~~~~~~~~~
The expected type comes from property 'localConfig' which is declared here on type '{ localConfig: Config; configKeys: string[]; }'
```
- Delete analytics-client-common as it's not used

chore(analytics-remote-config): update package.json

---

packages/analytics-core/src/core-client.ts
packages/analytics-core/src/timeline.ts
packages/analytics-core/test/timeline.test.ts

Replicating the fix that we did on the main branch for v1.x as well
https://github.com/amplitude/Amplitude-TypeScript/pull/936/files

fix: plugin remove should only remove plugin if it exists

---

packages/plugin-autocapture-browser/src/autocapture/track-action-click.ts
packages/plugin-autocapture-browser/src/autocapture/track-click.ts
packages/plugin-autocapture-browser/test/autocapture-plugin/track-action-clicks.test.ts
packages/plugin-autocapture-browser/test/default-event-tracking-advanced.test.ts

[AMP-122086](https://amplitude.atlassian.net/browse/AMP-122086)
Previously time was assigned to the event based on the exact timestamp of the event when it was fired. This was meant to ensure that any delay in calling track() would not impact the ordering of events.
However it seems like this potentially has the opposite effect where it causes these events to appear in the wrong order in the user timeline
[AMP-122086]: https://amplitude.atlassian.net/browse/AMP-122086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(autocapture): remove time assignment for element interactions tracking

---

packages/analytics-browser-test/test/index.test.ts
packages/analytics-core/src/revenue.ts
packages/analytics-core/src/types/event/base-event.ts
packages/analytics-core/test/revenue.test.ts
scripts/templates/browser-bookmarklet.template.js
scripts/templates/browser-snippet.template.js

https://amplitude.atlassian.net/browse/AMP-126168
Add missing revenue properties: revenue and revenue sig. 
https://amplitude.com/docs/sdks/analytics/browser/browser-sdk-2#revenue-interface
```
const event = new amplitude.Revenue()
.setProductId('com.company.productId')
.setPrice(3.99)
.setQuantity(3);
.setReceipt('receipt');
.setReceiptSig('receipt signature');
amplitude.revenue(event);
```

feat(analytics-core): add support for revenue receipt and receipt sig

---

packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/constants.ts
packages/session-replay-browser/src/observers.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/observers.test.ts
packages/session-replay-browser/test/session-replay.test.ts
yarn.lock

New network observer for observing fetch requests. This is currently set up to watch ALL requests and enabled through remote config. 

feat(session replay): initial network observers

---

packages/plugin-autocapture-browser/package.json

A follow up PR of https://github.com/amplitude/Amplitude-TypeScript/pull/988/files. 
analytics-client-common is not used in the autocapture plugin. Also remove `yarn add` command when `yarn version` to avoid reinstall the package when publishing. 

chore(plugin-autocapture-browser): remove analytics-client-common

---

packages/analytics-browser/src/config.ts
packages/analytics-browser/test/config.test.ts
packages/analytics-core/src/types/browser-config.ts

Adding the version to BrowserConfig class. This one is slightly different from v1.x, since the code is different for `useBrowserConfig`.

chore(analytics browser): version to the config object

---

packages/plugin-session-replay-react-native/README.md
packages/plugin-session-replay-react-native/android/src/main/java/com/amplitude/pluginsessionreplayreactnative/PluginSessionReplayReactNativeModule.kt
packages/plugin-session-replay-react-native/example/App.tsx
packages/plugin-session-replay-react-native/example/ios/Podfile.lock
packages/plugin-session-replay-react-native/ios/PluginSessionReplayReactNative.mm
packages/plugin-session-replay-react-native/ios/PluginSessionReplayReactNative.swift
packages/plugin-session-replay-react-native/src/session-replay-config.tsx
packages/plugin-session-replay-react-native/src/session-replay.ts

Add a log-level config param to remove hardcoded debug logging in PluginSessionReplayReactNative

feat(session replay rn): add log level config to session replay rn plugin

---

packages/analytics-browser/src/plugins/file-download-tracking.ts
packages/analytics-browser/src/plugins/form-interaction-tracking.ts
packages/analytics-browser/test/plugins/file-download-tracking.test.ts
packages/analytics-browser/test/plugins/form-interaction-tracking.test.ts

[AMP-126154]
Previously, we only add file download form interaction listeners when `load` event is dispatched. This works for scenarios when plugins are installed before page loads, for example, script tag in header. Events are not tracked when plugins are installed after page loads where no load event is dispatched. This PR fixes it. 
[AMP-126154]: https://amplitude.atlassian.net/browse/AMP-126154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analytics-browser): should track file download and form interaction when plugins are installed after page loads

---

packages/analytics-browser/src/index.ts

Fix https://github.com/amplitude/Amplitude-TypeScript/issues/1004
Follow up PR of https://github.com/amplitude/Amplitude-TypeScript/pull/993. 
Enums are essentially constants. So export them as const rather than type under the namespace `Types`. Keep re-exported interfaces as type.

fix(analytics-browser): re-export enums from analytics-types

---

packages/analytics-browser/src/config.ts
packages/analytics-browser/test/config.test.ts
packages/analytics-core/src/types/browser-config.ts

This PR sets the default for the `fetchRemoteConfig` option to be `true`.
The goal of this is to allow more users, excluding those who have set it to false explicitly, to be able to control their SDK configuration through the Amplitude platform.

feat(analytics-browser): set default for fetchRemoteConfig option to true

---

packages/analytics-core/src/remote-config/remote-config-localstorage.ts
packages/analytics-core/src/remote-config/remote-config.ts
packages/analytics-core/test/remote-config/remote-config-localstorage.test.ts
packages/analytics-core/test/remote-config/remote-config.test.ts

[AMP-124564]
Remote config client
- Have the same design and APIs as the iOS one https://github.com/amplitude/AmplitudeCore-Swift/pull/2
- A remote config client based on request-on-demand and subscription + callback modes. 
- The remote config client has 3 public APIs. See code comment for more details. 
- `subscribe()` is very similar to `addEventListener()`. Callback is called when the remote config fetched. 
- Analytics SDK will initialize a remote config client and plugins can use it for request remote config on their needs.
```
export interface IRemoteConfigClient {
subscribe(key: string | undefined, deliveryMode: DeliveryMode, callback: RemoteConfigCallback): string;
unsubscribe(id: string): boolean;
updateConfigs(): void;
}
```
Remote config storage
- Default to local storage. …

feat(analytics-core): remote config client

---

packages/plugin-session-replay-browser/README.md
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/README.md
packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/typings/session-replay.ts

Documenting additional SDK parameters.

docs(session-replay-browser): adding documentation for options in the standalone sdk

---

packages/analytics-core/src/utils/uuid.ts
packages/analytics-core/test/utils/uuid.test.ts

Hi, this is Jake from the Technical Support team.
There was an issue of user properties being mapped incorrectly due to colliding UUIDs set by the Amplitude TS SDK[due to math.random function]. 
There was a fix in JS SDK but not carried over to TS SDK
- https://github.com/amplitude/Amplitude-JavaScript/blob/v8.x/src/uuid.js
The issue has been stale, so I am making PR for the issue!
* [v] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-TypeScript/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?

fix(uuid): set UUID's using crypto libraries instead of Math.random

---

.github/workflows/jira-issue-create-template.yml

GitHub issues with long titles were causing Jira ticket creation to fail because the combined length of the prefix `[SDK - {label}]` and the GitHub issue title could exceed Jira's 255-character limit for summaries. While GitHub has a 256-character limit for issue titles, this doesn't account for the additional characters added by our prefix format.
- Added a truncation step that calculates the maximum allowed title length, accounting for:
- The prefix length (`[SDK - {label}] `)
- The ellipsis length (`...`)
- The remaining space for the actual title
- Truncates the GitHub issue title if needed, preserving the prefix format
- Adds ellipsis (...) to indicate when a title has been truncated
This will impact all repos that depend on this workflow, e.g. …

fix: truncate GitHub issue titles for Jira ticket creation

---

.github/workflows/jira-issue-create-template.yml

Did not work on first run, will look into trying to manually test this elsewhere first then recreate 
Reverts amplitude/Amplitude-TypeScript#1023

chore: Revert "fix: truncate GitHub issue titles for Jira ticket creation"

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/index.ts
packages/analytics-browser/test/browser-client.test.ts

[AMP-126972](https://amplitude.atlassian.net/browse/AMP-126972)
This PR adds an interface `PluginHost` with a method `plugin()` which returns the plugin instance by name string. 
This PR supports installing experiment as a plugin https://github.com/amplitude/experiment-js-client/pull/168
[AMP-126972]: https://amplitude.atlassian.net/browse/AMP-126972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(analytics-browser): plugin host

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-core/src/core-client.ts
packages/analytics-core/src/identify.ts
packages/analytics-core/src/timeline.ts
packages/analytics-core/src/types/event/event.ts
packages/analytics-core/src/types/plugin.ts
packages/analytics-core/test/core-client.test.ts
packages/analytics-core/test/timeline.test.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

[AMP-126972](https://amplitude.atlassian.net/browse/AMP-126972)
Add three APIs to plugin. They are called when the corresponding property is changed. 
- onSessionIdChanged()
- onOptOutChanged()
- onIdentityChanged()
Adopt SR plugin to the first two.
- onSessionIdChanged()
- update session replay instance's session id
- onOptOutChanged()
- call session replay shutdown() or init() according to optOut
[AMP-126972]: https://amplitude.atlassian.net/browse/AMP-126972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(analytics-core): new plugin interfaces onXXXchanged()

---

packages/plugin-session-replay-browser/test/integration/browser-sdk-integration.test.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

Clean left analytics-types in tests! 

chore(plugin-session-replay-browser): clean analytics-types in tests

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/index.ts
packages/analytics-browser/test/index.test.ts
packages/analytics-core/src/core-client.ts
packages/analytics-core/test/core-client.test.ts

This PR is made for the experiment plugin https://github.com/amplitude/experiment-js-client/pull/168
- Export class `AmplitudeBrowser` for experiment plugin integration
- Move `PluginHost` from `AmplitudeBrowser` to `AmplitudeCore`

fix(analytics-core): add support for experiment plugin

---

packages/analytics-browser/src/config/joined-config.ts
packages/analytics-browser/test/config/joined-config.test.ts

- Updated types of `BrowserRemoteConfig` to reflect the addition of the pageUrlAllowlistRegex property inside `elementInteractions`
- Updated `generateJoinedConfig()` to also initialize those strings from `pageUrlAllowlistRegex` as RegExp objects and append them to the original
[Jira](https://amplitude.atlassian.net/browse/AMP-127542)

feat(analytics-browser): allow initialization of remote config property pageUrlAllowlistRegex

---

packages/plugin-session-replay-browser/src/index.ts
packages/plugin-session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/events/event-compressor.ts
packages/session-replay-browser/src/index.ts
packages/session-replay-browser/src/session-replay-factory.ts

- Add a class property `sr` to `SessionReplayPlugin` class
- Export `SessionReplayPlugin` class 
Will create a PR to add this example to `examples/browser/react-app/` in another PR. https://github.com/amplitude/Amplitude-TypeScript/commit/dfded000878b45a1245fc84cf3738fc834d29a97
Local test: 
Analytics and SR work: 
```ts
const client: AmplitudeBrowser = new amplitude.AmplitudeBrowser();
client.init('5b9a9510e261f9ead90865bbc5a7ad1d', 'user@company.com', {
logLevel: amplitude.Types.LogLevel.Debug,
}).promise.then((_) => {
client.add(sessionReplayPlugin({debugMode: true})).promise.then((_) => {
// Add SR plugin to existing Amplitude analytics SDK
// and call SR APIs.
// SR APIs are only available when
// 1. Amplitude instance has successfully setup
// 2. SR plugin has been installed …
```

feat(plugin-session-replay-browser): add an sr instance property

---

packages/analytics-core/package.json
yarn.lock

Fix https://github.com/amplitude/Amplitude-TypeScript/pull/1030
"@amplitude/analytics-connector" can be removed after: 
1. Next major version of experiment SDK to remove dependency on analytics-connector
2. Next major version of analytics-core to not export AnalyticsConnector related stuffs

fix(analytics-core): add missing analytics-connector dependency

---

packages/analytics-core/src/index.ts
packages/analytics-core/src/network-observer.ts
packages/analytics-core/test/network-observer.test.ts
packages/session-replay-browser/src/session-replay.ts

* copied Jesse's implementation of [network observer](https://github.com/amplitude/Amplitude-TypeScript/blob/AMP-125616/add-autocomplete/packages/session-replay-browser/src/observers.ts#L25) to be a singleton class in "analytics-core"
* changed methods from "start" and "stop" to "subscribe" and "unsubscribe" and made it so that it can be subscribed to multiple times
* added requestBodySize and responseBodySize to network events and added functions to calculate the size of those
* note that this is unused (hence why it's a "chore"). The next stages will be to
* make the network request autocapture
* port over "observer.ts" to use this

chore: make a re-usable version of the Network Observer

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts

A previous change (#1008) set the default value of fetchRemoteConfig to be `true`, but this default was not being used which resulted in fetchRemoteConfig defaulting to `undefined`.
This change fixes it by referencing the correct browserOptions variable which includes the default values

fix(analytics-browser): default values for config were not being used for fetchRemoteConfig

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/test/browser-client.test.ts

Reverts #1037 
This breaks some tests that are non-trivial to fix, reverting change for now

chore: Revert: "fix(analytics-browser): default values for config were not being used for fetchRemoteConfig"

---

.github/workflows/feature-branch-prerelease.yml

Bump the version of NodeJS that the pre-release workflow uses so that it's the same as v2 release.
This was done because an [attempt to do the pre-release](https://github.com/amplitude/Amplitude-TypeScript/actions/runs/14653457044/job/41124195039) due to a dependency required Node >= 18.17 

chore: update Node version in pre-release workflow

---

packages/analytics-browser/src/default-tracking.ts
packages/analytics-browser/test/default-tracking.test.ts
packages/analytics-core/src/network-observer.ts

also, make it so `autocapture.networkTracking` defaults to `false`.

fix(analytics-browser): use performance.now in network capture

---

.github/workflows/jira-issue-create-template.yml

GitHub issues with long titles were causing Jira ticket creation to fail because the combined length of the prefix `[SDK - {label}]` and the GitHub issue title could exceed Jira's 255-character limit for summaries. While GitHub has a 256-character limit for issue titles, this doesn't account for the additional characters added by our prefix format.
- Added a truncation step that calculates the maximum allowed title length, accounting for:
- The prefix length (`[SDK - {label}] `)
- The ellipsis length (`...`)
- The remaining space for the actual title
- Removes quotes
- Truncates the GitHub issue title if needed, preserving the prefix format
- Adds ellipsis (...) to indicate when a title has been truncated
This will impact all repos that depend on this workflow, e.g. …

chore: fix jira issue create workflow

---

packages/plugin-network-capture-browser/src/track-network-event.ts
packages/plugin-network-capture-browser/test/autocapture-plugin/track-network-event.test.ts

Calls to "fetch" with a relative URL were not being captured and causing an exception to be thrown because [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) doesn't parse and throws an exception if you pass it a relative URL without a base URL.
Added a helper function that parses the URL with the base URL, and also catches the exception and returns undefined if it breaks.

fix(plugin-network-capture): fix bug that fails to capture relative URLs

---

package.json

TEMPORARILY switching to "from-package" in Lerna so that we can publish packages that failed to publish. Revert this once that's done.

chore: publish lerna from-package temporarily

---

packages/plugin-session-replay-react-native/amplitude-plugin-session-replay-react-native.podspec
packages/plugin-session-replay-react-native/ios/ConsoleLogger.swift

Session Replay no longer provides a logger, it uses the version from core.
Also, update min version of sr to the unified release.

fix: use correct logger

---

packages/session-replay-browser/src/config/joined-config.ts
packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/constants.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/config/joined-config.test.ts
packages/session-replay-browser/test/session-replay.test.ts

Adding metadata event that propagates as an rrweb event. This will be processed to be used later as metadata information including versions and debugging. 

chore(session replay): add metadata and config to rrweb events

---

packages/analytics-core/src/core-client.ts
packages/analytics-core/test/core-client.test.ts
packages/unified/src/unified.ts
packages/unified/test/unified.test.ts

Add a new API `plugins()` to `PluginHost` to support the case that multiple product experiment (experiment-js-client) instances can be attached to one analytics client instance. 
reference: https://github.com/amplitude/AmplitudeCore-Swift/pull/27

feat(analytics-core): add plugins to look up plugin by class type

---

packages/segment-session-replay-plugin/package.json

PR updates `package.json` for `segment-session-replay-plugin` to allow the package to be published to NPM.
- Removes the private status
- Adds a `publishConfig`

chore(segment-session-replay-plugin): set publishConfig and remove private status in package.json

---

packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts
packages/plugin-page-view-tracking-browser/test/page-view-tracking.test.ts
test-server/browser-sdk/page-view-history.html

When we cal teardown on page view plugin, `window.history.pushState` is restored to whatever it was before we overwrote it. The problem with this is that if another plugin also overwrites `window.history.pushState` after we do, and then we restore it, their implementation will get overwritten to.
This PR stops the restoration of `pushState` and what it does instead is adds a flag `isTracking` that needs to be `true` for page tracking to work. So when "setup" is called, `isTracking=true`. When "teardown" is called", "isTracking=false" again and then the `history.pushState` callback becomes essentially a "no-op"
Also added a page to test-server that lets you manually test this.

 fix(plugin-page-view-tracking-browser): do not restore history.pushState on teardown

---

packages/segment-session-replay-plugin/README.md

Correct installation command syntax in README for segment-session-replay-plugin.  Previously there was an unclosed quote which caused issues when copying and pasting the command.
* Does your PR have a breaking change?:  No, docs change.

fix(docs): correct installation command syntax in README for segment-session-replay-plugin

---

packages/plugin-session-replay-react-native/android/src/main/java/com/amplitude/pluginsessionreplayreactnative/PluginSessionReplayReactNativeModule.kt

This change adds compatibility checks to prevent crashes when the plugin is used with apps running on the old React Native architecture instead of the new architecture. Ensures the plugin works reliably across different React Native configurations.
Fixes https://github.com/amplitude/Amplitude-TypeScript/issues/1028
Fixes https://github.com/amplitude/Amplitude-TypeScript/issues/1028

fix(react-native-session-replay): prevent crash on Android with old architecture 

---

packages/analytics-browser/src/default-tracking.ts
packages/analytics-browser/test/default-tracking.test.ts

* restore `isTrackingEnabled` to what it was before
* refactor `isNetworkTrackingEnabled` so it works the exact same way as `isElementInteractionsEnabled`

fix: make opt-in logic for networkTracking match elementInteractions

---

packages/unified/package.json
packages/unified/src/index.ts
packages/unified/src/library.ts
packages/unified/src/unified.ts
packages/unified/src/version.ts
packages/unified/test/library.test.ts

When dogfood the unified SDK on corp site, the event library was not changed and remained to be `amplitude-ts/2.17.6`. This PR changes the unified version library to enrichment type to be processed later than the version library of the browser sdk. 

fix(unified): update version library to enrichment type

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/default-tracking.ts
packages/analytics-browser/test/browser-client.test.ts
packages/analytics-browser/test/default-tracking.test.ts
packages/analytics-core/src/types/browser-config.ts
test-server/browser-sdk/index.html

* Currently only "config.networkTrackingOptions" is used to defined network tracking. This PR adds "config.autocapture.networkTracking = {}" as an option too
* Also, this PR makes "autocapture.networkTracking" explicitly opt-in, meaning you have to set `autocapture.networkTracking` to `true` or an object for `networkTracking` to be enabled.
* I also changed the type `isTrackingEnabled(autocapture: AutocaptureOptions, ...)` to `isTrackingEnabled(autocapture: AutocaptureOptionsDefaultAvailable, ...)`
* `AutocaptureOptionsDefaultAvailable` is a new type that's a subset of AutocaptureOptions that only includes `'pageViews' | 'sessions' | 'fileDownloads' | 'formInteractions' | 'attribution'`
* This is to prevent future autocapture features from calling "isTrackingEnabled" and being enabled …

fix(analytics-browser): support autocapture.networkTracking as object

---

packages/analytics-browser/test/browser-client.test.ts
packages/plugin-session-replay-browser/test/session-replay.test.ts

- correct `initialize` typos in tests
- `npm test`

chore: fix typo in tests

---

packages/analytics-core/src/network-request-event.ts
packages/analytics-core/test/network-observer.test.ts
packages/plugin-network-capture-browser/test/autocapture-plugin/track-network-event.test.ts
test-server/browser-sdk/fetch.html

If NetworkRequestEvent encounters status=undefined in it's constructor, set it to 0 by default. Status 0 is a default status meaning that no response came back.

fix(plugin-network-capture-browser): default status=undefined as 0

---

packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

Correct type mapping for SDK Plugins that are not Amplitude specific such as Segment.

fix(session-replay): map the type to the correct sdk plugin

---

.cursor/rules/code-style.mdc
.cursor/rules/commit-and-pr-guidelines.mdc

Adds comprehensive Cursor rules documentation to improve development workflow and maintain consistency across Amplitude-TypeScript.
Example usage:
type `commit and create a pr following @commit-and-pr-guidelines.mdc` in Cursor and it will automatically commit and create a PR with title and description. You can change them later. You have to install [Browser MCP](https://chromewebstore.google.com/detail/browser-mcp-automate-your/bjfgambnhccakkhmkepdoekmckoijdlc) first to allow Cursor interact with your browser. 
- Added commit and PR guidelines following conventional commits
- Added code style and formatting rules

docs: add Cursor rules for development standards

---

test-server/index.html
vite.config.js

Make it so that "test-server/index.html" serves as a site map for the rest of the server. This is so that web pages can be easily discoverable and so that it's easier to figure out how to add and remove pages from the test server.

chore: make test files linkable from index.html

---

packages/plugin-network-capture-browser/README.md
packages/plugin-network-capture-browser/src/network-capture-plugin.ts

resulting from copy-pasting autocapture to network capture
This plugin was created by copying autocapture-browser and then renaming some stuff and re-writing. Some of the docoumentation wasn't updated properly. And there was a bit of unused code.

chore: fix documentation + remove unused code

---

.github/workflows/publish-single-package.yml

This workflow allows publishing individual packages with the following features:
- Package name input (e.g., unified, analytics-browser)
- Release tag selection (beta, alpha)
- Dry run mode for testing without actual publishing
- Automatic version bumping using semantic versioning
- Changelog updates and npm publishing
- Package privacy management (temporary public, restore to private)
The workflow includes proper authorization checks, builds, tests, and cleanup steps to ensure safe and reliable package publishing.

ci: add single package publish workflow

---

packages/analytics-remote-config/src/remote-config.ts
packages/analytics-remote-config/src/types.ts
packages/analytics-remote-config/test/remote-config.test.ts
packages/session-replay-browser/src/config/joined-config.ts
packages/session-replay-browser/test/__mocks__/@amplitude/analytics-remote-config.ts
packages/session-replay-browser/test/config/joined-config.test.ts
packages/session-replay-browser/test/integration.test.ts
packages/session-replay-browser/test/integration/sampling.test.ts
packages/session-replay-browser/test/session-replay-factory.test.ts
packages/session-replay-browser/test/session-replay.test.ts

We were previously making a remote call for each key of the config. This changes it to only look up the namespace and fetch the keys in JS.
Tested using tampermonkey:

fix(session-replay-browser): reduces network calls to remote config from many to 1

---

packages/plugin-session-replay-browser/src/session-replay.ts
packages/plugin-session-replay-browser/src/typings/session-replay.ts
packages/session-replay-browser/src/config/local-config.ts
packages/session-replay-browser/src/config/types.ts
packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/src/utils/rrweb.ts
packages/session-replay-browser/test/session-replay.test.ts

Currently in shadow root contexts script tags may show "SCRIPT_PLACEHOLDER" which is not ideal. This is due to `<script>` tags being captured and replaced with this text. On replay rrweb injects `display: none !important`, but is not added to shadow roots sometimes causing the text to appear.
This can be fixed in the player too, but it's good to have this option if we need it later on. I changed the name of the option on our side since I thought it was clearer, but happy to discuss that one!
[SR-1374](https://amplitude.atlassian.net/browse/SR-1374)
[SR-1374]: https://amplitude.atlassian.net/browse/SR-1374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(session-replay-browser): allows users to omit scripts and comments from being captured

---

packages/plugin-session-replay-browser/README.md
packages/session-replay-browser/src/config/local-config.ts
packages/session-replay-browser/src/constants.ts

Enabling performance compression by default. The user can still alter the performanceConfig options locally. 

perf(session-replay): enable compression performance by default

---

.github/workflows/ci-nx.yml

Remove `ci-nx` GHA on push to branches. It should only run on PRs. 

ci: remove ci nx on push to branches

---

packages/analytics-node-ai/jest.config.js
packages/analytics-node-ai/package.json
packages/analytics-node-ai/src/index.ts
packages/analytics-node-ai/src/openai.ts
packages/analytics-node-ai/src/version.ts
packages/analytics-node-ai/test/openai.test.ts
packages/analytics-node-ai/tsconfig.es5.json
packages/analytics-node-ai/tsconfig.esm.json
packages/analytics-node-ai/tsconfig.json
yarn.lock

chore: stub in new Analytics-Node-AI package

---

packages/segment-session-replay-plugin-react-native/package.json
yarn.lock

…lay-react-native dependency
update SR SDK versions dependency to be less restrictive

chore(segment-session-replay-plugin-react-native): update session-replay-react-native dependency

---

packages/plugin-autocapture-browser/src/autocapture/track-rage-click.ts
packages/plugin-autocapture-browser/test/autocapture-plugin/track-rage-click.test.ts
test-server/autocapture/element-interactions.html

Use a sliding window for rage click instead of a buffer.
Previously, it used a buffer, which has an edge case where 3 events could happen in one window and then another 3 events could happen in the next window, and it could miss a rage click if the buffer time elapsed between the calls.
This PR fixes it so that it just adds clicks to a sliding window, where the clicks expire after a certain time, and the window gets cleared if the next clicked element is not the same as the previously clicked on element.
* Does your PR have a breaking change?:  Yes

fix: use sliding window to capture rage clicks

---

.github/workflows/ci-nx.yml
.github/workflows/ci.yml

This reverts commit 8f641c5c82b2751297424aab70d5c3a3a3580b3c.
publish v2 failed with error "no changed packages" 
However there are plenty of changes when running the command locally
Revert the CI PR to rule out the possibility. 

Revert: "chore: exclusively use Nx for CI workflows (#1220)"

---

packages/targeting/package.json

This PR marks the targeting package as private to hide it from lerna version to unblock publish v2 GHA. Should fix targeting package in a separate PR. 
[Publish v2 GHA](https://github.com/amplitude/Amplitude-TypeScript/actions/runs/16605794516/job/46977131456) failed without explicit error message. 
I ran `npm run deploy:version --no-private --create-release` locally and got the error
```
error Invariant Violation: expected workspace package to exist for "glob"
at invariant (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:2318:15)
at _loop2 (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:91560:9)
at PackageHoister.init (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:91619:19)
at PackageLinker.getFlatHoistedTree (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:48551:20 …
```

chore(targeting): make it private for publish

---

.github/workflows/publish-v2.yml

This PR prevent GHA step from stopping immediately before it can execute output with detailed error messages.
An example of current publish v2 not printing output: https://github.com/amplitude/Amplitude-TypeScript/pull/1224

ci: output error message

---

packages/session-replay-browser/src/session-replay.ts

Adding additional metadata for helping debug TRC capturing conditions - 
```
Amplitude Logger [Debug]: {
"name": "targeted replay capture config",
"sessionTargetingMatch": false,
"targetingParams": {
"event": {
"user_id": "XXX",
"device_id": "XXX",
"session_id": XXX,
"time": 1754954595601,
"platform": "Web",
"language": "en-US",
"ip": "$remote",
"insert_id": "XXX",
"event_type": "$identify",
"user_properties": {
"$set": {
"propertyBeforeInit": "true"
}
},
"event_id": 3604,
"library": "amplitude-ts/2.11.9",
"user_agent": "XXX"
},
"userProperties": {
"propertyBeforeInit": "true"
}
}
}
```

chore(session replay): additional debug logging for trc

---

packages/analytics-core/src/index.ts
packages/analytics-core/src/utils/url-utils.ts
packages/analytics-core/test/utils/url-utils.test.ts
packages/plugin-autocapture-browser/src/helpers.ts
packages/plugin-autocapture-browser/test/helpers.test.ts

Move `isPageUrlAllowed` into a helper function in `analytics-core` so that it can be used by other autocapture features.

refactor(analytics-core): migrate isPageUrlAllowed to general helper function

---

packages/analytics-core/src/network-request-event.ts
packages/analytics-core/test/network-observer.test.ts

Upon careful consideration, I think it's unwise to make the `pruneHeaders` function mutate the headers object. There's a risk that somebody could unwittingly pass the original headers object into `pruneHeaders` by mistake and mutate it. Not worth the performance boost.
This PR changes it so that `pruneHeaders` returns a new headers object that has the key/value pairings pruned from the original. The original object is untouched.

refactor(analytics-core): change pruneHeaders to be non-mutative

---

packages/plugin-autocapture-browser/src/helpers.ts
packages/plugin-autocapture-browser/test/helpers.test.ts
yarn.lock

Add email address regex match filtering along with credit card and SSN.

feat(autocapture): add filtering for email in isNonSensitiveString

---

packages/analytics-browser/src/index.ts

* Add "getIdentity" and "getOptOut" to the "analytics-browser" index
* This fixes a type issue, these two attributes not being present in the "default" export make it not be duck-typable as a BrowserClient

fix: add missing BrowserClient attributes

---

packages/analytics-browser/test/index.test.ts
packages/analytics-browser/test/utils/fake-browser-client.ts

Add test that verifies that the export of "analytics-browser" index is instance of BrowserClient (structural typing test).
Methodology: Create a "FakeBrowserClient" that implements "BrowserClient" and then check that the methods in "analytics-browser" default export match methods in `BrowserClient.prototype`

chore: test default amplitude is BrowserClient

---

packages/session-replay-browser/src/session-replay.ts
packages/session-replay-browser/test/session-replay.test.ts

The evaluateTargetingAndCapture function is currently being used to call `recordEvent`. We should limit this two only 2 scenarios: 
- Initialization
- TRC evaluation

perf(session-replay): reduce record initializations for targeting 

---

packages/analytics-core/src/diagnostics/diagnostics-client.ts
packages/analytics-core/src/diagnostics/diagnostics-storage.ts
packages/analytics-core/src/index.ts
packages/analytics-core/test/diagnostics/diagnostics-client.test.ts
packages/analytics-core/test/diagnostics/diagnostics-storage.test.ts
packages/analytics-core/test/index.test.ts
test-server/diagnostics-test.html

Add a diagnostics client with APIs: 
- setTag() for tag
- increment() for counter
- recordHistogram for histogram
- recordEvent for event. This will be added later after the diagnostic server supports events in the request payload
The client has two storages
- memory storage as cache
- auto save to persistent storage every 1 second if there is any data
- indexedDB as persistent storage
- auto flush every 5 minutes if there is any data
The client also flushes on initialization when last flush time stored in indexedDB has passed 5 minutes.
The code is based on the diagnostics client design [here](https://amplitude.atlassian.net/wiki/spaces/GOV/pages/3270639769/Diagnostics+client+design).
I'm heavily using `istanbul ignore next` in diagnostics-storage for test coverage as it's mainly just …

feat(analytics-core): add diagnostics client

---

packages/plugin-ga-events-forwarder-browser/src/ga-events-forwarder.ts
packages/plugin-ga-events-forwarder-browser/test/ga-events-forwarder.test.ts

Problem: relative URL's cause `new URL` to throw an exception in the `intercept` function, which logs a console error in the catch block, which is creating a lot of noise for one of our customers.
Solution: move the `new URL` function before the try catch block into it's own try catch block. In this block, the catch doesn't log an error. No need to log an error, because if it reaches that block it means that it's a relative URL.

fix(plugin-ga-events-forwarder-browser): do not log errors on relative URLs

---

packages/analytics-browser/src/browser-client.ts
packages/analytics-browser/src/default-tracking.ts
packages/analytics-browser/test/default-tracking.test.ts
test-server/autocapture/element-interactions.html

Hide this warning if "urls" or "hosts" is empty:

fix(analytics-browser): suppress unnecessary url warnings

---

packages/analytics-browser/src/browser-client.ts

This PR reverts the changes from the "fix: support timestamp override for Experiment events" commit.

revert(analytics-browser): revert "fix: support timestamp override for Experiment events"
